// Auto-generated by @miuprep/content. Run npm.cmd run sync:portal-quality -w @miuprep/content after content changes.
export interface ContentQualityIssueSnapshot {
  code: string;
  count: number;
}

export interface EnglishSkillReadinessSnapshot {
  skill: 'reading' | 'listening' | 'use_of_english' | 'writing' | 'speaking';
  label: string;
  totalItems: number;
  learningReadyItems: number;
  feedbackOnlyItems: number;
  blockerItems: number;
  warningItems: number;
  byProgram: Record<string, number>;
}

export interface EnglishContentQualitySnapshot {
  schemaVersion: 'english_content_guard_v1';
  generatedAt: string;
  sourceCommand: string;
  qualitySummary: {
    tests: number;
    questions: number;
    blockers: number;
    warnings: number;
    byProgram: Record<string, number>;
    topIssues: ContentQualityIssueSnapshot[];
  };
  coverage: {
    readyQuestions: number;
    blockedQuestions: number;
    warningIssues: number;
    byProgram: Record<string, number>;
    bySkill: Record<string, number>;
    byQuestionType: Record<string, number>;
    byConcept: Record<string, number>;
    bySourceTest: Record<string, number>;
  };
  skillReadiness: EnglishSkillReadinessSnapshot[];
  adapter: {
    readyItems: number;
    mockTests: number;
    passages: number;
    errorCount: number;
    pass: boolean;
  };
}

export interface ContentCoverageProgramSnapshot {
  programId: string;
  label: string;
  sourceQuestions: number;
  importedQuestions: number;
  readyQuestions: number;
  blockerItems: number;
  warningItems: number;
  feedbackOnlyItems?: number;
  adapterPass: boolean;
  coverageStatus: 'ready' | 'watch' | 'planned' | 'needs_repair';
  sourceMatched?: boolean;
  changedQuestions?: number;
  sourceFiles?: number;
  sourceFormats?: Record<string, number>;
  sourcePath?: string;
  currentPath?: string;
  note: string;
}

export interface UnifiedContentCoverageSnapshot {
  schemaVersion: 'miuprep_content_coverage_v1';
  generatedAt: string;
  programs: ContentCoverageProgramSnapshot[];
}

export const ENGLISH_CONTENT_QUALITY_SNAPSHOT: EnglishContentQualitySnapshot = {
  "schemaVersion": "english_content_guard_v1",
  "generatedAt": "2026-06-04T13:51:00.334Z",
  "sourceCommand": "npm.cmd run sync:portal-quality -w @miuprep/content",
  "qualitySummary": {
    "tests": 95,
    "questions": 7098,
    "blockers": 0,
    "warnings": 112,
    "byProgram": {
      "ielts": 6,
      "cpe": 47,
      "cae": 42
    },
    "topIssues": [
      {
        "code": "schema.sections[*].questionGroups[*].questions[*].blankIndex",
        "count": 64
      },
      {
        "code": "schema.sections[*].transcript",
        "count": 48
      }
    ]
  },
  "coverage": {
    "readyQuestions": 6990,
    "blockedQuestions": 0,
    "warningIssues": 112,
    "byProgram": {
      "ielts": 110,
      "cpe": 3051,
      "cae": 3829
    },
    "bySkill": {
      "reading": 2049,
      "listening": 1115,
      "use_of_english": 3826
    },
    "byQuestionType": {
      "gap_fill": 3082,
      "multiple_choice": 3131,
      "true_false_not_given": 14,
      "matching_headings": 8,
      "map_labeling": 2,
      "gapped_text": 337,
      "multiple_matching": 416
    },
    "byConcept": {
      "eng.reading_inference": 6141,
      "eng.vocabulary_range": 6251,
      "eng.grammar_accuracy": 4643,
      "eng.listening_main_idea": 1119,
      "eng.listening_detail": 1119,
      "eng.listening_inference": 1119
    },
    "bySourceTest": {
      "reading-sample-1": 40,
      "reading-sample-2": 8,
      "reading-sample-3": 8,
      "listening-sample-1": 40,
      "listening-sample-2": 7,
      "listening-sample-3": 7,
      "cpe-sample-1": 53,
      "cpe-practice-test1-book3": 53,
      "cpe-practice-test2-book3": 53,
      "cpe-practice-test3-book3": 53,
      "cpe-practice-test4-book3": 53,
      "cpe-practice-test5-book3": 53,
      "cpe-practice-test6-book3": 53,
      "cpe2-test1": 68,
      "cpe2-test2": 72,
      "cpe2-test3": 73,
      "cpe2-test4": 73,
      "cpe2-test5": 73,
      "cpe2-test6": 73,
      "cam-cpe1-test1": 53,
      "cam-cpe1-test2": 53,
      "cam-cpe1-test3": 53,
      "cam-cpe1-test4": 53,
      "camcp2-test1": 53,
      "camcp2-test2": 53,
      "camcp2-test3": 53,
      "camcp2-test4": 53,
      "camcp2-listening-topic-bank": 112,
      "camcp3-test1": 73,
      "camcp3-test2": 73,
      "camcp3-test3": 73,
      "camcp3-test4": 73,
      "camcp3-listening-topic-bank": 112,
      "camcp4-test1": 73,
      "camcp4-test2": 73,
      "camcp4-test3": 73,
      "camcp4-test4": 73,
      "camcp4-listening-topic-bank": 112,
      "camcp5-test1": 73,
      "camcp5-test2": 73,
      "camcp5-test3": 73,
      "camcp5-test4": 73,
      "camcp5-listening-topic-bank": 112,
      "cpe-entry-test1": 50,
      "cpe-entry-test2": 50,
      "cpe-entry-test3": 50,
      "cpe-entry-test4": 50,
      "cpe-entry-test5": 50,
      "cpe-entry-test6": 50,
      "cpe-entry-test7": 50,
      "cpe-entry-test8": 50,
      "cpe-entry-test9": 50,
      "cpe-entry-test10": 50,
      "cae-error-correction-bank": 30,
      "cae-official-practice-test1": 56,
      "cam-cae-plus1-test1": 122,
      "cam-cae-plus1-test2": 122,
      "cam-cae-plus1-test3": 128,
      "cam-cae-plus1-test4": 126,
      "cam-cae-plus1-test5": 122,
      "cam-cae1-listening-topic-bank": 120,
      "cam-cae1-test1": 84,
      "cam-cae1-test2": 84,
      "cam-cae1-test3": 84,
      "cam-cae1-test4": 84,
      "cam-cae2-listening-topic-bank": 120,
      "cam-cae2-test1": 84,
      "cam-cae2-test2": 84,
      "cam-cae2-test3": 84,
      "cam-cae2-test4": 84,
      "cam-cae3-listening-topic-bank": 120,
      "cam-cae3-test1": 84,
      "cam-cae3-test2": 84,
      "cam-cae3-test3": 84,
      "cam-cae3-test4": 84,
      "cam-cae4-listening-topic-bank": 120,
      "cam-cae4-test1": 125,
      "cam-cae4-test2": 122,
      "cam-cae4-test3": 123,
      "cam-cae4-test4": 122,
      "cam-cae5-test1": 127,
      "cam-cae5-test2": 125,
      "cam-cae5-test3": 128,
      "cam-cae5-test4": 127,
      "cam-cae6-listening-topic-bank": 133,
      "cam-cae6-test1": 126,
      "cam-cae6-test2": 127,
      "cam-cae6-test3": 125,
      "cam-cae6-test4": 125
    }
  },
  "skillReadiness": [
    {
      "skill": "reading",
      "label": "Reading",
      "totalItems": 2049,
      "learningReadyItems": 2049,
      "feedbackOnlyItems": 0,
      "blockerItems": 0,
      "warningItems": 64,
      "byProgram": {
        "ielts": 56,
        "cpe": 797,
        "cae": 1196
      }
    },
    {
      "skill": "listening",
      "label": "Listening",
      "totalItems": 1115,
      "learningReadyItems": 1115,
      "feedbackOnlyItems": 0,
      "blockerItems": 0,
      "warningItems": 48,
      "byProgram": {
        "ielts": 54,
        "cpe": 448,
        "cae": 613
      }
    },
    {
      "skill": "use_of_english",
      "label": "Use of English",
      "totalItems": 3826,
      "learningReadyItems": 3826,
      "feedbackOnlyItems": 0,
      "blockerItems": 0,
      "warningItems": 0,
      "byProgram": {
        "cpe": 1806,
        "cae": 2020
      }
    },
    {
      "skill": "writing",
      "label": "Writing",
      "totalItems": 67,
      "learningReadyItems": 0,
      "feedbackOnlyItems": 67,
      "blockerItems": 0,
      "warningItems": 0,
      "byProgram": {
        "cae": 60,
        "cpe": 4,
        "ielts": 3
      }
    },
    {
      "skill": "speaking",
      "label": "Speaking",
      "totalItems": 54,
      "learningReadyItems": 0,
      "feedbackOnlyItems": 54,
      "blockerItems": 0,
      "warningItems": 0,
      "byProgram": {
        "cae": 48,
        "cpe": 3,
        "ielts": 3
      }
    }
  ],
  "adapter": {
    "readyItems": 7098,
    "mockTests": 95,
    "passages": 658,
    "errorCount": 0,
    "pass": true
  }
};

export const CONTENT_COVERAGE_SNAPSHOT: UnifiedContentCoverageSnapshot = {
  "schemaVersion": "miuprep_content_coverage_v1",
  "generatedAt": "2026-06-04T13:51:00.334Z",
  "programs": [
    {
      "programId": "vn_math_6",
      "label": "VN Math 6 Local Sources",
      "sourceQuestions": 1549,
      "importedQuestions": 1549,
      "readyQuestions": 926,
      "blockerItems": 623,
      "warningItems": 20,
      "coverageStatus": "watch",
      "adapterPass": true,
      "sourceMatched": true,
      "changedQuestions": 0,
      "sourceFiles": 75,
      "sourceFormats": {
        "doc": 67,
        "docx": 7,
        "dot": 1
      },
      "sourcePath": "C:\\Users\\HAIQUYNH\\OneDrive\\SACH VIET\\TOAN\\TAI LIEU TOAN 6",
      "currentPath": "C:\\Users\\HAIQUYNH\\OneDrive\\CODE AI\\MIUPREP_SYSTEM\\reports\\content-quality\\math6-raw-extract.json",
      "note": "926/1549 questions are display-ready; 539 geometry SVG figures generated; 623 items remain behind formula/image/encoding gates."
    },
    {
      "programId": "vn_math_9",
      "label": "MiuMath Math 9",
      "sourceQuestions": 485,
      "importedQuestions": 485,
      "readyQuestions": 485,
      "blockerItems": 0,
      "warningItems": 0,
      "coverageStatus": "ready",
      "adapterPass": true,
      "sourceMatched": true,
      "changedQuestions": 0,
      "sourceFiles": 136,
      "sourceFormats": {
        ".rar": 6,
        ".pdf": 106,
        ".docx": 21,
        ".doc": 2,
        ".zip": 1
      },
      "sourcePath": "C:\\Users\\HAIQUYNH\\OneDrive\\CODE AI\\ON THi\\miumath-app\\public\\data\\questions_db.json",
      "currentPath": "C:\\Users\\HAIQUYNH\\OneDrive\\CODE AI\\MIUPREP_SYSTEM\\apps\\miumath-app\\public\\data\\questions_db.json",
      "note": "Counts match source and every question converts to QuestionItem. Local TOAN 9 folder has 136 files for the next guarded import batch."
    },
    {
      "programId": "vn_math_vao_10",
      "label": "MiuMath On Vao 10",
      "sourceQuestions": 485,
      "importedQuestions": 485,
      "readyQuestions": 485,
      "blockerItems": 0,
      "warningItems": 0,
      "coverageStatus": "ready",
      "adapterPass": true,
      "sourceMatched": true,
      "changedQuestions": 0,
      "sourcePath": "C:\\Users\\HAIQUYNH\\OneDrive\\CODE AI\\ON THi\\miumath-app\\public\\data\\questions_db.json",
      "currentPath": "C:\\Users\\HAIQUYNH\\OneDrive\\CODE AI\\MIUPREP_SYSTEM\\apps\\miumath-app\\public\\data\\questions_db.json",
      "note": "Counts match source and every question converts to QuestionItem. The same item bank is tagged for entrance-exam review via vn_math_vao_10."
    },
    {
      "programId": "vn_math_7",
      "label": "VN Math 7 Local Sources",
      "sourceQuestions": 0,
      "importedQuestions": 0,
      "readyQuestions": 0,
      "blockerItems": 0,
      "warningItems": 0,
      "coverageStatus": "planned",
      "adapterPass": true,
      "sourceMatched": true,
      "changedQuestions": 0,
      "sourceFiles": 6,
      "sourceFormats": {
        ".pdf": 5,
        ".docx": 1
      },
      "sourcePath": "C:\\Users\\HAIQUYNH\\OneDrive\\SACH VIET\\TOAN\\toan 7",
      "note": "Source folder is detected; build a Math 7 matrix/importer with the same Math guard before opening items."
    },
    {
      "programId": "vn_math_8",
      "label": "VN Math 8 Local Sources",
      "sourceQuestions": 0,
      "importedQuestions": 0,
      "readyQuestions": 0,
      "blockerItems": 0,
      "warningItems": 0,
      "coverageStatus": "planned",
      "adapterPass": true,
      "sourceMatched": true,
      "changedQuestions": 0,
      "sourceFiles": 25,
      "sourceFormats": {
        ".pdf": 23,
        ".rar": 2
      },
      "sourcePath": "C:\\Users\\HAIQUYNH\\OneDrive\\SACH VIET\\TOAN\\toan 8",
      "note": "Source folder is detected; build a Math 8 matrix/importer with the same Math guard before opening items."
    },
    {
      "programId": "vn_math_10_12",
      "label": "VN Math 10-12 Local Sources",
      "sourceQuestions": 0,
      "importedQuestions": 0,
      "readyQuestions": 0,
      "blockerItems": 0,
      "warningItems": 0,
      "coverageStatus": "planned",
      "adapterPass": true,
      "sourceMatched": true,
      "changedQuestions": 0,
      "sourceFiles": 67,
      "sourceFormats": {
        ".pdf": 62,
        ".doc": 1,
        ".docx": 1,
        ".xlsx": 3
      },
      "sourcePath": "C:\\Users\\HAIQUYNH\\OneDrive\\SACH VIET\\TOAN\\toan 10",
      "note": "Knowledge Graph is ready; source folder is detected and should use the same guarded import/display-ready flow."
    },
    {
      "programId": "sat",
      "label": "SAT Public Package",
      "sourceQuestions": 9305,
      "importedQuestions": 9305,
      "readyQuestions": 9305,
      "blockerItems": 0,
      "warningItems": 0,
      "coverageStatus": "ready",
      "adapterPass": true,
      "sourceMatched": true,
      "changedQuestions": 0,
      "currentPath": "C:\\Users\\HAIQUYNH\\OneDrive\\CODE AI\\MIUPREP_SYSTEM\\apps\\sat-studio\\artifacts\\sat-studio-public-content-package-latest.json",
      "note": "5642 Math and 3663 Reading/Writing items are ready."
    },
    {
      "programId": "ielts",
      "label": "IELTS Layer",
      "sourceQuestions": 116,
      "importedQuestions": 116,
      "readyQuestions": 110,
      "blockerItems": 0,
      "warningItems": 6,
      "coverageStatus": "watch",
      "feedbackOnlyItems": 6,
      "adapterPass": true,
      "sourceMatched": true,
      "changedQuestions": 0,
      "note": "110 mastery-ready questions and 6 feedback-only Writing/Speaking samples in the shared English catalog."
    },
    {
      "programId": "cpe",
      "label": "CPE",
      "sourceQuestions": 3058,
      "importedQuestions": 3058,
      "readyQuestions": 3051,
      "blockerItems": 0,
      "warningItems": 47,
      "coverageStatus": "watch",
      "feedbackOnlyItems": 7,
      "adapterPass": true,
      "sourceMatched": true,
      "changedQuestions": 0,
      "note": "3051 mastery-ready questions and 7 feedback-only Writing/Speaking samples in the shared English catalog."
    },
    {
      "programId": "cae",
      "label": "CAE",
      "sourceQuestions": 3937,
      "importedQuestions": 3937,
      "readyQuestions": 3829,
      "blockerItems": 0,
      "warningItems": 42,
      "coverageStatus": "watch",
      "feedbackOnlyItems": 108,
      "adapterPass": true,
      "sourceMatched": true,
      "changedQuestions": 0,
      "note": "3829 mastery-ready questions and 108 feedback-only Writing/Speaking samples in the shared English catalog."
    }
  ]
};
