import { buildEnglishContentGuardReport, type EnglishContentGuardReport } from './english-content-guard-report';
import { buildMath6ContentGuardReport } from './math6-content-guard-report';
import type { Math6RawSource } from './math6-import';
import { buildMath8ContentGuardReport } from './math8-content-guard-report';
import type { Math8RawSource } from './math8-import';
import { buildMath9ContentGuardReport } from './math9-content-guard-report';
import type { Math9RawSource } from './math9-import';
import { buildMath10ContentGuardReport } from './math10-content-guard-report';
import type { Math10RawSource } from './math10-import';
import { buildMath11ContentGuardReport } from './math11-content-guard-report';
import type { Math11RawSource } from './math11-import';
import { buildMath7ContentGuardReport } from './math7-content-guard-report';
import type { Math7RawSource } from './math7-import';
import { buildMiuMathContentGuardReport } from './miumath-content-guard-report';
import { buildSatContentReadinessSnapshot, type SatPublicStudentPackage } from './sat-content';
import { toQuestionItemsFromMiuMath, type MiuMathQuestion, type QuestionItem } from './standard';

declare function require(name: string): any;
declare const process: { argv: string[]; cwd(): string; exitCode?: number };

const fs = require('node:fs');
const path = require('node:path');

const report = buildEnglishContentGuardReport();
const workspaceRoot = findWorkspaceRoot(process.cwd());
const targetPath = getArgValue('--target') || path.join(workspaceRoot, 'apps', 'miuprep-portal', 'src', 'data', 'contentQualitySnapshot.ts');
const coverageSnapshot = buildUnifiedCoverageSnapshot(workspaceRoot, report);

fs.mkdirSync(path.dirname(targetPath), { recursive: true });
fs.writeFileSync(targetPath, renderPortalSnapshot(report, coverageSnapshot));

console.log(`Synced English content quality snapshot to ${targetPath}`);
console.log(
  JSON.stringify(
    {
      readyQuestions: report.coverage.readyQuestions,
      blockedQuestions: report.coverage.blockedQuestions,
      adapterPass: report.adapter.pass,
      topIssues: report.qualitySummary.topIssues,
      coverage: coverageSnapshot.programs.map((program) => ({
        programId: program.programId,
        coverageStatus: program.coverageStatus,
        importedQuestions: program.importedQuestions,
        readyQuestions: program.readyQuestions,
        blockerItems: program.blockerItems,
        adapterPass: program.adapterPass,
      })),
    },
    null,
    2,
  ),
);

if (report.adapter.errors.length) {
  process.exitCode = 1;
}

interface UnifiedContentCoverageSnapshot {
  schemaVersion: 'miuprep_content_coverage_v1';
  generatedAt: string;
  programs: Array<{
    programId: string;
    label: string;
    sourceQuestions: number;
    importedQuestions: number;
    readyQuestions: number;
    blockerItems: number;
    warningItems: number;
    feedbackOnlyItems?: number;
    coverageStatus: 'ready' | 'watch' | 'planned' | 'needs_repair';
    adapterPass: boolean;
    sourceMatched?: boolean;
    changedQuestions?: number;
    sourceFiles?: number;
    sourceFormats?: Record<string, number>;
    sourcePath?: string;
    currentPath?: string;
    note: string;
  }>;
}

function renderPortalSnapshot(guardReport: EnglishContentGuardReport, coverageSnapshot: UnifiedContentCoverageSnapshot): string {
  const snapshot = {
    schemaVersion: guardReport.schemaVersion,
    generatedAt: guardReport.generatedAt,
    sourceCommand: 'npm.cmd run sync:portal-quality -w @miuprep/content',
    qualitySummary: {
      tests: guardReport.qualitySummary.tests,
      questions: guardReport.qualitySummary.questions,
      blockers: guardReport.qualitySummary.blockers,
      warnings: guardReport.qualitySummary.warnings,
      byProgram: guardReport.qualitySummary.byProgram,
      topIssues: guardReport.qualitySummary.topIssues,
    },
    coverage: {
      readyQuestions: guardReport.coverage.readyQuestions,
      blockedQuestions: guardReport.coverage.blockedQuestions,
      warningIssues: guardReport.coverage.warningIssues,
      byProgram: guardReport.coverage.byProgram,
      bySkill: guardReport.coverage.bySkill,
      byQuestionType: guardReport.coverage.byQuestionType,
      byConcept: guardReport.coverage.byConcept,
      bySourceTest: guardReport.coverage.bySourceTest,
    },
    skillReadiness: guardReport.skillReadiness,
    adapter: {
      readyItems: guardReport.adapter.readyItems,
      mockTests: guardReport.adapter.mockTests,
      passages: guardReport.adapter.passages,
      errorCount: guardReport.adapter.errors.length,
      pass: guardReport.adapter.pass,
    },
  };

  return `// Auto-generated by @miuprep/content. Run npm.cmd run sync:portal-quality -w @miuprep/content after content changes.
export interface ContentQualityIssueSnapshot {
  code: string;
  count: number;
}

export interface EnglishSkillReadinessSnapshot {
  skill: 'reading' | 'listening' | 'use_of_english' | 'writing' | 'speaking';
  label: string;
  totalItems: number;
  learningReadyItems: number;
  feedbackOnlyItems: number;
  blockerItems: number;
  warningItems: number;
  byProgram: Record<string, number>;
}

export interface EnglishContentQualitySnapshot {
  schemaVersion: 'english_content_guard_v1';
  generatedAt: string;
  sourceCommand: string;
  qualitySummary: {
    tests: number;
    questions: number;
    blockers: number;
    warnings: number;
    byProgram: Record<string, number>;
    topIssues: ContentQualityIssueSnapshot[];
  };
  coverage: {
    readyQuestions: number;
    blockedQuestions: number;
    warningIssues: number;
    byProgram: Record<string, number>;
    bySkill: Record<string, number>;
    byQuestionType: Record<string, number>;
    byConcept: Record<string, number>;
    bySourceTest: Record<string, number>;
  };
  skillReadiness: EnglishSkillReadinessSnapshot[];
  adapter: {
    readyItems: number;
    mockTests: number;
    passages: number;
    errorCount: number;
    pass: boolean;
  };
}

export interface ContentCoverageProgramSnapshot {
  programId: string;
  label: string;
  sourceQuestions: number;
  importedQuestions: number;
  readyQuestions: number;
  blockerItems: number;
  warningItems: number;
  feedbackOnlyItems?: number;
  adapterPass: boolean;
  coverageStatus: 'ready' | 'watch' | 'planned' | 'needs_repair';
  sourceMatched?: boolean;
  changedQuestions?: number;
  sourceFiles?: number;
  sourceFormats?: Record<string, number>;
  sourcePath?: string;
  currentPath?: string;
  note: string;
}

export interface UnifiedContentCoverageSnapshot {
  schemaVersion: 'miuprep_content_coverage_v1';
  generatedAt: string;
  programs: ContentCoverageProgramSnapshot[];
}

export const ENGLISH_CONTENT_QUALITY_SNAPSHOT: EnglishContentQualitySnapshot = ${JSON.stringify(snapshot, null, 2)};

export const CONTENT_COVERAGE_SNAPSHOT: UnifiedContentCoverageSnapshot = ${JSON.stringify(coverageSnapshot, null, 2)};
`;
}

function buildUnifiedCoverageSnapshot(workspaceRootPath: string, englishReport: EnglishContentGuardReport): UnifiedContentCoverageSnapshot {
  const generatedAt = englishReport.generatedAt;
  const programs: UnifiedContentCoverageSnapshot['programs'] = [];
  const localMathSourceRoot = path.resolve(workspaceRootPath, '..', '..', 'SACH VIET', 'TOAN');
  const math6RawPath = resolveDefaultMath6RawPath(workspaceRootPath);
  let miumathItemsForCoverage: QuestionItem[] = [];
  let miumathAdapterPass = true;
  let miumathBlockers = 0;
  let miumathWarnings = 0;

  if (fs.existsSync(math6RawPath)) {
    const rawSources = readMath6RawSources(math6RawPath);
    const math6Report = buildMath6ContentGuardReport(rawSources, {
      rawPath: math6RawPath,
      generatedAt,
      formulaAssetExists: (src) => mathFormulaAssetExists(workspaceRootPath, src),
    }).report;
    const scoredReadyItems = math6Report.pedagogy.scoredPracticeReady;
    const blockedItems = math6Report.qualitySummary.blockers;
    const warningItems = math6Report.qualitySummary.warnings;
    programs.push({
      programId: 'vn_math_6',
      label: 'VN Math 6 Local Sources',
      sourceQuestions: math6Report.stats.questions,
      importedQuestions: math6Report.adapter.convertedItems,
      readyQuestions: scoredReadyItems,
      blockerItems: blockedItems,
      warningItems,
      coverageStatus: !math6Report.adapter.pass || scoredReadyItems === 0 ? 'needs_repair' : blockedItems > 0 || warningItems > 0 ? 'watch' : 'ready',
      adapterPass: math6Report.adapter.pass,
      sourceMatched: true,
      changedQuestions: 0,
      sourceFiles: math6Report.input.sources,
      sourceFormats: countSourceFormats(rawSources),
      sourcePath: path.resolve(localMathSourceRoot, 'TAI LIEU TOAN 6'),
      currentPath: math6RawPath,
      note: `${math6Report.stats.displayReady}/${math6Report.stats.questions} questions are display-ready; ${scoredReadyItems}/${math6Report.stats.questions} are scored-practice-ready; ${math6Report.pedagogy.scoredPracticeExcluded} source-artifact/formula-image items are held for review, with ${math6Report.pedagogy.scoredPracticePending} eligible items still pending answer keys.`,
    });
  } else {
    programs.push(buildPlannedMathProgramRow('vn_math_6', 'VN Math 6 Local Sources', path.resolve(localMathSourceRoot, 'TAI LIEU TOAN 6'), 'Raw extract is missing; run the Math 6 extractor before guard/import.'));
  }

  const miumathCurrentPath = path.resolve(workspaceRootPath, 'apps', 'miumath-app', 'public', 'data', 'questions_db.json');
  const miumathSourcePath = path.resolve(workspaceRootPath, '..', 'ON THi', 'miumath-app', 'public', 'data', 'questions_db.json');

  if (fs.existsSync(miumathCurrentPath)) {
    const currentQuestions = readJsonArray<MiuMathQuestion>(miumathCurrentPath);
    const sourceQuestions = fs.existsSync(miumathSourcePath) ? readJsonArray<MiuMathQuestion>(miumathSourcePath) : undefined;
    const miumathReport = buildMiuMathContentGuardReport(currentQuestions, {
      currentPath: miumathCurrentPath,
      sourcePath: sourceQuestions ? miumathSourcePath : undefined,
      sourceQuestions,
    });
    const miumathItems = toQuestionItemsFromMiuMath(currentQuestions);
    miumathItemsForCoverage = miumathItems;
    miumathAdapterPass = miumathReport.adapter.pass;
    miumathBlockers = miumathReport.qualitySummary.blockers;
    miumathWarnings = miumathReport.qualitySummary.warnings;
    const localMath9Sources = scanSourceFolder(path.resolve(localMathSourceRoot, 'TOAN 9'));
    programs.push(...buildMiuMathProgramRows(miumathReport, miumathItems, localMath9Sources));
  }

  const math9RawPath = path.resolve(workspaceRootPath, 'reports', 'content-quality', 'math9-rich-raw-extract.json');
  const math9HsgPath = path.resolve(workspaceRootPath, 'reports', 'content-quality', 'math9-hsg-raw-extract.json');
  const math9OnVao10Path = path.resolve(workspaceRootPath, 'reports', 'content-quality', 'math9-onvao10-rich-raw-extract.json');
  if (fs.existsSync(math9RawPath) || fs.existsSync(math9HsgPath) || fs.existsSync(math9OnVao10Path)) {
    const rawSources9 = fs.existsSync(math9RawPath) ? readMath9RawSources(math9RawPath) : [];
    if (fs.existsSync(math9HsgPath)) {
      const hsgSources9 = readMath9RawSources(math9HsgPath);
      rawSources9.push(...hsgSources9);
    }
    if (fs.existsSync(math9OnVao10Path)) {
      const onVao10Sources9 = readMath9RawSources(math9OnVao10Path);
      rawSources9.push(...onVao10Sources9);
    }
    const uniqueRawSources9 = dedupeMathRawSources(rawSources9);
    const activeMath9RawPath = fs.existsSync(math9RawPath) ? math9RawPath : fs.existsSync(math9OnVao10Path) ? math9OnVao10Path : math9HsgPath;
    const math9GuardResult = buildMath9ContentGuardReport(uniqueRawSources9, {
      rawPath: activeMath9RawPath,
      generatedAt,
      formulaAssetExists: (src) => mathFormulaAssetExists(workspaceRootPath, src),
    });
    const math9Report = math9GuardResult.report;
    const blockedItems9 = Math.max(0, math9Report.stats.questions - math9Report.stats.displayReady);
    const unscoredItems9 = Math.max(0, math9Report.stats.displayReady - math9Report.stats.scoredPracticeReady);
    programs.push({
      programId: 'vn_math_9_local_sources',
      label: 'VN Math 9 Local Sources',
      sourceQuestions: math9Report.stats.questions,
      importedQuestions: math9Report.adapter.convertedItems,
      readyQuestions: math9Report.stats.displayReady,
      blockerItems: blockedItems9,
      warningItems: math9Report.qualitySummary.warnings,
      coverageStatus: !math9Report.adapter.pass || math9Report.stats.displayReady === 0 ? 'needs_repair' : blockedItems9 > 0 ? 'watch' : 'ready',
      adapterPass: math9Report.adapter.pass,
      sourceMatched: true,
      changedQuestions: 0,
      sourceFiles: math9Report.input.sources,
      sourceFormats: countSourceFormats(uniqueRawSources9),
      sourcePath: path.resolve(localMathSourceRoot, 'TOAN 9'),
      currentPath: activeMath9RawPath,
      note: `${math9Report.stats.displayReady}/${math9Report.stats.questions} questions are display-ready from local Math 9 sources; ${math9Report.stats.scoredPracticeReady} have source answers/solutions for scored practice; ${blockedItems9} items remain behind formula/image/encoding gates and ${unscoredItems9} display-ready items still need answer keys.`,
    });
    programs.push(buildCombinedExam10ProgramRow({
      miumathItems: miumathItemsForCoverage,
      miumathAdapterPass,
      miumathBlockers,
      miumathWarnings,
      math9Items: math9GuardResult.items,
      math9Report,
      sourcePath: path.resolve(localMathSourceRoot, 'TOAN 9'),
      currentPath: activeMath9RawPath,
    }));
  } else {
    programs.push(buildPlannedMathProgramRow('vn_math_9_local_sources', 'VN Math 9 Local Sources', path.resolve(localMathSourceRoot, 'TOAN 9'), 'Source folder is detected; run the Math 9 rich extractor and guard before opening local items.'));
  }

  const math7RawPath = path.resolve(workspaceRootPath, 'reports', 'content-quality', 'math7-rich-raw-extract.json');
  if (fs.existsSync(math7RawPath) || fs.existsSync(path.resolve(workspaceRootPath, 'reports', 'content-quality', 'math7-hsg-raw-extract.json'))) {
    const rawSources7 = fs.existsSync(math7RawPath) ? readMath7RawSources(math7RawPath) : [];
    const math7HsgPath = path.resolve(workspaceRootPath, 'reports', 'content-quality', 'math7-hsg-raw-extract.json');
    if (fs.existsSync(math7HsgPath)) {
      const hsgSources7 = readMath7RawSources(math7HsgPath);
      rawSources7.push(...hsgSources7);
    }
    const seenFiles7 = new Set<string>();
    const uniqueRawSources7: Math7RawSource[] = [];
    for (const src of rawSources7) {
      const key = src.relativePath || src.fileName;
      if (!seenFiles7.has(key)) {
        seenFiles7.add(key);
        uniqueRawSources7.push(src);
      }
    }
    const activeRawPath = fs.existsSync(math7RawPath) ? math7RawPath : math7HsgPath;
    const math7Report = buildMath7ContentGuardReport(uniqueRawSources7, { rawPath: activeRawPath, generatedAt }).report;
    const blockedItems7 = Math.max(0, math7Report.stats.questions - math7Report.stats.displayReady);
    programs.push({
      programId: 'vn_math_7',
      label: 'VN Math 7 Local Sources',
      sourceQuestions: math7Report.stats.questions,
      importedQuestions: math7Report.adapter.convertedItems,
      readyQuestions: math7Report.stats.displayReady,
      blockerItems: blockedItems7,
      warningItems: math7Report.qualitySummary.warnings,
      coverageStatus: !math7Report.adapter.pass || math7Report.stats.displayReady === 0 ? 'needs_repair' : blockedItems7 > 0 ? 'watch' : 'ready',
      adapterPass: math7Report.adapter.pass,
      sourceMatched: true,
      changedQuestions: 0,
      sourceFiles: math7Report.input.sources,
      sourceFormats: countSourceFormats(rawSources7),
      sourcePath: path.resolve(localMathSourceRoot, 'toan 7'),
      currentPath: activeRawPath,
      note: `${math7Report.stats.displayReady}/${math7Report.stats.questions} questions are display-ready; ${blockedItems7} items remain behind formula/image/encoding gates.`,
    });
  } else {
    programs.push(buildPlannedMathProgramRow('vn_math_7', 'VN Math 7 Local Sources', path.resolve(localMathSourceRoot, 'toan 7'), 'Source folder is detected; build a Math 7 matrix/importer with the same Math guard before opening items.'));
  }
  const math8RawPath = path.resolve(workspaceRootPath, 'reports', 'content-quality', 'math8-rich-raw-extract.json');
  if (fs.existsSync(math8RawPath) || fs.existsSync(path.resolve(workspaceRootPath, 'reports/content-quality/math8-hsg-raw-extract.json'))) {
    const rawSources8 = fs.existsSync(math8RawPath) ? readMath8RawSources(math8RawPath) : [];
    const math8HsgPath = path.resolve(workspaceRootPath, 'reports/content-quality/math8-hsg-raw-extract.json');
    if (fs.existsSync(math8HsgPath)) {
      const hsgSources8 = readMath8RawSources(math8HsgPath);
      rawSources8.push(...hsgSources8);
    }
    const seenFiles8 = new Set<string>();
    const uniqueRawSources8: Math8RawSource[] = [];
    for (const src of rawSources8) {
      const key = src.relativePath || src.fileName;
      if (!seenFiles8.has(key)) {
        seenFiles8.add(key);
        uniqueRawSources8.push(src);
      }
    }
    const activeRawPath = fs.existsSync(math8RawPath) ? math8RawPath : math8HsgPath;
    const math8Report = buildMath8ContentGuardReport(uniqueRawSources8, { rawPath: activeRawPath, generatedAt }).report;
    const blockedItems8 = Math.max(0, math8Report.stats.questions - math8Report.stats.displayReady);
    programs.push({
      programId: 'vn_math_8',
      label: 'VN Math 8 Local Sources',
      sourceQuestions: math8Report.stats.questions,
      importedQuestions: math8Report.adapter.convertedItems,
      readyQuestions: math8Report.stats.displayReady,
      blockerItems: blockedItems8,
      warningItems: math8Report.qualitySummary.warnings,
      coverageStatus: !math8Report.adapter.pass || math8Report.stats.displayReady === 0 ? 'needs_repair' : blockedItems8 > 0 ? 'watch' : 'ready',
      adapterPass: math8Report.adapter.pass,
      sourceMatched: true,
      changedQuestions: 0,
      sourceFiles: math8Report.input.sources,
      sourceFormats: countSourceFormats(rawSources8),
      sourcePath: path.resolve(localMathSourceRoot, 'toan 8'),
      currentPath: math8RawPath,
      note: `${math8Report.stats.displayReady}/${math8Report.stats.questions} questions are display-ready; ${blockedItems8} items remain behind formula/image/encoding gates.`,
    });
  } else {
    programs.push(buildPlannedMathProgramRow('vn_math_8', 'VN Math 8 Local Sources', path.resolve(localMathSourceRoot, 'toan 8'), 'Source folder is detected; build a Math 8 matrix/importer with the same Math guard before opening items.'));
  }
  const math10RawPath = path.resolve(workspaceRootPath, 'reports', 'content-quality', 'math10-rich-raw-extract.json');
  if (fs.existsSync(math10RawPath)) {
    const rawSources10 = readMath10RawSources(math10RawPath);
    const math10Report = buildMath10ContentGuardReport(rawSources10, { rawPath: math10RawPath, generatedAt }).report;
    const publishedItems10 = math10Report.stats.displayReady;
    const excludedItems10 = Math.max(0, math10Report.stats.questions - math10Report.stats.displayReady);
    const math10PublishedPath = path.resolve(workspaceRootPath, 'reports', 'content-quality', 'math10-published-question-bank.json');
    programs.push({
      programId: 'vn_math_10_12',
      label: 'VN Math 10-12 Local Sources',
      sourceQuestions: publishedItems10,
      importedQuestions: publishedItems10,
      readyQuestions: publishedItems10,
      blockerItems: 0,
      warningItems: math10Report.qualitySummary.warnings,
      coverageStatus: !math10Report.adapter.pass || publishedItems10 === 0 ? 'needs_repair' : math10Report.qualitySummary.warnings > 0 ? 'watch' : 'ready',
      adapterPass: math10Report.adapter.pass,
      sourceMatched: true,
      changedQuestions: 0,
      sourceFiles: math10Report.input.sources,
      sourceFormats: countSourceFormats(rawSources10),
      sourcePath: path.resolve(localMathSourceRoot, 'toan 10'),
      currentPath: fs.existsSync(math10PublishedPath) ? math10PublishedPath : math10RawPath,
      note: `${publishedItems10} Math 10 questions are published to the learner system; ${math10Report.stats.scoredPracticeReady}/${publishedItems10} published questions have source or generated MiuMath answers/solutions for scored practice; ${math10Report.stats.generatedSolutions} are generated MiuMath solutions; ${excludedItems10} blocked raw questions were excluded before publish.`,
    });
  } else {
    programs.push(buildPlannedMathProgramRow('vn_math_10_12', 'VN Math 10-12 Local Sources', path.resolve(localMathSourceRoot, 'toan 10'), 'Knowledge Graph is ready; source folder is detected and should use the same guarded import/display-ready flow.'));
  }

  const math11RawPath = path.resolve(workspaceRootPath, 'reports', 'content-quality', 'math11-rich-raw-extract.json');
  if (fs.existsSync(math11RawPath)) {
    const rawSources11 = readMath11RawSources(math11RawPath);
    const math11Report = buildMath11ContentGuardReport(rawSources11, { rawPath: math11RawPath, generatedAt }).report;
    const publishedItems11 = math11Report.stats.displayReady;
    const excludedItems11 = Math.max(0, math11Report.stats.questions - math11Report.stats.displayReady);
    const math11PublishedPath = path.resolve(workspaceRootPath, 'reports', 'content-quality', 'math11-published-question-bank.json');
    programs.push({
      programId: 'vn_math_11_local_sources',
      label: 'VN Math 11 Local Sources',
      sourceQuestions: publishedItems11,
      importedQuestions: publishedItems11,
      readyQuestions: publishedItems11,
      blockerItems: 0,
      warningItems: math11Report.qualitySummary.warnings,
      coverageStatus: !math11Report.adapter.pass || publishedItems11 === 0 ? 'needs_repair' : math11Report.qualitySummary.warnings > 0 ? 'watch' : 'ready',
      adapterPass: math11Report.adapter.pass,
      sourceMatched: true,
      changedQuestions: 0,
      sourceFiles: math11Report.input.sources,
      sourceFormats: countSourceFormats(rawSources11),
      sourcePath: path.resolve(localMathSourceRoot, 'toan 11'),
      currentPath: fs.existsSync(math11PublishedPath) ? math11PublishedPath : math11RawPath,
      note: `${publishedItems11} Math 11 questions are published to the learner system; ${math11Report.stats.scoredPracticeReady}/${publishedItems11} published questions have source answers/solutions for scored practice; ${excludedItems11} blocked raw questions were excluded before publish.`,
    });
  } else {
    programs.push(buildPlannedMathProgramRow('vn_math_11_local_sources', 'VN Math 11 Local Sources', path.resolve(localMathSourceRoot, 'toan 11'), 'Knowledge Graph is ready; source folder is detected and should use the same guarded import/display-ready flow.'));
  }

  const satPackagePath = path.resolve(workspaceRootPath, 'apps', 'sat-studio', 'artifacts', 'sat-studio-public-content-package-latest.json');
  if (fs.existsSync(satPackagePath)) {
    const satPackage = readJson<SatPublicStudentPackage>(satPackagePath);
    const satReport = buildSatContentReadinessSnapshot(satPackage, generatedAt);
    programs.push({
      programId: 'sat',
      label: 'SAT Public Package',
      sourceQuestions: satReport.totalItems,
      importedQuestions: satReport.totalItems,
      readyQuestions: satReport.learningReadyItems,
      blockerItems: satReport.blockerItems,
      warningItems: satReport.warningItems,
      coverageStatus: satReport.blockerItems > 0 || !satReport.adapter.pass ? 'needs_repair' : satReport.warningItems > 0 ? 'watch' : 'ready',
      adapterPass: satReport.adapter.pass,
      sourceMatched: satReport.totalItems === satReport.uniqueIds && satReport.duplicateIds === 0,
      changedQuestions: 0,
      currentPath: satPackagePath,
      note: `${satReport.bySection.Math || 0} Math and ${satReport.bySection['Reading and Writing'] || 0} Reading/Writing items are ready.`,
    });
  }

  programs.push(...buildEnglishProgramCoverageRows(englishReport));

  return {
    schemaVersion: 'miuprep_content_coverage_v1',
    generatedAt,
    programs,
  };
}

function buildMiuMathProgramRows(
  report: ReturnType<typeof buildMiuMathContentGuardReport>,
  items: ReturnType<typeof toQuestionItemsFromMiuMath>,
  localMath9Sources: SourceFolderScan,
): UnifiedContentCoverageSnapshot['programs'] {
  const baseStatus: UnifiedContentCoverageSnapshot['programs'][number]['coverageStatus'] =
    report.qualitySummary.blockers > 0 || !report.adapter.pass
      ? 'needs_repair'
      : report.qualitySummary.warnings > 0 || (report.comparison?.changed.length || 0) > 0
        ? 'watch'
        : 'ready';
  const sourceMatched = (report.comparison?.added.length || 0) === 0 && (report.comparison?.removed.length || 0) === 0;
  const changedQuestions = report.comparison?.changed.length || 0;
  const noteBase = report.comparison?.changed.length
    ? `${report.comparison.changed.length} changed questions compared with source; adapter passes.`
    : 'Counts match source and every question converts to QuestionItem.';

  return [
    {
      programId: 'vn_math_9',
      label: 'MiuMath Math 9',
      sourceQuestions: report.input.sourceQuestions ?? report.input.currentQuestions,
      importedQuestions: countItemsByProgram(items, 'vn_math_9'),
      readyQuestions: countItemsByProgram(items, 'vn_math_9'),
      blockerItems: report.qualitySummary.blockers,
      warningItems: report.qualitySummary.warnings,
      coverageStatus: baseStatus,
      adapterPass: report.adapter.pass,
      sourceMatched,
      changedQuestions,
      sourceFiles: localMath9Sources.totalFiles || undefined,
      sourceFormats: localMath9Sources.byExtension,
      sourcePath: report.input.sourcePath,
      currentPath: report.input.currentPath,
      note: `${noteBase} Local TOAN 9 folder has ${localMath9Sources.totalFiles} files for the next guarded import batch.`,
    },
    {
      programId: 'vn_math_vao_10',
      label: 'MiuMath On Vao 10',
      sourceQuestions: report.input.sourceQuestions ?? report.input.currentQuestions,
      importedQuestions: countItemsByProgram(items, 'vn_math_vao_10'),
      readyQuestions: countItemsByProgram(items, 'vn_math_vao_10'),
      blockerItems: report.qualitySummary.blockers,
      warningItems: report.qualitySummary.warnings,
      coverageStatus: baseStatus,
      adapterPass: report.adapter.pass,
      sourceMatched,
      changedQuestions,
      sourcePath: report.input.sourcePath,
      currentPath: report.input.currentPath,
      note: `${noteBase} The same item bank is tagged for entrance-exam review via vn_math_vao_10.`,
    },
  ];
}

function buildCombinedExam10ProgramRow(options: {
  miumathItems: QuestionItem[];
  miumathAdapterPass: boolean;
  miumathBlockers: number;
  miumathWarnings: number;
  math9Items: QuestionItem[];
  math9Report: ReturnType<typeof buildMath9ContentGuardReport>['report'];
  sourcePath: string;
  currentPath: string;
}): UnifiedContentCoverageSnapshot['programs'][number] {
  const miumathExam10Items = options.miumathItems.filter(isExam10OverlayItem);
  const math9Exam10Items = options.math9Items.filter(isExam10OverlayItem);
  const math9DisplayReadyIds = new Set(options.math9Report.displayReadyItemIds);
  const math9ReadyItems = math9Exam10Items.filter((item) => math9DisplayReadyIds.has(item.id));
  const miumathReadyQuestions = Math.max(0, miumathExam10Items.length - options.miumathBlockers);
  const importedQuestions = miumathReadyQuestions + math9ReadyItems.length;
  const readyQuestions = importedQuestions;
  const excludedQuestions = Math.max(0, miumathExam10Items.length - miumathReadyQuestions)
    + Math.max(0, math9Exam10Items.length - math9ReadyItems.length);
  const blockerItems = 0;
  const math9ReadyItemIds = new Set(math9ReadyItems.map((item) => item.id));
  const math9Warnings = options.math9Report.issues.filter((issue) =>
    issue.severity === 'warning' && (!issue.questionId || math9ReadyItemIds.has(issue.questionId)),
  ).length;
  const warningItems = options.miumathWarnings + math9Warnings;
  const adapterPass = options.miumathAdapterPass && options.math9Report.adapter.pass;
  const clusters = countExam10Clusters([...miumathExam10Items, ...math9ReadyItems]);
  const clusterCount = Object.keys(clusters).length;

  return {
    programId: 'vn_math_vao_10_combined',
    label: 'VN Math Vao 10 Combined',
    sourceQuestions: importedQuestions,
    importedQuestions,
    readyQuestions,
    blockerItems,
    warningItems,
    coverageStatus: !adapterPass || readyQuestions === 0 ? 'needs_repair' : blockerItems > 0 || warningItems > 0 ? 'watch' : 'ready',
    adapterPass,
    sourceMatched: true,
    changedQuestions: 0,
    sourceFiles: options.math9Report.input.sources + (miumathExam10Items.length ? 1 : 0),
    sourcePath: options.sourcePath,
    currentPath: options.currentPath,
    note: `Combines ${miumathExam10Items.length} legacy MiuMath questions with ${math9ReadyItems.length} display-ready local Math 9/on-vao-10 questions across ${clusterCount} exam10 clusters; ${excludedQuestions} display-blocked questions were excluded from the combined entrance-exam learner path.`,
  };
}

function isExam10OverlayItem(item: QuestionItem): boolean {
  return item.programIds.includes('vn_math_vao_10') && Boolean(getExam10Metadata(item));
}

function countExam10Clusters(items: QuestionItem[]): Record<string, number> {
  return items.reduce<Record<string, number>>((result, item) => {
    const clusterId = String(getExam10Metadata(item)?.clusterId || '');
    if (!clusterId) return result;
    result[clusterId] = (result[clusterId] || 0) + 1;
    return result;
  }, {});
}

function getExam10Metadata(item: QuestionItem): Record<string, unknown> | undefined {
  const value = item.metadata?.exam10;
  return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : undefined;
}

function buildPlannedMathProgramRow(programId: string, label: string, sourcePath: string, note: string): UnifiedContentCoverageSnapshot['programs'][number] {
  const scan = scanSourceFolder(sourcePath);
  return {
    programId,
    label,
    sourceQuestions: 0,
    importedQuestions: 0,
    readyQuestions: 0,
    blockerItems: 0,
    warningItems: 0,
    coverageStatus: 'planned',
    adapterPass: true,
    sourceMatched: scan.exists,
    changedQuestions: 0,
    sourceFiles: scan.totalFiles,
    sourceFormats: scan.byExtension,
    sourcePath,
    note,
  };
}

function buildEnglishProgramCoverageRows(report: EnglishContentGuardReport): UnifiedContentCoverageSnapshot['programs'] {
  return ['ielts', 'cpe', 'cae'].map((programId) => {
    const masteryReadyQuestions = Number(report.coverage.byProgram[programId] || 0);
    const feedbackOnlyItems = report.skillReadiness
      .filter((row) => row.skill === 'writing' || row.skill === 'speaking')
      .reduce((sum, row) => sum + Number(row.byProgram[programId] || 0), 0);
    const importedQuestions = report.skillReadiness.reduce((sum, row) => sum + Number(row.byProgram[programId] || 0), 0);
    const readyQuestions = masteryReadyQuestions;
    const blockerItems = Math.max(0, importedQuestions - masteryReadyQuestions - feedbackOnlyItems);
    const warnings = Number(report.qualitySummary.byProgram[programId] || 0);
    return {
      programId,
      label: programId === 'ielts' ? 'IELTS Layer' : programId.toUpperCase(),
      sourceQuestions: importedQuestions,
      importedQuestions,
      readyQuestions,
      blockerItems,
      warningItems: warnings,
      coverageStatus: blockerItems > 0 || !report.adapter.pass ? 'needs_repair' : warnings > 0 ? 'watch' : 'ready',
      feedbackOnlyItems,
      adapterPass: report.adapter.pass && blockerItems === 0,
      sourceMatched: true,
      changedQuestions: 0,
      note: `${masteryReadyQuestions} mastery-ready questions and ${feedbackOnlyItems} feedback-only Writing/Speaking samples in the shared English catalog.`,
    };
  });
}

interface SourceFolderScan {
  exists: boolean;
  totalFiles: number;
  byExtension: Record<string, number>;
}

function scanSourceFolder(folderPath: string): SourceFolderScan {
  if (!fs.existsSync(folderPath)) {
    return { exists: false, totalFiles: 0, byExtension: {} };
  }

  const byExtension: Record<string, number> = {};
  let totalFiles = 0;
  walkFiles(folderPath, (filePath) => {
    totalFiles += 1;
    const extension = path.extname(filePath).toLowerCase() || '(none)';
    byExtension[extension] = (byExtension[extension] || 0) + 1;
  });

  return { exists: true, totalFiles, byExtension };
}

function walkFiles(folderPath: string, visitor: (filePath: string) => void, depth = 0, state = { count: 0 }): void {
  if (depth > 8 || state.count >= 10000) return;
  fs.readdirSync(folderPath, { withFileTypes: true }).forEach((entry: { name: string; isDirectory(): boolean; isFile(): boolean; isSymbolicLink?(): boolean }) => {
    if (state.count >= 10000 || entry.isSymbolicLink?.()) return;
    const entryPath = path.join(folderPath, entry.name);
    if (entry.isDirectory()) {
      if (isSkippedSourceScanDir(entry.name)) return;
      walkFiles(entryPath, visitor, depth + 1, state);
      return;
    }
    if (entry.isFile()) {
      state.count += 1;
      visitor(entryPath);
    }
  });
}

function isSkippedSourceScanDir(name: string): boolean {
  return ['.git', '.svn', '.hg', 'node_modules', 'dist', 'build', '.next', '.vite'].includes(name.toLowerCase());
}

function countItemsByProgram(items: ReturnType<typeof toQuestionItemsFromMiuMath>, programId: string): number {
  return items.filter((item) => item.programIds.includes(programId)).length;
}

function readMath6RawSources(filePath: string): Math6RawSource[] {
  const parsed = readJson<unknown>(filePath);
  if (Array.isArray(parsed)) return parsed as Math6RawSource[];
  if (parsed && typeof parsed === 'object' && Array.isArray((parsed as { sources?: unknown }).sources)) {
    return (parsed as { sources: Math6RawSource[] }).sources;
  }
  throw new Error(`Expected Math 6 raw source array or { sources: [] } at ${filePath}`);
}

function readMath8RawSources(filePath: string): Math8RawSource[] {
  const parsed = readJson<unknown>(filePath);
  if (Array.isArray(parsed)) return parsed as Math8RawSource[];
  if (parsed && typeof parsed === 'object' && Array.isArray((parsed as { sources?: unknown }).sources)) {
    return (parsed as { sources: Math8RawSource[] }).sources;
  }
  throw new Error(`Expected Math 8 raw source array or { sources: [] } at ${filePath}`);
}

function readMath9RawSources(filePath: string): Math9RawSource[] {
  const parsed = readJson<unknown>(filePath);
  if (Array.isArray(parsed)) return parsed as Math9RawSource[];
  if (parsed && typeof parsed === 'object' && Array.isArray((parsed as { sources?: unknown }).sources)) {
    return (parsed as { sources: Math9RawSource[] }).sources;
  }
  throw new Error(`Expected Math 9 raw source array or { sources: [] } at ${filePath}`);
}

function readMath10RawSources(filePath: string): Math10RawSource[] {
  const parsed = readJson<unknown>(filePath);
  if (Array.isArray(parsed)) return parsed as Math10RawSource[];
  if (parsed && typeof parsed === 'object' && Array.isArray((parsed as { sources?: unknown }).sources)) {
    return (parsed as { sources: Math10RawSource[] }).sources;
  }
  return [];
}

function readMath11RawSources(filePath: string): Math11RawSource[] {
  const parsed = readJson<unknown>(filePath);
  if (Array.isArray(parsed)) return parsed as Math11RawSource[];
  if (parsed && typeof parsed === 'object' && Array.isArray((parsed as { sources?: unknown }).sources)) {
    return (parsed as { sources: Math11RawSource[] }).sources;
  }
  return [];
}

function readMath7RawSources(filePath: string): Math7RawSource[] {
  const parsed = readJson<unknown>(filePath);
  if (Array.isArray(parsed)) return parsed as Math7RawSource[];
  if (parsed && typeof parsed === 'object' && Array.isArray((parsed as { sources?: unknown }).sources)) {
    return (parsed as { sources: Math7RawSource[] }).sources;
  }
  throw new Error(`Expected Math 7 raw source array or { sources: [] } at ${filePath}`);
}

function dedupeMathRawSources<T extends { fileName: string; relativePath?: string }>(sources: T[]): T[] {
  const byKey = new Map<string, T>();
  sources.forEach((source) => {
    byKey.set(source.relativePath || source.fileName, source);
  });
  return [...byKey.values()];
}

function resolveDefaultMath6RawPath(workspaceRootPath: string): string {
  const richRawPath = path.resolve(workspaceRootPath, 'reports', 'content-quality', 'math6-rich-raw-extract.json');
  const plainRawPath = path.resolve(workspaceRootPath, 'reports', 'content-quality', 'math6-raw-extract.json');
  return shouldUseRichMath6RawPath(richRawPath, plainRawPath) ? richRawPath : plainRawPath;
}

function mathFormulaAssetExists(workspaceRootPath: string, src: string): boolean {
  if (!String(src || '').startsWith('/assets/')) return true;
  return fs.existsSync(path.resolve(workspaceRootPath, 'apps', 'miuprep-portal', 'public', String(src).replace(/^\/+/, '')));
}

function shouldUseRichMath6RawPath(richRawPath: string, plainRawPath: string): boolean {
  if (!fs.existsSync(richRawPath)) return false;
  try {
    const richSources = readMath6RawSources(richRawPath);
    const richSourcesWithText = richSources.filter((source) => String(source.text || '').trim().length > 0).length;
    if (!fs.existsSync(plainRawPath)) return richSourcesWithText > 0;
    const plainSources = readMath6RawSources(plainRawPath);
    return richSources.length >= plainSources.length && richSourcesWithText >= Math.ceil(plainSources.length * 0.9);
  } catch {
    return false;
  }
}

function countSourceFormats(rawSources: any[]): Record<string, number> {
  return rawSources.reduce<Record<string, number>>((result, source) => {
    const extension = String(source.extension || path.extname(source.fileName).replace(/^\./, '') || 'unknown').toLowerCase();
    result[extension] = (result[extension] || 0) + 1;
    return result;
  }, {});
}

function readJson<T>(filePath: string): T {
  return JSON.parse(fs.readFileSync(filePath, 'utf8')) as T;
}

function readJsonArray<T>(filePath: string): T[] {
  const parsed = readJson<unknown>(filePath);
  if (!Array.isArray(parsed)) throw new Error(`Expected JSON array at ${filePath}`);
  return parsed as T[];
}

function getArgValue(name: string): string {
  const index = process.argv.indexOf(name);
  if (index < 0) return '';
  const value = process.argv[index + 1] || '';
  return value ? path.resolve(process.cwd(), value) : '';
}

function findWorkspaceRoot(startDir: string): string {
  let current = path.resolve(startDir);
  while (current && current !== path.dirname(current)) {
    if (isWorkspaceRoot(current)) return current;
    current = path.dirname(current);
  }
  if (isWorkspaceRoot(current)) return current;
  throw new Error(`Cannot locate MIUPREP workspace root from ${startDir}`);
}

function isWorkspaceRoot(candidate: string): boolean {
  return (
    fs.existsSync(path.join(candidate, 'package.json')) &&
    fs.existsSync(path.join(candidate, 'apps', 'miuprep-portal', 'src')) &&
    fs.existsSync(path.join(candidate, 'packages', 'content', 'src'))
  );
}
