import { buildEnglishContentGuardReport, type EnglishContentGuardReport } from './english-content-guard-report';
import { buildMath6ContentGuardReport } from './math6-content-guard-report';
import type { Math6RawSource } from './math6-import';
import { buildMiuMathContentGuardReport } from './miumath-content-guard-report';
import { buildSatContentReadinessSnapshot, type SatPublicStudentPackage } from './sat-content';
import { toQuestionItemsFromMiuMath, type MiuMathQuestion } from './standard';

declare function require(name: string): any;
declare const process: { argv: string[]; cwd(): string; exitCode?: number };

const fs = require('node:fs');
const path = require('node:path');

const report = buildEnglishContentGuardReport();
const workspaceRoot = findWorkspaceRoot(process.cwd());
const targetPath = getArgValue('--target') || path.join(workspaceRoot, 'apps', 'miuprep-portal', 'src', 'data', 'contentQualitySnapshot.ts');
const coverageSnapshot = buildUnifiedCoverageSnapshot(workspaceRoot, report);

fs.mkdirSync(path.dirname(targetPath), { recursive: true });
fs.writeFileSync(targetPath, renderPortalSnapshot(report, coverageSnapshot));

console.log(`Synced English content quality snapshot to ${targetPath}`);
console.log(
  JSON.stringify(
    {
      readyQuestions: report.coverage.readyQuestions,
      blockedQuestions: report.coverage.blockedQuestions,
      adapterPass: report.adapter.pass,
      topIssues: report.qualitySummary.topIssues,
      coverage: coverageSnapshot.programs.map((program) => ({
        programId: program.programId,
        coverageStatus: program.coverageStatus,
        importedQuestions: program.importedQuestions,
        readyQuestions: program.readyQuestions,
        blockerItems: program.blockerItems,
        adapterPass: program.adapterPass,
      })),
    },
    null,
    2,
  ),
);

if (report.adapter.errors.length) {
  process.exitCode = 1;
}

interface UnifiedContentCoverageSnapshot {
  schemaVersion: 'miuprep_content_coverage_v1';
  generatedAt: string;
  programs: Array<{
    programId: string;
    label: string;
    sourceQuestions: number;
    importedQuestions: number;
    readyQuestions: number;
    blockerItems: number;
    warningItems: number;
    feedbackOnlyItems?: number;
    coverageStatus: 'ready' | 'watch' | 'planned' | 'needs_repair';
    adapterPass: boolean;
    sourceMatched?: boolean;
    changedQuestions?: number;
    sourceFiles?: number;
    sourceFormats?: Record<string, number>;
    sourcePath?: string;
    currentPath?: string;
    note: string;
  }>;
}

function renderPortalSnapshot(guardReport: EnglishContentGuardReport, coverageSnapshot: UnifiedContentCoverageSnapshot): string {
  const snapshot = {
    schemaVersion: guardReport.schemaVersion,
    generatedAt: guardReport.generatedAt,
    sourceCommand: 'npm.cmd run sync:portal-quality -w @miuprep/content',
    qualitySummary: {
      tests: guardReport.qualitySummary.tests,
      questions: guardReport.qualitySummary.questions,
      blockers: guardReport.qualitySummary.blockers,
      warnings: guardReport.qualitySummary.warnings,
      byProgram: guardReport.qualitySummary.byProgram,
      topIssues: guardReport.qualitySummary.topIssues,
    },
    coverage: {
      readyQuestions: guardReport.coverage.readyQuestions,
      blockedQuestions: guardReport.coverage.blockedQuestions,
      warningIssues: guardReport.coverage.warningIssues,
      byProgram: guardReport.coverage.byProgram,
      bySkill: guardReport.coverage.bySkill,
      byQuestionType: guardReport.coverage.byQuestionType,
      byConcept: guardReport.coverage.byConcept,
      bySourceTest: guardReport.coverage.bySourceTest,
    },
    skillReadiness: guardReport.skillReadiness,
    adapter: {
      readyItems: guardReport.adapter.readyItems,
      mockTests: guardReport.adapter.mockTests,
      passages: guardReport.adapter.passages,
      errorCount: guardReport.adapter.errors.length,
      pass: guardReport.adapter.pass,
    },
  };

  return `// Auto-generated by @miuprep/content. Run npm.cmd run sync:portal-quality -w @miuprep/content after content changes.
export interface ContentQualityIssueSnapshot {
  code: string;
  count: number;
}

export interface EnglishSkillReadinessSnapshot {
  skill: 'reading' | 'listening' | 'use_of_english' | 'writing' | 'speaking';
  label: string;
  totalItems: number;
  learningReadyItems: number;
  feedbackOnlyItems: number;
  blockerItems: number;
  warningItems: number;
  byProgram: Record<string, number>;
}

export interface EnglishContentQualitySnapshot {
  schemaVersion: 'english_content_guard_v1';
  generatedAt: string;
  sourceCommand: string;
  qualitySummary: {
    tests: number;
    questions: number;
    blockers: number;
    warnings: number;
    byProgram: Record<string, number>;
    topIssues: ContentQualityIssueSnapshot[];
  };
  coverage: {
    readyQuestions: number;
    blockedQuestions: number;
    warningIssues: number;
    byProgram: Record<string, number>;
    bySkill: Record<string, number>;
    byQuestionType: Record<string, number>;
    byConcept: Record<string, number>;
    bySourceTest: Record<string, number>;
  };
  skillReadiness: EnglishSkillReadinessSnapshot[];
  adapter: {
    readyItems: number;
    mockTests: number;
    passages: number;
    errorCount: number;
    pass: boolean;
  };
}

export interface ContentCoverageProgramSnapshot {
  programId: string;
  label: string;
  sourceQuestions: number;
  importedQuestions: number;
  readyQuestions: number;
  blockerItems: number;
  warningItems: number;
  feedbackOnlyItems?: number;
  adapterPass: boolean;
  coverageStatus: 'ready' | 'watch' | 'planned' | 'needs_repair';
  sourceMatched?: boolean;
  changedQuestions?: number;
  sourceFiles?: number;
  sourceFormats?: Record<string, number>;
  sourcePath?: string;
  currentPath?: string;
  note: string;
}

export interface UnifiedContentCoverageSnapshot {
  schemaVersion: 'miuprep_content_coverage_v1';
  generatedAt: string;
  programs: ContentCoverageProgramSnapshot[];
}

export const ENGLISH_CONTENT_QUALITY_SNAPSHOT: EnglishContentQualitySnapshot = ${JSON.stringify(snapshot, null, 2)};

export const CONTENT_COVERAGE_SNAPSHOT: UnifiedContentCoverageSnapshot = ${JSON.stringify(coverageSnapshot, null, 2)};
`;
}

function buildUnifiedCoverageSnapshot(workspaceRootPath: string, englishReport: EnglishContentGuardReport): UnifiedContentCoverageSnapshot {
  const generatedAt = englishReport.generatedAt;
  const programs: UnifiedContentCoverageSnapshot['programs'] = [];
  const localMathSourceRoot = path.resolve(workspaceRootPath, '..', '..', 'SACH VIET', 'TOAN');
  const math6RawPath = path.resolve(workspaceRootPath, 'reports', 'content-quality', 'math6-raw-extract.json');

  if (fs.existsSync(math6RawPath)) {
    const rawSources = readMath6RawSources(math6RawPath);
    const math6Report = buildMath6ContentGuardReport(rawSources, { rawPath: math6RawPath, generatedAt }).report;
    const blockedItems = Math.max(0, math6Report.stats.questions - math6Report.stats.displayReady);
    programs.push({
      programId: 'vn_math_6',
      label: 'VN Math 6 Local Sources',
      sourceQuestions: math6Report.stats.questions,
      importedQuestions: math6Report.adapter.convertedItems,
      readyQuestions: math6Report.stats.displayReady,
      blockerItems: blockedItems,
      warningItems: math6Report.qualitySummary.warnings,
      coverageStatus: !math6Report.adapter.pass || math6Report.stats.displayReady === 0 ? 'needs_repair' : blockedItems > 0 ? 'watch' : 'ready',
      adapterPass: math6Report.adapter.pass,
      sourceMatched: true,
      changedQuestions: 0,
      sourceFiles: math6Report.input.sources,
      sourceFormats: countSourceFormats(rawSources),
      sourcePath: path.resolve(localMathSourceRoot, 'TAI LIEU TOAN 6'),
      currentPath: math6RawPath,
      note: `${math6Report.stats.displayReady}/${math6Report.stats.questions} questions are display-ready; ${math6Report.stats.generatedFigures} geometry SVG figures generated; ${blockedItems} items remain behind formula/image/encoding gates.`,
    });
  } else {
    programs.push(buildPlannedMathProgramRow('vn_math_6', 'VN Math 6 Local Sources', path.resolve(localMathSourceRoot, 'TAI LIEU TOAN 6'), 'Raw extract is missing; run the Math 6 extractor before guard/import.'));
  }

  const miumathCurrentPath = path.resolve(workspaceRootPath, 'apps', 'miumath-app', 'public', 'data', 'questions_db.json');
  const miumathSourcePath = path.resolve(workspaceRootPath, '..', 'ON THi', 'miumath-app', 'public', 'data', 'questions_db.json');

  if (fs.existsSync(miumathCurrentPath)) {
    const currentQuestions = readJsonArray<MiuMathQuestion>(miumathCurrentPath);
    const sourceQuestions = fs.existsSync(miumathSourcePath) ? readJsonArray<MiuMathQuestion>(miumathSourcePath) : undefined;
    const miumathReport = buildMiuMathContentGuardReport(currentQuestions, {
      currentPath: miumathCurrentPath,
      sourcePath: sourceQuestions ? miumathSourcePath : undefined,
      sourceQuestions,
    });
    const miumathItems = toQuestionItemsFromMiuMath(currentQuestions);
    const localMath9Sources = scanSourceFolder(path.resolve(localMathSourceRoot, 'TOAN 9'));
    programs.push(...buildMiuMathProgramRows(miumathReport, miumathItems, localMath9Sources));
  }

  programs.push(buildPlannedMathProgramRow('vn_math_7', 'VN Math 7 Local Sources', path.resolve(localMathSourceRoot, 'toan 7'), 'Source folder is detected; build a Math 7 matrix/importer with the same Math guard before opening items.'));
  programs.push(buildPlannedMathProgramRow('vn_math_8', 'VN Math 8 Local Sources', path.resolve(localMathSourceRoot, 'toan 8'), 'Source folder is detected; build a Math 8 matrix/importer with the same Math guard before opening items.'));
  programs.push(buildPlannedMathProgramRow('vn_math_10_12', 'VN Math 10-12 Local Sources', path.resolve(localMathSourceRoot, 'toan 10'), 'Knowledge Graph is ready; source folder is detected and should use the same guarded import/display-ready flow.'));

  const satPackagePath = path.resolve(workspaceRootPath, 'apps', 'sat-studio', 'artifacts', 'sat-studio-public-content-package-latest.json');
  if (fs.existsSync(satPackagePath)) {
    const satPackage = readJson<SatPublicStudentPackage>(satPackagePath);
    const satReport = buildSatContentReadinessSnapshot(satPackage, generatedAt);
    programs.push({
      programId: 'sat',
      label: 'SAT Public Package',
      sourceQuestions: satReport.totalItems,
      importedQuestions: satReport.totalItems,
      readyQuestions: satReport.learningReadyItems,
      blockerItems: satReport.blockerItems,
      warningItems: satReport.warningItems,
      coverageStatus: satReport.blockerItems > 0 || !satReport.adapter.pass ? 'needs_repair' : satReport.warningItems > 0 ? 'watch' : 'ready',
      adapterPass: satReport.adapter.pass,
      sourceMatched: satReport.totalItems === satReport.uniqueIds && satReport.duplicateIds === 0,
      changedQuestions: 0,
      currentPath: satPackagePath,
      note: `${satReport.bySection.Math || 0} Math and ${satReport.bySection['Reading and Writing'] || 0} Reading/Writing items are ready.`,
    });
  }

  programs.push(...buildEnglishProgramCoverageRows(englishReport));

  return {
    schemaVersion: 'miuprep_content_coverage_v1',
    generatedAt,
    programs,
  };
}

function buildMiuMathProgramRows(
  report: ReturnType<typeof buildMiuMathContentGuardReport>,
  items: ReturnType<typeof toQuestionItemsFromMiuMath>,
  localMath9Sources: SourceFolderScan,
): UnifiedContentCoverageSnapshot['programs'] {
  const baseStatus: UnifiedContentCoverageSnapshot['programs'][number]['coverageStatus'] =
    report.qualitySummary.blockers > 0 || !report.adapter.pass
      ? 'needs_repair'
      : report.qualitySummary.warnings > 0 || (report.comparison?.changed.length || 0) > 0
        ? 'watch'
        : 'ready';
  const sourceMatched = (report.comparison?.added.length || 0) === 0 && (report.comparison?.removed.length || 0) === 0;
  const changedQuestions = report.comparison?.changed.length || 0;
  const noteBase = report.comparison?.changed.length
    ? `${report.comparison.changed.length} changed questions compared with source; adapter passes.`
    : 'Counts match source and every question converts to QuestionItem.';

  return [
    {
      programId: 'vn_math_9',
      label: 'MiuMath Math 9',
      sourceQuestions: report.input.sourceQuestions ?? report.input.currentQuestions,
      importedQuestions: countItemsByProgram(items, 'vn_math_9'),
      readyQuestions: countItemsByProgram(items, 'vn_math_9'),
      blockerItems: report.qualitySummary.blockers,
      warningItems: report.qualitySummary.warnings,
      coverageStatus: baseStatus,
      adapterPass: report.adapter.pass,
      sourceMatched,
      changedQuestions,
      sourceFiles: localMath9Sources.totalFiles || undefined,
      sourceFormats: localMath9Sources.byExtension,
      sourcePath: report.input.sourcePath,
      currentPath: report.input.currentPath,
      note: `${noteBase} Local TOAN 9 folder has ${localMath9Sources.totalFiles} files for the next guarded import batch.`,
    },
    {
      programId: 'vn_math_vao_10',
      label: 'MiuMath On Vao 10',
      sourceQuestions: report.input.sourceQuestions ?? report.input.currentQuestions,
      importedQuestions: countItemsByProgram(items, 'vn_math_vao_10'),
      readyQuestions: countItemsByProgram(items, 'vn_math_vao_10'),
      blockerItems: report.qualitySummary.blockers,
      warningItems: report.qualitySummary.warnings,
      coverageStatus: baseStatus,
      adapterPass: report.adapter.pass,
      sourceMatched,
      changedQuestions,
      sourcePath: report.input.sourcePath,
      currentPath: report.input.currentPath,
      note: `${noteBase} The same item bank is tagged for entrance-exam review via vn_math_vao_10.`,
    },
  ];
}

function buildPlannedMathProgramRow(programId: string, label: string, sourcePath: string, note: string): UnifiedContentCoverageSnapshot['programs'][number] {
  const scan = scanSourceFolder(sourcePath);
  return {
    programId,
    label,
    sourceQuestions: 0,
    importedQuestions: 0,
    readyQuestions: 0,
    blockerItems: 0,
    warningItems: 0,
    coverageStatus: 'planned',
    adapterPass: true,
    sourceMatched: scan.exists,
    changedQuestions: 0,
    sourceFiles: scan.totalFiles,
    sourceFormats: scan.byExtension,
    sourcePath,
    note,
  };
}

function buildEnglishProgramCoverageRows(report: EnglishContentGuardReport): UnifiedContentCoverageSnapshot['programs'] {
  return ['ielts', 'cpe', 'cae'].map((programId) => {
    const masteryReadyQuestions = Number(report.coverage.byProgram[programId] || 0);
    const feedbackOnlyItems = report.skillReadiness
      .filter((row) => row.skill === 'writing' || row.skill === 'speaking')
      .reduce((sum, row) => sum + Number(row.byProgram[programId] || 0), 0);
    const importedQuestions = report.skillReadiness.reduce((sum, row) => sum + Number(row.byProgram[programId] || 0), 0);
    const readyQuestions = masteryReadyQuestions;
    const blockerItems = Math.max(0, importedQuestions - masteryReadyQuestions - feedbackOnlyItems);
    const warnings = Number(report.qualitySummary.byProgram[programId] || 0);
    return {
      programId,
      label: programId === 'ielts' ? 'IELTS Layer' : programId.toUpperCase(),
      sourceQuestions: importedQuestions,
      importedQuestions,
      readyQuestions,
      blockerItems,
      warningItems: warnings,
      coverageStatus: blockerItems > 0 || !report.adapter.pass ? 'needs_repair' : warnings > 0 ? 'watch' : 'ready',
      feedbackOnlyItems,
      adapterPass: report.adapter.pass && blockerItems === 0,
      sourceMatched: true,
      changedQuestions: 0,
      note: `${masteryReadyQuestions} mastery-ready questions and ${feedbackOnlyItems} feedback-only Writing/Speaking samples in the shared English catalog.`,
    };
  });
}

interface SourceFolderScan {
  exists: boolean;
  totalFiles: number;
  byExtension: Record<string, number>;
}

function scanSourceFolder(folderPath: string): SourceFolderScan {
  if (!fs.existsSync(folderPath)) {
    return { exists: false, totalFiles: 0, byExtension: {} };
  }

  const byExtension: Record<string, number> = {};
  let totalFiles = 0;
  walkFiles(folderPath, (filePath) => {
    totalFiles += 1;
    const extension = path.extname(filePath).toLowerCase() || '(none)';
    byExtension[extension] = (byExtension[extension] || 0) + 1;
  });

  return { exists: true, totalFiles, byExtension };
}

function walkFiles(folderPath: string, visitor: (filePath: string) => void): void {
  fs.readdirSync(folderPath, { withFileTypes: true }).forEach((entry: { name: string; isDirectory(): boolean; isFile(): boolean }) => {
    const entryPath = path.join(folderPath, entry.name);
    if (entry.isDirectory()) {
      walkFiles(entryPath, visitor);
      return;
    }
    if (entry.isFile()) visitor(entryPath);
  });
}

function countItemsByProgram(items: ReturnType<typeof toQuestionItemsFromMiuMath>, programId: string): number {
  return items.filter((item) => item.programIds.includes(programId)).length;
}

function readMath6RawSources(filePath: string): Math6RawSource[] {
  const parsed = readJson<unknown>(filePath);
  if (Array.isArray(parsed)) return parsed as Math6RawSource[];
  if (parsed && typeof parsed === 'object' && Array.isArray((parsed as { sources?: unknown }).sources)) {
    return (parsed as { sources: Math6RawSource[] }).sources;
  }
  throw new Error(`Expected Math 6 raw source array or { sources: [] } at ${filePath}`);
}

function countSourceFormats(rawSources: Math6RawSource[]): Record<string, number> {
  return rawSources.reduce<Record<string, number>>((result, source) => {
    const extension = String(source.extension || path.extname(source.fileName).replace(/^\./, '') || 'unknown').toLowerCase();
    result[extension] = (result[extension] || 0) + 1;
    return result;
  }, {});
}

function readJson<T>(filePath: string): T {
  return JSON.parse(fs.readFileSync(filePath, 'utf8')) as T;
}

function readJsonArray<T>(filePath: string): T[] {
  const parsed = readJson<unknown>(filePath);
  if (!Array.isArray(parsed)) throw new Error(`Expected JSON array at ${filePath}`);
  return parsed as T[];
}

function getArgValue(name: string): string {
  const index = process.argv.indexOf(name);
  if (index < 0) return '';
  const value = process.argv[index + 1] || '';
  return value ? path.resolve(process.cwd(), value) : '';
}

function findWorkspaceRoot(startDir: string): string {
  let current = path.resolve(startDir);
  while (current && current !== path.dirname(current)) {
    if (isWorkspaceRoot(current)) return current;
    current = path.dirname(current);
  }
  if (isWorkspaceRoot(current)) return current;
  throw new Error(`Cannot locate MIUPREP workspace root from ${startDir}`);
}

function isWorkspaceRoot(candidate: string): boolean {
  return (
    fs.existsSync(path.join(candidate, 'package.json')) &&
    fs.existsSync(path.join(candidate, 'apps', 'miuprep-portal', 'src')) &&
    fs.existsSync(path.join(candidate, 'packages', 'content', 'src'))
  );
}
