import { buildEnglishContentGuardReport, type EnglishContentGuardReport } from './english-content-guard-report';
import { buildMiuMathContentGuardReport } from './miumath-content-guard-report';
import { buildSatContentReadinessSnapshot, type SatPublicStudentPackage } from './sat-content';
import type { MiuMathQuestion } from './standard';

declare function require(name: string): any;
declare const process: { argv: string[]; cwd(): string; exitCode?: number };

const fs = require('node:fs');
const path = require('node:path');

const report = buildEnglishContentGuardReport();
const workspaceRoot = findWorkspaceRoot(process.cwd());
const targetPath = getArgValue('--target') || path.join(workspaceRoot, 'apps', 'miuprep-portal', 'src', 'data', 'contentQualitySnapshot.ts');
const coverageSnapshot = buildUnifiedCoverageSnapshot(workspaceRoot, report);

fs.mkdirSync(path.dirname(targetPath), { recursive: true });
fs.writeFileSync(targetPath, renderPortalSnapshot(report, coverageSnapshot));

console.log(`Synced English content quality snapshot to ${targetPath}`);
console.log(
  JSON.stringify(
    {
      readyQuestions: report.coverage.readyQuestions,
      blockedQuestions: report.coverage.blockedQuestions,
      adapterPass: report.adapter.pass,
      topIssues: report.qualitySummary.topIssues,
      coverage: coverageSnapshot.programs.map((program) => ({
        programId: program.programId,
        coverageStatus: program.coverageStatus,
        importedQuestions: program.importedQuestions,
        readyQuestions: program.readyQuestions,
        blockerItems: program.blockerItems,
        adapterPass: program.adapterPass,
      })),
    },
    null,
    2,
  ),
);

if (report.adapter.errors.length) {
  process.exitCode = 1;
}

interface UnifiedContentCoverageSnapshot {
  schemaVersion: 'miuprep_content_coverage_v1';
  generatedAt: string;
  programs: Array<{
    programId: string;
    label: string;
    sourceQuestions: number;
    importedQuestions: number;
    readyQuestions: number;
    blockerItems: number;
    warningItems: number;
    feedbackOnlyItems?: number;
    coverageStatus: 'ready' | 'watch' | 'planned' | 'needs_repair';
    adapterPass: boolean;
    sourceMatched?: boolean;
    changedQuestions?: number;
    sourcePath?: string;
    currentPath?: string;
    note: string;
  }>;
}

function renderPortalSnapshot(guardReport: EnglishContentGuardReport, coverageSnapshot: UnifiedContentCoverageSnapshot): string {
  const snapshot = {
    schemaVersion: guardReport.schemaVersion,
    generatedAt: guardReport.generatedAt,
    sourceCommand: 'npm.cmd run sync:portal-quality -w @miuprep/content',
    qualitySummary: {
      tests: guardReport.qualitySummary.tests,
      questions: guardReport.qualitySummary.questions,
      blockers: guardReport.qualitySummary.blockers,
      warnings: guardReport.qualitySummary.warnings,
      byProgram: guardReport.qualitySummary.byProgram,
      topIssues: guardReport.qualitySummary.topIssues,
    },
    coverage: {
      readyQuestions: guardReport.coverage.readyQuestions,
      blockedQuestions: guardReport.coverage.blockedQuestions,
      warningIssues: guardReport.coverage.warningIssues,
      byProgram: guardReport.coverage.byProgram,
      bySkill: guardReport.coverage.bySkill,
      byQuestionType: guardReport.coverage.byQuestionType,
      byConcept: guardReport.coverage.byConcept,
      bySourceTest: guardReport.coverage.bySourceTest,
    },
    skillReadiness: guardReport.skillReadiness,
    adapter: {
      readyItems: guardReport.adapter.readyItems,
      mockTests: guardReport.adapter.mockTests,
      passages: guardReport.adapter.passages,
      errorCount: guardReport.adapter.errors.length,
      pass: guardReport.adapter.pass,
    },
  };

  return `// Auto-generated by @miuprep/content. Run npm.cmd run sync:portal-quality -w @miuprep/content after content changes.
export interface ContentQualityIssueSnapshot {
  code: string;
  count: number;
}

export interface EnglishSkillReadinessSnapshot {
  skill: 'reading' | 'listening' | 'use_of_english' | 'writing' | 'speaking';
  label: string;
  totalItems: number;
  learningReadyItems: number;
  feedbackOnlyItems: number;
  blockerItems: number;
  warningItems: number;
  byProgram: Record<string, number>;
}

export interface EnglishContentQualitySnapshot {
  schemaVersion: 'english_content_guard_v1';
  generatedAt: string;
  sourceCommand: string;
  qualitySummary: {
    tests: number;
    questions: number;
    blockers: number;
    warnings: number;
    byProgram: Record<string, number>;
    topIssues: ContentQualityIssueSnapshot[];
  };
  coverage: {
    readyQuestions: number;
    blockedQuestions: number;
    warningIssues: number;
    byProgram: Record<string, number>;
    bySkill: Record<string, number>;
    byQuestionType: Record<string, number>;
    byConcept: Record<string, number>;
    bySourceTest: Record<string, number>;
  };
  skillReadiness: EnglishSkillReadinessSnapshot[];
  adapter: {
    readyItems: number;
    mockTests: number;
    passages: number;
    errorCount: number;
    pass: boolean;
  };
}

export interface ContentCoverageProgramSnapshot {
  programId: string;
  label: string;
  sourceQuestions: number;
  importedQuestions: number;
  readyQuestions: number;
  blockerItems: number;
  warningItems: number;
  feedbackOnlyItems?: number;
  adapterPass: boolean;
  coverageStatus: 'ready' | 'watch' | 'planned' | 'needs_repair';
  sourceMatched?: boolean;
  changedQuestions?: number;
  sourcePath?: string;
  currentPath?: string;
  note: string;
}

export interface UnifiedContentCoverageSnapshot {
  schemaVersion: 'miuprep_content_coverage_v1';
  generatedAt: string;
  programs: ContentCoverageProgramSnapshot[];
}

export const ENGLISH_CONTENT_QUALITY_SNAPSHOT: EnglishContentQualitySnapshot = ${JSON.stringify(snapshot, null, 2)};

export const CONTENT_COVERAGE_SNAPSHOT: UnifiedContentCoverageSnapshot = ${JSON.stringify(coverageSnapshot, null, 2)};
`;
}

function buildUnifiedCoverageSnapshot(workspaceRootPath: string, englishReport: EnglishContentGuardReport): UnifiedContentCoverageSnapshot {
  const generatedAt = englishReport.generatedAt;
  const programs: UnifiedContentCoverageSnapshot['programs'] = [];
  const miumathCurrentPath = path.resolve(workspaceRootPath, 'apps', 'miumath-app', 'public', 'data', 'questions_db.json');
  const miumathSourcePath = path.resolve(workspaceRootPath, '..', 'ON THi', 'miumath-app', 'public', 'data', 'questions_db.json');

  if (fs.existsSync(miumathCurrentPath)) {
    const currentQuestions = readJsonArray<MiuMathQuestion>(miumathCurrentPath);
    const sourceQuestions = fs.existsSync(miumathSourcePath) ? readJsonArray<MiuMathQuestion>(miumathSourcePath) : undefined;
    const miumathReport = buildMiuMathContentGuardReport(currentQuestions, {
      currentPath: miumathCurrentPath,
      sourcePath: sourceQuestions ? miumathSourcePath : undefined,
      sourceQuestions,
    });
    programs.push({
      programId: 'vn_math_6_9',
      label: 'MiuMath Math 9',
      sourceQuestions: miumathReport.input.sourceQuestions ?? miumathReport.input.currentQuestions,
      importedQuestions: miumathReport.input.currentQuestions,
      readyQuestions: miumathReport.adapter.convertedItems,
      blockerItems: miumathReport.qualitySummary.blockers,
      warningItems: miumathReport.qualitySummary.warnings,
      coverageStatus:
        miumathReport.qualitySummary.blockers > 0 || !miumathReport.adapter.pass
          ? 'needs_repair'
          : miumathReport.qualitySummary.warnings > 0 || (miumathReport.comparison?.changed.length || 0) > 0
            ? 'watch'
            : 'ready',
      adapterPass: miumathReport.adapter.pass,
      sourceMatched: (miumathReport.comparison?.added.length || 0) === 0 && (miumathReport.comparison?.removed.length || 0) === 0,
      changedQuestions: miumathReport.comparison?.changed.length || 0,
      sourcePath: miumathReport.input.sourcePath,
      currentPath: miumathReport.input.currentPath,
      note: miumathReport.comparison?.changed.length
        ? `${miumathReport.comparison.changed.length} changed questions compared with source; counts match and adapter passes.`
        : 'Counts match source and every question converts to QuestionItem.',
    });
  }

  programs.push({
    programId: 'vn_math_10_12',
    label: 'VN Math 10-12',
    sourceQuestions: 0,
    importedQuestions: 0,
    readyQuestions: 0,
    blockerItems: 0,
    warningItems: 0,
    coverageStatus: 'planned',
    adapterPass: true,
    sourceMatched: false,
    changedQuestions: 0,
    note: 'Knowledge Graph, objectives, skills, and remediation map are ready; question bank has not been imported yet.',
  });

  const satPackagePath = path.resolve(workspaceRootPath, 'apps', 'sat-studio', 'artifacts', 'sat-studio-public-content-package-latest.json');
  if (fs.existsSync(satPackagePath)) {
    const satPackage = readJson<SatPublicStudentPackage>(satPackagePath);
    const satReport = buildSatContentReadinessSnapshot(satPackage, generatedAt);
    programs.push({
      programId: 'sat',
      label: 'SAT Public Package',
      sourceQuestions: satReport.totalItems,
      importedQuestions: satReport.totalItems,
      readyQuestions: satReport.learningReadyItems,
      blockerItems: satReport.blockerItems,
      warningItems: satReport.warningItems,
      coverageStatus: satReport.blockerItems > 0 || !satReport.adapter.pass ? 'needs_repair' : satReport.warningItems > 0 ? 'watch' : 'ready',
      adapterPass: satReport.adapter.pass,
      sourceMatched: satReport.totalItems === satReport.uniqueIds && satReport.duplicateIds === 0,
      changedQuestions: 0,
      currentPath: satPackagePath,
      note: `${satReport.bySection.Math || 0} Math and ${satReport.bySection['Reading and Writing'] || 0} Reading/Writing items are ready.`,
    });
  }

  programs.push(...buildEnglishProgramCoverageRows(englishReport));

  return {
    schemaVersion: 'miuprep_content_coverage_v1',
    generatedAt,
    programs,
  };
}

function buildEnglishProgramCoverageRows(report: EnglishContentGuardReport): UnifiedContentCoverageSnapshot['programs'] {
  return ['ielts', 'cpe', 'cae'].map((programId) => {
    const masteryReadyQuestions = Number(report.coverage.byProgram[programId] || 0);
    const feedbackOnlyItems = report.skillReadiness
      .filter((row) => row.skill === 'writing' || row.skill === 'speaking')
      .reduce((sum, row) => sum + Number(row.byProgram[programId] || 0), 0);
    const importedQuestions = report.skillReadiness.reduce((sum, row) => sum + Number(row.byProgram[programId] || 0), 0);
    const readyQuestions = masteryReadyQuestions + feedbackOnlyItems;
    const blockerItems = Math.max(0, importedQuestions - readyQuestions);
    const warnings = Number(report.qualitySummary.byProgram[programId] || 0);
    return {
      programId,
      label: programId === 'ielts' ? 'IELTS Layer' : programId.toUpperCase(),
      sourceQuestions: importedQuestions,
      importedQuestions,
      readyQuestions,
      blockerItems,
      warningItems: warnings,
      coverageStatus: blockerItems > 0 || !report.adapter.pass ? 'needs_repair' : warnings > 0 ? 'watch' : 'ready',
      feedbackOnlyItems,
      adapterPass: report.adapter.pass && blockerItems === 0,
      sourceMatched: true,
      changedQuestions: 0,
      note: `${masteryReadyQuestions} mastery-ready questions and ${feedbackOnlyItems} feedback-only Writing/Speaking samples in the shared English catalog.`,
    };
  });
}

function readJson<T>(filePath: string): T {
  return JSON.parse(fs.readFileSync(filePath, 'utf8')) as T;
}

function readJsonArray<T>(filePath: string): T[] {
  const parsed = readJson<unknown>(filePath);
  if (!Array.isArray(parsed)) throw new Error(`Expected JSON array at ${filePath}`);
  return parsed as T[];
}

function getArgValue(name: string): string {
  const index = process.argv.indexOf(name);
  if (index < 0) return '';
  const value = process.argv[index + 1] || '';
  return value ? path.resolve(process.cwd(), value) : '';
}

function findWorkspaceRoot(startDir: string): string {
  let current = path.resolve(startDir);
  while (current && current !== path.dirname(current)) {
    if (isWorkspaceRoot(current)) return current;
    current = path.dirname(current);
  }
  if (isWorkspaceRoot(current)) return current;
  throw new Error(`Cannot locate MIUPREP workspace root from ${startDir}`);
}

function isWorkspaceRoot(candidate: string): boolean {
  return (
    fs.existsSync(path.join(candidate, 'package.json')) &&
    fs.existsSync(path.join(candidate, 'apps', 'miuprep-portal', 'src')) &&
    fs.existsSync(path.join(candidate, 'packages', 'content', 'src'))
  );
}
