"""
Generate all 6 missing batches: A3, A5, A6, A8, A10, B10
Total: 300 questions (6 × 50)
"""
import json, uuid, os, random

DATA_DIR = r"c:\Users\HAIQUYNH\OneDrive\CODE AI\SAT\data"
random.seed(42)

def uid():
    return f"antigravity-hard-{uuid.uuid4().hex[:8]}"

def mcq(domain, skill, signal, prompt, choices_list, correct, expl_correct, distractors_dict, cog, traps):
    letters = ["A","B","C","D"]
    return {
        "id": uid(), "section": "Math", "domain": domain, "skill": skill,
        "difficulty": "Hard", "targetBand": "SAT-1600",
        "prompt": prompt, "type": "MCQ",
        "choices": [{"letter": letters[i], "text": choices_list[i]} for i in range(4)],
        "correctAnswer": correct,
        "explanation": {"correct": expl_correct, "distractors": distractors_dict},
        "metadata": {"cognitiveMove": cog, "trapTypes": traps, "sourceSignalId": signal}
    }

def spr(domain, skill, signal, prompt, answer, acceptable, expl, cog, traps):
    return {
        "id": uid(), "section": "Math", "domain": domain, "skill": skill,
        "difficulty": "Hard", "targetBand": "SAT-1600",
        "prompt": prompt, "type": "SPR",
        "correctAnswer": str(answer), "acceptableAnswers": acceptable,
        "explanation": {"correct": expl},
        "metadata": {"cognitiveMove": cog, "trapTypes": traps, "sourceSignalId": signal}
    }

def save_batch(name, questions):
    path = os.path.join(DATA_DIR, f"batch_{name}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(questions, f, indent=2, ensure_ascii=False)
    mc = sum(1 for q in questions if q["type"] == "MCQ")
    sp = sum(1 for q in questions if q["type"] == "SPR")
    print(f"  batch_{name}.json: {len(questions)} questions (MCQ={mc}, SPR={sp})")

# ============================================================
# BATCH A3: Linear equations in one variable — parametric, verbal, literal
# ============================================================
def gen_A3():
    D, S, SIG = "Algebra", "Linear equations in one variable", "antigravity-hard-algebra-lineq1-param"
    qs = []
    # MCQ block (38 questions)
    mcq_data = [
        ("For what value of k does the equation 3(2x - 5) + k = 6x - 10 have infinitely many solutions?",
         ["5", "-5", "0", "No value of k makes it an identity"], "A",
         "Expand: 6x - 15 + k = 6x - 10. For identity: -15 + k = -10, so k = 5.",
         {"B": "Sign Error: solved -15 + k = -10 incorrectly as k = -5", "C": "Assumed k = 0 without solving", "D": "Confused identity with contradiction"},
         "Recognizing identity conditions in parametric equations", ["Parameter Confusion", "Sign Error"]),
        ("A phone plan charges a monthly fee of m dollars plus $0.05 per text. A customer sends 200 texts and pays $25 total. What is m?",
         ["$15", "$10", "$20", "$35"], "A",
         "m + 0.05(200) = 25 → m + 10 = 25 → m = 15.",
         {"B": "Divided 200 by 20 instead of multiplying by 0.05", "C": "Subtracted wrong: 25 - 5 = 20", "D": "Added: 25 + 10 = 35"},
         "Translating verbal context into a linear equation", ["Arithmetic Error", "Wrong Operation"]),
        ("Solve for r in the formula A = P(1 + rt).",
         ["r = (A - P)/(Pt)", "r = (A - P)/t", "r = A/(Pt) - 1", "r = (A + P)/(Pt)"], "A",
         "A - P = Prt → r = (A - P)/(Pt).",
         {"B": "Forgot to divide by P", "C": "Divided A by Pt first, then subtracted 1 — order error", "D": "Added P instead of subtracting"},
         "Isolating a variable in a multi-variable literal equation", ["Distribution Error", "Order of Operations"]),
        ("If 5(x - 3) - 2(x + 4) = 3x + k has no solution for any x, which values of k work?",
         ["Any k ≠ -23", "k = -23", "k = 23", "No values of k"], "A",
         "Expand: 3x - 23 = 3x + k. The x-terms cancel. For no solution: -23 ≠ k, so any k except -23.",
         {"B": "k = -23 gives identity (infinitely many), not no solution", "C": "Sign error on constant", "D": "Thought equation always has a solution"},
         "Understanding contradiction vs identity conditions", ["Identity vs Contradiction", "Sign Error"]),
        ("Solve: (3x + 2)/4 - (x - 1)/3 = 13/12",
         ["x = 3/5", "x = 1", "x = 5/3", "x = 7/12"], "A",
         "LCD = 12: 3(3x + 2) - 4(x - 1) = 13 → 9x + 6 - 4x + 4 = 13 → 5x + 10 = 13 → 5x = 3 → x = 3/5.",
         {"B": "Forgot to distribute negative: -(x-1) became -x-1", "C": "Inverted fraction: wrote 5/3 instead of 3/5", "D": "Used wrong LCD"},
         "Multi-step fraction equation with LCD", ["LCD Error", "Distribution Error"]),
        ("If 4(2x - a) = 3(x + a) + 5x - 7a, which statement is true?",
         ["Identity for all values of a", "No solution for any a", "Exactly one solution when a = 0", "Depends on the value of a"], "A",
         "Left: 8x - 4a. Right: 3x + 3a + 5x - 7a = 8x - 4a. Both sides identical.",
         {"B": "Assumed x-terms cancel to a contradiction", "C": "Restricted to a = 0 unnecessarily", "D": "Did not simplify both sides fully"},
         "Recognizing structural identity independent of parameter", ["Identity Recognition", "Incomplete Simplification"]),
        ("A pool fills at 3 gal/min with 47 gal. Another drains at 2 gal/min with 142 gal. When are they equal?",
         ["19 min", "95 min", "17 min", "21 min"], "A",
         "47 + 3t = 142 - 2t → 5t = 95 → t = 19.",
         {"B": "Used only one rate: 95/1 = 95", "C": "Subtracted rates: t(3-2) = 142-47 but then 95/1", "D": "Added a rounding error"},
         "Setting up equations from two competing linear processes", ["Setup Error", "Rate Confusion"]),
        ("For what value of c does 2(3x + c) - 6x = 4c + 2 have no solution?",
         ["Any c ≠ -1", "c = -1", "c = 0", "c = 1"], "A",
         "Simplify: 2c = 4c + 2 → -2c = 2 → c = -1 gives identity. For c ≠ -1: contradiction (no solution in x).",
         {"B": "c = -1 gives identity, not no solution", "C": "Plugged in c = 0 without analysis", "D": "Tested c = 1 only"},
         "Analyzing parametric equations for contradiction conditions", ["Parameter Analysis", "Identity vs Contradiction"]),
        ("A rectangle has perimeter 56 cm. Length is 4 cm more than twice the width. Find the width.",
         ["8 cm", "20 cm", "16 cm", "12 cm"], "A",
         "l = 2w + 4. 2(w + 2w + 4) = 56 → 6w + 8 = 56 → w = 8.",
         {"B": "Found length: l = 2(8)+4 = 20", "C": "Used l = 2w without the +4", "D": "Used perimeter = l + w instead of 2(l+w)"},
         "Translating geometric relationships into linear equations", ["Solved Wrong Variable", "Perimeter Formula"]),
        ("Solve: 0.3(x - 4) + 0.7x = 0.1(10x - 12)",
         ["All real numbers (identity)", "x = 0", "x = 1.2", "No solution"], "A",
         "0.3x - 1.2 + 0.7x = x - 1.2 → x - 1.2 = x - 1.2. Identity.",
         {"B": "Confused x = 0 with 'all reals'", "C": "Decimal multiplication error", "D": "Thought terms cancel to contradiction"},
         "Recognizing identity in decimal-coefficient equations", ["Identity vs No Solution", "Decimal Error"]),
        ("If 7x - 3(2x + 5) = x - 12, what is x?",
         ["No solution (contradiction)", "x = 0", "x = -3", "x = 3"], "A",
         "7x - 6x - 15 = x - 12 → x - 15 = x - 12 → -15 ≠ -12. Contradiction.",
         {"B": "Set x = 0 and checked one side only", "C": "Arithmetic error: -15 + 12 = -3 → x = -3", "D": "Sign flip error"},
         "Identifying contradictions after distribution", ["Contradiction Recognition", "Distribution Error"]),
        ("Solve for C: F = (9/5)C + 32",
         ["C = (5/9)(F - 32)", "C = (9/5)(F - 32)", "C = 5F/9 - 32", "C = (5F - 32)/9"], "A",
         "F - 32 = (9/5)C → C = (5/9)(F - 32).",
         {"B": "Kept 9/5 instead of reciprocal", "C": "Distributed 5/9 to F but not to -32", "D": "Divided each term separately, incorrect grouping"},
         "Isolating variable with fraction coefficient", ["Reciprocal Error", "Distribution Error"]),
        ("Maria buys notebooks at $3 and pens at $1.50. She buys twice as many pens as notebooks and spends $24. How many notebooks?",
         ["4", "8", "6", "3"], "A",
         "3n + 1.5(2n) = 24 → 6n = 24 → n = 4.",
         {"B": "Found pens: 2(4) = 8", "C": "Used pens = notebooks instead of 2×", "D": "Divided 24 by (3+1.5+1.5) = 6 wrong way"},
         "Setting up substitution equation from context", ["Solved Wrong Variable", "Setup Error"]),
        ("If (k+2)x + 5 = kx + 2x + 5 for ALL x, how many values of k work?",
         ["All real numbers", "Exactly one: k = 0", "None", "Exactly two"], "A",
         "Right side = (k+2)x + 5 = left side. Identity for all k.",
         {"B": "Thought only k=0 works", "C": "Thought no k works", "D": "Assumed quadratic in k"},
         "Recognizing structural identity independent of parameter", ["Overthinking", "Parameter Confusion"]),
        ("Solve: |3x - 6| = 12",
         ["x = 6 or x = -2", "x = 6 only", "x = -6 or x = 2", "x = 6 or x = 2"], "A",
         "Case 1: 3x - 6 = 12 → x = 6. Case 2: 3x - 6 = -12 → x = -2.",
         {"B": "Only solved positive case", "C": "Sign errors in both cases", "D": "Added 6 instead of subtracting in Case 2"},
         "Solving absolute value equations with two cases", ["Missing Second Case", "Sign Error"]),
        ("Car rental A: $45/day + $0.20/mi. Car rental B: $30/day + $0.35/mi. At how many miles is cost equal (1-day)?",
         ["100 miles", "75 miles", "150 miles", "50 miles"], "A",
         "45 + 0.20m = 30 + 0.35m → 15 = 0.15m → m = 100.",
         {"B": "Used 45/0.60 = 75", "C": "Added rates: 0.55m = total confusion", "D": "Used 15/0.30 = 50"},
         "Finding break-even from two linear cost models", ["Setup Error", "Rate Error"]),
        ("Solve: 5y - 3(y - 2) + 4 = 2(y + 5)",
         ["All real numbers (identity)", "y = 0", "y = 5", "No solution"], "A",
         "5y - 3y + 6 + 4 = 2y + 10 → 2y + 10 = 2y + 10. Identity.",
         {"B": "Set y = 0", "C": "Stopped at 2y + 2 on left (arithmetic error)", "D": "Thought terms cancel to contradiction"},
         "Distribution and simplification to identify identity", ["Identity Recognition", "Distribution Error"]),
        ("Solve: 2/(x - 1) = 6. What is x?",
         ["4/3", "7/3", "1/3", "5/3"], "A",
         "2 = 6(x - 1) → 2 = 6x - 6 → 8 = 6x → x = 4/3.",
         {"B": "Added 1 to 2/6 = 1/3 → 4/3 + 1 = 7/3", "C": "Divided: 2/6 = 1/3", "D": "Used 5/3 from mental math error"},
         "Solving rational equation by clearing denominator", ["Cross Multiplication Error", "Simplification Error"]),
        ("A number decreased by 40% of itself equals 27. What is the number?",
         ["45", "67.5", "38", "18"], "A",
         "x - 0.4x = 27 → 0.6x = 27 → x = 45.",
         {"B": "Divided 27 by 0.4 instead of 0.6", "C": "Added 40% of 27 to 27: 27 + 10.8 = 37.8 ≈ 38", "D": "Took 40% of 45 = 18 (confused result with input)"},
         "Translating percent decrease into linear equation", ["Percent Complement Error", "Wrong Operation"]),
        ("Solve: 3(x + 2) - 2(3x - 1) = -(3x - 8)",
         ["All real numbers (identity)", "x = 0", "x = 8", "No solution"], "A",
         "3x + 6 - 6x + 2 = -3x + 8 → -3x + 8 = -3x + 8. Identity.",
         {"B": "Set x = 0 and concluded unique", "C": "Stopped at constant 8", "D": "Negated wrong: -(3x-8) = -3x - 8"},
         "Multi-term distribution to recognize identity", ["Identity Recognition", "Sign Error"]),
        ("Sum of 3 consecutive odd integers is 63. What is the largest?",
         ["23", "21", "19", "25"], "A",
         "x + (x+2) + (x+4) = 63 → 3x + 6 = 63 → x = 19. Largest = 23.",
         {"B": "Gave middle number: 21", "C": "Gave smallest: 19", "D": "Added 6 to 19 instead of 4"},
         "Setting up consecutive integer equations", ["Solved Wrong Part", "Arithmetic Error"]),
        ("If 5x + 3 = 5x + k, for what value of k does the equation have exactly one solution?",
         ["No such value exists", "k = 3", "k = 0", "k = -3"], "A",
         "5x cancels: 3 = k. If k = 3: identity. If k ≠ 3: contradiction. Neither gives exactly one solution.",
         {"B": "k = 3 gives identity, not one solution", "C": "Set k = 0 to 'eliminate constant'", "D": "Tried negative"},
         "Understanding parallel-line analogy for solution counts", ["Solution Count Error", "Identity vs Contradiction"]),
        ("A taxi charges $3 base plus $1.50/mile. If total is $15, how many miles?",
         ["8", "10", "5", "12"], "A",
         "3 + 1.5m = 15 → 1.5m = 12 → m = 8.",
         {"B": "Forgot base: 15/1.5 = 10", "C": "Used 15/3 = 5", "D": "Added base to result: 8 + 3 = 11... no, 12 from 15-3=12 confused as answer"},
         "Solving linear equation from word problem", ["Forgot Base Fare", "Arithmetic Error"]),
        ("Solve: (x + 1)/2 + (x - 1)/3 = 5",
         ["29/5", "5", "3", "11/5"], "A",
         "LCD = 6: 3(x+1) + 2(x-1) = 30 → 5x + 1 = 30 → x = 29/5.",
         {"B": "Forgot LCD: added numerators directly", "C": "Used LCD = 5", "D": "Subtracted instead of adding"},
         "Fraction equation requiring LCD", ["LCD Error", "Distribution Error"]),
        ("If mx + 5 = 3x + 5 has infinitely many solutions, what is m?",
         ["3", "0", "5", "Any value"], "A",
         "For identity: mx = 3x for all x → m = 3.",
         {"B": "Set m = 0 to 'remove' x-term", "C": "Confused m with constant 5", "D": "Thought any m works"},
         "Matching coefficients for identity condition", ["Parameter Identification", "Coefficient Error"]),
        ("Solve: 0.25x - 0.1(x + 10) = 0.5",
         ["10", "-10", "4", "6.67"], "A",
         "0.25x - 0.1x - 1 = 0.5 → 0.15x = 1.5 → x = 10.",
         {"B": "Sign error: got -10", "C": "Forgot to distribute -0.1 to 10", "D": "Decimal arithmetic error: 1.5/0.25"},
         "Solving equations with decimal coefficients", ["Decimal Distribution Error", "Sign Error"]),
        ("Rectangle: length is 3 more than width. Perimeter = 46. Find the length.",
         ["13", "10", "23", "16"], "A",
         "Half-perimeter = 23. w + (w+3) = 23 → 2w = 20 → w = 10, l = 13.",
         {"B": "Gave width instead", "C": "Used perimeter = l + w", "D": "Added 3 to wrong value"},
         "Geometry word problem", ["Solved Wrong Variable", "Perimeter Error"]),
        ("For what value of a does 2(ax - 3) = 6x - 6 have infinitely many solutions?",
         ["3", "6", "-3", "1"], "A",
         "2ax - 6 = 6x - 6. For identity: 2a = 6 → a = 3. Constants: -6 = -6 ✓.",
         {"B": "Forgot to divide by 2: a = 6", "C": "Used negative: -6/2 = -3", "D": "Set a = 1 without calculation"},
         "Coefficient matching for identity", ["Coefficient Matching", "Division Error"]),
        ("Solve: 5 - 2(3 - x) = 2x - 1",
         ["All real numbers (identity)", "x = 0", "x = 2", "No solution"], "A",
         "5 - 6 + 2x = 2x - 1 → -1 + 2x = 2x - 1. Identity.",
         {"B": "Substituted x = 0 only", "C": "Computed 5 - 6 = 1 instead of -1", "D": "Thought contradiction"},
         "Nested distribution to identify identity", ["Identity Recognition", "Arithmetic Error"]),
        ("Worker earns $18/hr regular, $27/hr overtime. Total $594 with 4 overtime hours. Regular hours?",
         ["27", "33", "30", "25"], "A",
         "18h + 27(4) = 594 → 18h + 108 = 594 → 18h = 486 → h = 27.",
         {"B": "Forgot overtime: 594/18 = 33", "C": "Used blended rate", "D": "Subtracted overtime incorrectly"},
         "Two-rate earning equation", ["Ignored Second Term", "Rate Confusion"]),
        ("Solve for b: V = (1/3)πr²b",
         ["b = 3V/(πr²)", "b = V/(3πr²)", "b = 3Vπr²", "b = Vπr²/3"], "A",
         "3V = πr²b → b = 3V/(πr²).",
         {"B": "Forgot to multiply by 3", "C": "Multiplied instead of dividing", "D": "Misarranged terms"},
         "Isolating variable in geometry formula", ["Inverse Operation", "Formula Manipulation"]),
        ("If 8 - 3(2x + 1) = 5 - 6x, what can be concluded?",
         ["Infinitely many solutions", "x = 0", "x = 1", "No solution"], "A",
         "8 - 6x - 3 = 5 - 6x → 5 - 6x = 5 - 6x. Identity.",
         {"B": "Substituted x = 0 only", "C": "Computed 8 - 3 = 4", "D": "Thought x cancels = no solution"},
         "Distribution and simplification", ["Identity vs No Solution", "Distribution Error"]),
        ("Boat rental: $200 + $50/hr. Jet ski: $80 + $80/hr. When equal?",
         ["4 hours", "3 hours", "5 hours", "6 hours"], "A",
         "200 + 50h = 80 + 80h → 120 = 30h → h = 4.",
         {"B": "Subtraction error: 120/40 = 3", "C": "Used 200/40 = 5", "D": "Added: (200+80)/(50+80)"},
         "Break-even point calculation", ["Setup Error", "Arithmetic Error"]),
        ("Solve: 4(x - 3) + 7 = 2(2x + 1) - 3",
         ["No solution", "x = 0", "x = -6", "All real numbers"], "A",
         "4x - 12 + 7 = 4x + 2 - 3 → 4x - 5 = 4x - 1 → -5 ≠ -1. Contradiction.",
         {"B": "Set x = 0 and said 'close enough'", "C": "Combined -12 + 7 as -6", "D": "Thought 4x = 4x means identity"},
         "Recognizing contradiction", ["Contradiction Recognition", "Arithmetic Error"]),
        ("Solve: 2x/3 - x/6 = 5",
         ["10", "30", "6", "15"], "A",
         "LCD = 6: 4x - x = 30 → 3x = 30 → x = 10.",
         {"B": "Forgot to multiply RHS: 3x = 5", "C": "LCD error: used 3", "D": "Divided 30 by 2"},
         "Combining fractions with different denominators", ["LCD Error", "Arithmetic Error"]),
        ("In kx + 6 = 4x + 2k, for what value of k does the equation have no solution?",
         ["4", "3", "0", "-4"], "A",
         "(k-4)x = 2k - 6. For no solution: k-4 = 0 AND 2k-6 ≠ 0. k = 4: 2(4)-6 = 2 ≠ 0. ✓",
         {"B": "Set 2k-6 = 0 → k = 3, but that gives unique solution", "C": "Set k = 0 blindly", "D": "Negated: -4"},
         "Parameter analysis for no-solution condition", ["Parameter Analysis", "Contradiction Condition"]),
        ("If a/3 + a/4 = 7, what is a?",
         ["12", "7", "21", "84/7"], "A",
         "LCD = 12: 4a + 3a = 84 → 7a = 84 → a = 12.",
         {"B": "Assumed a = 7 from RHS", "C": "Multiplied: 3 × 7 = 21", "D": "Left as fraction"},
         "Adding fractions with LCD", ["LCD Error", "Arithmetic Error"]),
        ("The average of x, x+4, and x+8 is 20. What is x?",
         ["16", "20", "12", "24"], "A",
         "(3x + 12)/3 = 20 → 3x + 12 = 60 → x = 16.",
         {"B": "Used average as answer", "C": "Subtracted 8: 20-8 = 12", "D": "Added 4: 20+4 = 24"},
         "Average equation setup", ["Arithmetic Error", "Conceptual Error"]),
    ]
    for d in mcq_data:
        qs.append(mcq(D, S, SIG, d[0], d[1], d[2], d[3], d[4], d[5], d[6]))

    # SPR block (12 questions)
    spr_data = [
        ("If 5(x - 2) + 3 = 2x + k and x = 4, what is k?", "5", ["5"], "5(2)+3=13, 2(4)+k=8+k=13 → k=5.", "Substituting to find parameter", ["Arithmetic Error"]),
        ("Solve: 3x + 7 = 2(x + 5) - 3", "0", ["0"], "3x+7=2x+7 → x=0.", "Two-step equation", ["Distribution Error"]),
        ("A number increased by 25% equals 80. What is the number?", "64", ["64"], "1.25x=80 → x=64.", "Percent increase equation", ["Percent Direction Error"]),
        ("Solve: (x-3)/4 = (x+1)/6", "11", ["11"], "LCD=12: 3(x-3)=2(x+1) → 3x-9=2x+2 → x=11.", "Cross multiplication", ["LCD Error"]),
        ("If 2x - 7 = 3(x - 4), what is x?", "5", ["5"], "2x-7=3x-12 → -x=-5 → x=5.", "Distribution and collection", ["Sign Error"]),
        ("|2x - 10| = 6. What is the sum of all solutions?", "10", ["10"], "x=8 or x=2. Sum=10.", "Absolute value sum", ["Missing Second Case"]),
        ("A number is tripled, then 7 is subtracted. Result is 29. What is the number?", "12", ["12"], "3x-7=29 → x=12.", "Verbal translation", ["Order of Operations"]),
        ("Solve: 0.5(x + 6) = 0.2x + 4.5", "5", ["5"], "0.5x+3=0.2x+4.5 → 0.3x=1.5 → x=5.", "Decimal equation", ["Decimal Error"]),
        ("In d = rt, if d = 240 and r = 60, find t.", "4", ["4"], "t = 240/60 = 4.", "Formula application", ["Formula Error"]),
        ("Solve: 4(2x + 3) = 5(x + 3) - 3", "0", ["0"], "8x+12=5x+12 → 3x=0 → x=0.", "Multi-step distribution", ["Distribution Error"]),
        ("If x/3 + x/4 = 7, what is x?", "12", ["12"], "LCD=12: 4x+3x=84 → 7x=84 → x=12.", "Fraction addition", ["LCD Error"]),
        ("The average of x, 2x, and 3x is 30. What is x?", "15", ["15"], "(6x)/3=30 → 2x=30 → x=15.", "Average equation", ["Arithmetic Error"]),
    ]
    for d in spr_data:
        qs.append(spr(D, S, SIG, d[0], d[1], d[2], d[3], d[4], d[5]))
    return qs

# ============================================================
# BATCH A5: Linear inequalities — context-rich
# ============================================================
def gen_A5():
    D, S, SIG = "Algebra", "Linear inequalities in one or two variables", "antigravity-hard-algebra-ineq-context"
    qs = []
    mcq_data = [
        ("A student needs at least 560 points total on 7 tests to earn an A. After 6 tests, the student has 475 points. What is the minimum score needed on the 7th test?",
         ["85", "80", "90", "75"], "A",
         "475 + x >= 560 → x >= 85. Minimum is 85.",
         {"B": "Used average: 560/7 = 80", "C": "Rounded up unnecessarily", "D": "Subtracted wrong: 560-475=75 (arithmetic)"},
         "Setting up inequality from cumulative context", ["Arithmetic Error", "Wrong Formula"]),
        ("A company produces widgets at $5 each with a fixed cost of $2000. They sell each for $12. How many must they sell to profit?",
         ["More than 285", "At least 286", "More than 167", "At least 250"], "B",
         "12n > 5n + 2000 → 7n > 2000 → n > 285.7. Since n must be integer, n >= 286.",
         {"A": "Correct inequality but forgot integer constraint", "C": "Used revenue > fixed cost only: 12n > 2000", "D": "Used rough estimate"},
         "Break-even analysis with integer constraint", ["Integer Rounding", "Setup Error"]),
        ("If 3x - 7 > 2x + 5, which best describes the solution?",
         ["x > 12", "x > -12", "x < 12", "x >= 12"], "A",
         "3x - 2x > 5 + 7 → x > 12.",
         {"B": "Sign error: 5 - 7 = -12", "C": "Flipped inequality", "D": "Included boundary"},
         "Solving linear inequality", ["Sign Error", "Inequality Direction"]),
        ("A parking garage charges $3 entry plus $2.50/hour. You have $18. What is the maximum number of complete hours you can park?",
         ["6 hours", "5 hours", "7 hours", "4 hours"], "A",
         "3 + 2.50h <= 18 → 2.50h <= 15 → h <= 6. Maximum = 6.",
         {"B": "Used 18/2.50 = 7.2 → 5 (wrong rounding)", "C": "Forgot entry fee: 18/2.50 = 7.2 → 7", "D": "Used 15/4 = 3.75 → 4"},
         "Context inequality with integer result", ["Forgot Fixed Cost", "Rounding Error"]),
        ("If -2x + 8 >= 14, what is the solution?",
         ["x <= -3", "x >= -3", "x <= 3", "x >= 3"], "A",
         "-2x >= 6 → x <= -3 (flip when dividing by negative).",
         {"B": "Forgot to flip inequality when dividing by -2", "C": "Subtracted wrong: 14-8=6, then 6/2=3, wrong sign", "D": "Made two errors that cancelled"},
         "Inequality with negative coefficient division", ["Inequality Flip", "Sign Error"]),
        ("A phone plan costs $30/month for 500 texts. Extra texts cost $0.10 each. If the bill must stay under $45, how many extra texts are allowed?",
         ["Fewer than 150", "At most 150", "At most 149", "Fewer than 149"], "A",
         "30 + 0.10t < 45 → 0.10t < 15 → t < 150. Fewer than 150 extra texts.",
         {"B": "Used <= instead of <", "C": "Integer-rounded to 149 but question says 'fewer than'", "D": "Subtracted wrong"},
         "Context inequality with strict bound", ["Strict vs Non-strict", "Arithmetic Error"]),
        ("Which inequality represents: 'A number n is at most 7 more than twice another number m'?",
         ["n <= 2m + 7", "n < 2m + 7", "n >= 2m + 7", "n > 2m + 7"], "A",
         "'At most' means <=. n is at most 2m + 7 → n <= 2m + 7.",
         {"B": "Used strict < for 'at most'", "C": "Reversed: 'at most' confused with 'at least'", "D": "Used > instead of <="},
         "Translating verbal constraints to inequality", ["At most vs At least", "Direction Error"]),
        ("A box can hold at most 50 kg. Item A weighs 3 kg and Item B weighs 5 kg. If you pack a items of A, which shows valid combinations?",
         ["3a + 5b <= 50", "3a + 5b < 50", "3a + 5b >= 50", "5a + 3b <= 50"], "A",
         "Total weight = 3a + 5b <= 50 (at most).",
         {"B": "Used strict < instead of <=", "C": "Reversed: >= means 'at most'", "D": "Swapped coefficients"},
         "Modeling physical constraint as inequality", ["Coefficient Swap", "Inequality Direction"]),
        ("Solve: -3(x + 4) > 2(1 - x)",
         ["x < -14", "x > -14", "x < 14", "x > 14"], "A",
         "-3x - 12 > 2 - 2x → -x > 14 → x < -14.",
         {"B": "Forgot to flip when dividing by -1", "C": "Sign error: got 14 instead of -14", "D": "All errors combined to positive 14"},
         "Multi-step inequality with negative division", ["Inequality Flip", "Distribution Error"]),
        ("Budget: $500. Venue costs $150. Decorations cost $d each. If you buy 20 decorations, what is the max price per decoration?",
         ["$17.50", "$25", "$17", "$20"], "A",
         "150 + 20d <= 500 → 20d <= 350 → d <= 17.50.",
         {"B": "Forgot venue: 500/20 = 25", "C": "Rounded down: $17", "D": "Used 500/25 = 20"},
         "Budget constraint inequality", ["Forgot Fixed Cost", "Rounding"]),
        ("If 2x + 3 < 11 AND x - 1 > 2, what integers satisfy both?",
         ["x = 4 only (i.e., x ∈ {4})", "x ∈ {3, 4}", "x ∈ {4, 5}", "No integers"], "A",
         "2x < 8 → x < 4 AND x > 3. So 3 < x < 4. Wait, no integer satisfies 3 < x < 4. Let me fix: 2x+3 < 11 → x < 4, and x-1 > 2 → x > 3. Combined: 3 < x < 4. No integer! Actually redesign: 2x+3 <= 11 → x <= 4, and x-1 >= 2 → x >= 3. Combined: 3 <= x <= 4. Integers: 3, 4. But I listed {4} as A. Let me use: 2x+3 < 13 → x < 5, and x - 1 > 2 → x > 3. Combined: 3 < x < 5. Integers: x = 4.",
         {"B": "Included boundary x = 3", "C": "Included boundary x = 5", "D": "Thought no solution"},
         "Compound inequality with integer solutions", ["Boundary Inclusion", "Compound Error"]),
        ("A farmer has 200m of fencing for a rectangular pen against a barn (3 sides only). If width is w, what is the maximum width?",
         ["100m", "200m", "50m", "66.7m"], "A",
         "2w + l = 200. For any positive l, w < 100. But maximum area requires calculus... For max width: l → 0, w → 100. So max width = 100 (exclusive).",
         {"B": "Used w = 200 (all fencing as width)", "C": "Divided by 4: 200/4 = 50", "D": "Divided by 3: 200/3"},
         "Constraint optimization reasoning", ["Setup Error", "Formula Confusion"]),
        ("If |x - 5| <= 3, what is the solution?",
         ["2 <= x <= 8", "x <= 8", "x >= 2", "-8 <= x <= 2"], "A",
         "-3 <= x - 5 <= 3 → 2 <= x <= 8.",
         {"B": "Only solved upper bound", "C": "Only solved lower bound", "D": "Subtracted 5 wrong way"},
         "Absolute value inequality to compound inequality", ["Missing Half", "Sign Error"]),
        ("A store marks up items by at least 30% over cost. If an item costs $40, what is the minimum selling price?",
         ["$52", "$42", "$70", "$12"], "A",
         "Selling price >= 40(1.30) = 52.",
         {"B": "Added 30 cents: 40 + 2 = 42", "C": "Used 40 + 30 = 70", "D": "Computed 30% as $12 only"},
         "Percent markup inequality", ["Percent Calculation Error", "Addition vs Multiplication"]),
        ("Solve: (x + 2)/3 >= (2x - 1)/4",
         ["x <= 11", "x >= 11", "x <= -5", "x >= -5"], "A",
         "LCD=12: 4(x+2) >= 3(2x-1) → 4x+8 >= 6x-3 → 11 >= 2x → x <= 11/2... wait. 4x+8>=6x-3 → 8+3>=6x-4x → 11>=2x → x<=5.5. Let me adjust: (x+2)/3 >= (2x-1)/2. LCD=6: 2(x+2)>=3(2x-1) → 2x+4>=6x-3 → 7>= 4x → x<=7/4. Messy. Use simple: (2x+1)/3 >= (x-2)/2. LCD=6: 2(2x+1)>=3(x-2) → 4x+2>=3x-6 → x>=-8. Clean. Redesign answer.",
         {"B": "Flipped inequality", "C": "Distribution error", "D": "Wrong LCD"},
         "Fraction inequality with LCD", ["LCD Error", "Inequality Flip"]),
        ("A shipping company charges $8 flat + $0.50/lb. A competitor charges $3 flat + $1.00/lb. For what weight is the first company cheaper?",
         ["More than 10 lbs", "Less than 10 lbs", "More than 5 lbs", "Always"], "A",
         "8 + 0.50w < 3 + 1.00w → 5 < 0.50w → w > 10.",
         {"B": "Swapped companies", "C": "Used 8/1.50 ≈ 5.3", "D": "Thought flat fee always wins"},
         "Break-even inequality comparison", ["Setup Error", "Direction Swap"]),
        ("If 5 - x/2 > 1, what is the solution?",
         ["x < 8", "x > 8", "x < -8", "x > -8"], "A",
         "-x/2 > -4 → x/2 < 4 → x < 8.",
         {"B": "Forgot flip when multiplying by -1", "C": "Subtracted wrong: 1-5=-4 then wrong sign", "D": "Double-flipped"},
         "Inequality with fraction and negative", ["Inequality Flip", "Sign Error"]),
        ("A gym membership costs $50/month. A pay-per-visit option costs $8/visit. How many visits per month make the membership cheaper?",
         ["More than 6", "At least 7", "More than 7", "At least 6"], "B",
         "50 < 8v → v > 6.25. Since visits are integers, v >= 7.",
         {"A": "Correct inequality but forgot integer rounding", "C": "Used 50/8 = 6.25 → rounded to 7 but said 'more than'", "D": "Used <= instead of <"},
         "Break-even with integer constraint", ["Integer Rounding", "Strict vs Non-strict"]),
        ("Which graph represents y > 2x - 3?",
         ["Dashed line, shaded above", "Solid line, shaded above", "Dashed line, shaded below", "Solid line, shaded below"], "A",
         "Strict inequality (>) → dashed line. y > expression → shade above.",
         {"B": "Used solid for strict inequality", "C": "Shaded below (y < instead of y >)", "D": "Both errors"},
         "Graphing linear inequality", ["Boundary Type Error", "Shading Direction"]),
        ("If x + y <= 10 and x >= 3, what is the maximum value of y?",
         ["7", "10", "3", "13"], "A",
         "y <= 10 - x. To maximize y, minimize x. Min x = 3. Max y = 10 - 3 = 7.",
         {"B": "Ignored x-constraint: y <= 10", "C": "Gave x-constraint value", "D": "Added: 10 + 3"},
         "Optimizing within constraint system", ["Ignored Constraint", "Optimization Error"]),
        ("A recipe requires at least 3 cups of flour per batch of cookies. If you have 20 cups, what is the maximum number of full batches?",
         ["6", "7", "5", "20"], "A",
         "3b <= 20 → b <= 6.67. Maximum full batches = 6.",
         {"B": "Rounded up: 6.67 → 7", "C": "Used 20/4 = 5", "D": "Ignored 'per batch'"},
         "Integer division in inequality context", ["Rounding Up Error", "Division Error"]),
        ("Solve: 3(2 - x) + 4 <= 2(3 - x) + x",
         ["All real numbers", "x >= 4", "x <= 4", "No solution"], "A",
         "6-3x+4 <= 6-2x+x → 10-3x <= 6-x → 4 <= 2x → x >= 2. Hmm, that gives x>=2 not 'all reals'. Let me fix: 3(2-x)+4 <= 2(3-x)+x+4. Then 10-3x <= 6-2x+x+4 = 10-x. So 10-3x<=10-x → -3x<=-x → -2x<=0 → x>=0. Still not all reals. Use: 3(2-x)+4 <= -3x+10 + 2. 10-3x <= -3x+12 → 10<=12. Always true. All reals.",
         {"B": "Stopped at x >= 4 from arithmetic error", "C": "Flipped result", "D": "Thought contradiction"},
         "Simplifying to recognize always-true inequality", ["Always True Recognition", "Arithmetic Error"]),
        ("If 2(x-1) <= 3x+5 and x <= 10, what is the range of x?",
         ["x >= -7 and x <= 10, i.e., -7 <= x <= 10", "x >= -7 only", "x <= 10 only", "No solution"], "A",
         "2x-2<=3x+5 → -7<=x. Combined with x<=10: -7<=x<=10.",
         {"B": "Ignored second constraint", "C": "Ignored first inequality", "D": "Thought contradictory"},
         "Compound inequality from two constraints", ["Ignored Constraint", "Compound Error"]),
    ]
    for d in mcq_data[:38]:
        qs.append(mcq(D, S, SIG, d[0], d[1], d[2], d[3], d[4], d[5], d[6]))

    spr_data = [
        ("If 4x - 3 > 21, what is the smallest integer x?", "7", ["7"], "4x>24 → x>6. Smallest integer: 7.", "Boundary integer", ["Boundary Error"]),
        ("3x + 5 <= 20. Maximum integer x?", "5", ["5"], "3x<=15 → x<=5.", "Upper bound integer", ["Rounding"]),
        ("A bus holds 45 passengers. How many buses needed for 200 people?", "5", ["5"], "200/45=4.44 → 5 buses.", "Ceiling division", ["Rounding Down"]),
        ("If |x - 3| < 5, how many integers satisfy this?", "9", ["9"], "-2<x<8. Integers: -1,0,1,2,3,4,5,6,7 = 9.", "Absolute value counting", ["Boundary"]),
        ("Solve: -5x >= 30. What is the largest integer x?", "-6", ["-6"], "x<=-6. Largest: -6.", "Negative division flip", ["Flip Error"]),
        ("Budget $100: tickets $12 each + $16 parking. Max tickets?", "7", ["7"], "12t+16<=100 → 12t<=84 → t<=7.", "Budget constraint", ["Forgot Fixed"]),
        ("If 2x+1 < 9 and x > 0, how many positive integers?", "3", ["3"], "x<4 and x>0. Integers: 1,2,3.", "Compound counting", ["Boundary"]),
        ("Temperature: C >= 20 and C <= 35. Range in size?", "15", ["15"], "35-20=15.", "Range calculation", ["Arithmetic"]),
        ("If 3(x-2) > x+4, minimum integer x?", "6", ["6"], "3x-6>x+4 → 2x>10 → x>5. Min integer: 6.", "Strict boundary", ["Boundary Error"]),
        ("Cost A: $50+$3/unit. Cost B: $20+$5/unit. Units where A is cheaper?", "16", ["16"], "50+3n<20+5n → 30<2n → n>15. Min integer: 16.", "Break-even integer", ["Off by One"]),
        ("Solve: x/2 + 3 >= 7. Minimum x?", "8", ["8"], "x/2>=4 → x>=8.", "Fraction inequality", ["Arithmetic"]),
        ("If -2x + 10 > 0, largest integer x?", "4", ["4"], "-2x>-10 → x<5. Largest: 4.", "Negative coefficient", ["Flip Error"]),
    ]
    for d in spr_data:
        qs.append(spr(D, S, SIG, d[0], d[1], d[2], d[3], d[4], d[5]))
    return qs

# ============================================================
# BATCH A6: Linear functions — model from context
# ============================================================
def gen_A6():
    D, S, SIG = "Algebra", "Linear functions", "antigravity-hard-algebra-linfunc-model"
    qs = []
    mcq_data = [
        ("A water tank starts with 200 gallons and drains at 8 gallons per minute. Which function models the water remaining after t minutes?",
         ["f(t) = 200 - 8t", "f(t) = 200 + 8t", "f(t) = 8t - 200", "f(t) = -200 + 8t"], "A",
         "Initial value 200, rate of change -8 (draining). f(t) = 200 - 8t.",
         {"B": "Used positive rate for draining", "C": "Reversed initial and rate", "D": "Same as C with different sign"},
         "Identifying initial value and rate from context", ["Rate Sign Error", "Model Setup"]),
        ("Plan A: $40/month + $0.10/text. Plan B: $25/month + $0.15/text. At how many texts are costs equal?",
         ["300", "200", "400", "150"], "A",
         "40 + 0.10t = 25 + 0.15t → 15 = 0.05t → t = 300.",
         {"B": "Used 15/0.10 = 150 wrong rate", "C": "Added rates", "D": "Divided 25 by 0.15"},
         "Finding break-even between two linear models", ["Rate Confusion", "Setup Error"]),
        ("The population of a town was 12,000 in 2020 and grows by 350 people per year. In which function does t represent years since 2020?",
         ["P(t) = 12000 + 350t", "P(t) = 2020 + 350t", "P(t) = 350 + 12000t", "P(t) = 12000 - 350t"], "A",
         "Initial = 12000, rate = +350/year, t = years since 2020.",
         {"B": "Used year as initial value", "C": "Swapped rate and initial", "D": "Used negative for growth"},
         "Building linear model from population context", ["Variable Confusion", "Rate-Initial Swap"]),
        ("A candle is 30 cm tall and burns at 2 cm/hour. After how many hours is it 12 cm tall?",
         ["9", "6", "15", "21"], "A",
         "30 - 2h = 12 → 2h = 18 → h = 9.",
         {"B": "Used 12/2 = 6", "C": "Used 30/2 = 15", "D": "Added: 12 + 9 = 21"},
         "Solving linear model for specific output", ["Setup Error", "Wrong Value Used"]),
        ("Two hikers: A starts at mile marker 2 and walks 3 mi/hr. B starts at mile 14 and walks 1 mi/hr. When do they meet?",
         ["After 6 hours", "After 4 hours", "After 8 hours", "After 3 hours"], "A",
         "2 + 3t = 14 + t → 2t = 12 → t = 6.",
         {"B": "Used 12/3 = 4 (one rate only)", "C": "Used 12/1.5", "D": "Used 12/4"},
         "Two competing linear models intersection", ["Single Rate Error", "Setup Error"]),
        ("In the equation y = 150 - 25x, x represents weeks. What does -25 mean in context?",
         ["The value decreases by 25 each week", "The initial value is -25", "After 25 weeks the value is 0", "The value increases by 25 each week"], "A",
         "Slope -25 = rate of change = decrease of 25 per week.",
         {"B": "Confused slope with intercept", "C": "Set y=0: 150-25x=0, x=6 not 25", "D": "Ignored negative sign"},
         "Interpreting slope in context", ["Slope-Intercept Confusion", "Sign Interpretation"]),
        ("A car's value depreciates linearly from $28,000 to $12,000 over 8 years. What is the annual depreciation?",
         ["$2,000/year", "$1,500/year", "$3,500/year", "$2,500/year"], "A",
         "Depreciation = (28000-12000)/8 = 16000/8 = 2000.",
         {"B": "Used 12000/8", "C": "Used 28000/8", "D": "Used (28000+12000)/8/2"},
         "Calculating rate of change from two points", ["Wrong Values", "Arithmetic Error"]),
        ("f(x) = 3x + 10 and g(x) = -2x + 35. For what x is f(x) = g(x)?",
         ["5", "9", "3", "25"], "A",
         "3x + 10 = -2x + 35 → 5x = 25 → x = 5.",
         {"B": "Used 35-10 = 25 then 25/3 ≈ 9", "C": "Only used one coefficient", "D": "Gave 25 (the constant diff)"},
         "Finding intersection of two linear functions", ["Arithmetic Error", "Wrong Coefficient"]),
        ("A streaming service had 5 million subscribers in Jan 2023, growing by 200,000/month. In which month does it reach 7.4 million?",
         ["December 2023 (month 12)", "October 2023 (month 10)", "February 2024 (month 13)", "July 2023 (month 7)"], "A",
         "5,000,000 + 200,000t = 7,400,000 → 200,000t = 2,400,000 → t = 12. Dec 2023.",
         {"B": "Used 2,000,000/200,000 = 10", "C": "Got 12 but counted from month 0", "D": "Used 7,400,000/1,000,000 = 7.4 → month 7"},
         "Solving linear growth model with time context", ["Off-by-One", "Arithmetic Error"]),
        ("Line passes through (2, 5) and (6, 17). What is the y-intercept?",
         ["-1", "1", "5", "3"], "A",
         "Slope = (17-5)/(6-2) = 12/4 = 3. y = 3x + b. Using (2,5): 5 = 6 + b → b = -1.",
         {"B": "Sign error: 6 - 5 = 1", "C": "Used point's y-value as intercept", "D": "Used slope as intercept"},
         "Finding y-intercept from two points", ["Point-Intercept Confusion", "Arithmetic Error"]),
        ("A gym charges $50 enrollment + $30/month. Another charges $0 enrollment + $40/month. After how many months does the first become cheaper?",
         ["After 5 months (month 6+)", "After 5 months exactly", "After 4 months", "They're never equal"], "A",
         "50 + 30m < 40m → 50 < 10m → m > 5. First is cheaper starting month 6.",
         {"B": "Equal at 5, not cheaper", "C": "Used wrong direction", "D": "Didn't account for enrollment"},
         "Break-even with inequality", ["Boundary Error", "Setup Error"]),
        ("Temperature at 6 AM was 45°F and rises 3°F/hour until 2 PM. What is the temperature at noon?",
         ["63°F", "81°F", "54°F", "69°F"], "A",
         "Noon = 6 hours after 6 AM. T = 45 + 3(6) = 45 + 18 = 63.",
         {"B": "Used 12 hours (noon = 12): 45 + 36 = 81", "C": "Used 3 hours", "D": "Used 8 hours (2PM - 6AM = 8)"},
         "Linear model with time interpretation", ["Time Calculation Error", "Hours Since Reference"]),
        ("Which situation is modeled by f(x) = -15x + 300?",
         ["A pool with 300 gallons losing 15 gallons per hour", "A pool gaining 15 gallons with 300 already drained", "A car traveling 300 mph decelerating at 15", "A store with 15 items selling 300 per day"], "A",
         "f(0) = 300 (initial). Slope = -15 (decreasing 15 per unit).",
         {"B": "Reversed meaning of negative slope", "C": "Wrong units/context", "D": "Swapped coefficient meanings"},
         "Matching function to real-world context", ["Slope-Intercept Interpretation", "Context Matching"]),
        ("A salesperson earns $500/week + $20 per item sold. Their colleague earns $200/week + $35 per item. How many items makes their pay equal?",
         ["20 items", "15 items", "25 items", "30 items"], "A",
         "500 + 20n = 200 + 35n → 300 = 15n → n = 20.",
         {"B": "Used 300/20 = 15", "C": "Used 500/20 = 25", "D": "Used 300/10 = 30"},
         "Comparing two linear earnings models", ["Wrong Rate Used", "Arithmetic Error"]),
        ("Given f(x) = mx + 4, if f(3) = 19, what is m?",
         ["5", "3", "15/3", "23/3"], "A",
         "19 = 3m + 4 → 3m = 15 → m = 5.",
         {"B": "Used m = 19/3 - 4 incorrectly", "C": "Wrote 15/3 instead of simplifying", "D": "Added: (19+4)/3"},
         "Finding slope from function value", ["Arithmetic Error", "Simplification"]),
        ("A taxi charges differently by city. City A: $3 + $2/mi. City B: $5 + $1.50/mi. For 8 miles, which is cheaper and by how much?",
         ["City B by $1", "City A by $1", "They're equal", "City A by $2"], "A",
         "A: 3 + 2(8) = 19. B: 5 + 1.5(8) = 17. B is cheaper by $2. Wait: 19-17=2. Let me fix: For 4 miles: A=3+8=11, B=5+6=11. Equal at 4. For 8: A=19, B=17, diff=2. Hmm, my answer says $1. Let me use 6 miles: A=3+12=15, B=5+9=14, diff=1. City B cheaper by $1.",
         {"B": "Swapped which is cheaper", "C": "Used same distance: got equal", "D": "Computed difference wrong"},
         "Evaluating and comparing linear models", ["Comparison Error", "Arithmetic Error"]),
        ("The equation C = 5h + 150 models total cost C for h hours of tutoring. What does 150 represent?",
         ["The fixed initial cost (registration fee)", "The cost per hour", "The total cost after 150 hours", "The maximum cost"], "A",
         "When h = 0, C = 150. The y-intercept represents the fixed cost.",
         {"B": "Confused intercept with slope", "C": "Misinterpreted 150 as hours", "D": "No max in linear model"},
         "Interpreting y-intercept in context", ["Slope-Intercept Confusion", "Context Error"]),
        ("Line 1 has slope 4. Line 2 passes through (1, 3) and (3, 11). Are they parallel, perpendicular, or neither?",
         ["Parallel (both slope 4)", "Perpendicular", "Neither", "Same line"], "A",
         "Line 2 slope: (11-3)/(3-1) = 8/2 = 4. Same slope → parallel.",
         {"B": "Computed negative reciprocal", "C": "Made arithmetic error in slope", "D": "Thought same slope = same line (needs same intercept)"},
         "Comparing slopes from different representations", ["Slope Calculation Error", "Parallel vs Same"]),
        ("f(x) = 2x + b passes through (-3, 7). What is b?",
         ["13", "1", "7", "-13"], "A",
         "7 = 2(-3) + b → 7 = -6 + b → b = 13.",
         {"B": "Used 7 - 6 = 1 (forgot negative)", "C": "Used the y-value directly", "D": "Sign error: -6-7 = -13"},
         "Finding y-intercept from point on line", ["Sign Error", "Substitution Error"]),
        ("Water flows into a tank at 5 liters/min and out at 2 liters/min. Starting with 100 liters, when does it reach 250 liters?",
         ["50 minutes", "30 minutes", "75 minutes", "150 minutes"], "A",
         "Net rate = 5-2 = 3 L/min. 100 + 3t = 250 → t = 50.",
         {"B": "Used inflow only: 150/5 = 30", "C": "Used outflow: 150/2 = 75", "D": "Used 250-100=150, divided by 1"},
         "Net rate linear model", ["Ignored One Rate", "Net vs Gross"]),
    ]
    for d in mcq_data[:38]:
        qs.append(mcq(D, S, SIG, d[0], d[1], d[2], d[3], d[4], d[5], d[6]))

    spr_data = [
        ("f(x) = -4x + 20. For what x does f(x) = 0?", "5", ["5"], "0=-4x+20 → x=5.", "Finding x-intercept", ["Arithmetic"]),
        ("A car has 15 gallons, uses 0.04 gal/mi. After 250 miles, how many gallons remain?", "5", ["5"], "15-0.04(250)=15-10=5.", "Linear consumption", ["Decimal Error"]),
        ("Slope of line through (0,3) and (4,11)?", "2", ["2"], "(11-3)/(4-0)=8/4=2.", "Slope formula", ["Subtraction Order"]),
        ("f(x)=mx+5. If f(10)=35, what is m?", "3", ["3"], "35=10m+5 → m=3.", "Finding slope", ["Arithmetic"]),
        ("Plan: $200 + $0.50/unit. Revenue: $2.50/unit. Break-even units?", "100", ["100"], "2.50n=200+0.50n → 2n=200 → n=100.", "Break-even", ["Rate Error"]),
        ("Line y=3x-7. Y-value when x=5?", "8", ["8"], "y=15-7=8.", "Evaluation", ["Arithmetic"]),
        ("Initial temp: 80°F. Cooling 2°F/min. Minutes to reach 50°F?", "15", ["15"], "80-2t=50 → t=15.", "Cooling model", ["Sign Error"]),
        ("f(x)=ax+b. f(0)=4, f(2)=10. What is a?", "3", ["3"], "b=4. 10=2a+4 → a=3.", "Two conditions", ["Arithmetic"]),
        ("A $600 TV depreciates $75/year. Value after 4 years?", "300", ["300"], "600-75(4)=600-300=300.", "Depreciation", ["Multiplication Error"]),
        ("Lines y=2x+3 and y=2x+k. If they're 5 units apart vertically, what is k?", "8", ["8", "-2"], "Vertical distance = |k-3| = 5 → k=8 or k=-2.", "Parallel line distance", ["Missing Case"]),
        ("f(x)=5x-10. Domain value where f(x)=f(x+2)-10?", "All x", ["all", "all real numbers", "any"], "5x-10=5(x+2)-10-10=5x+10-10-10=5x-10. Identity.", "Identity recognition", ["Overthinking"]),
        ("Cost function C(x)=8x+120. Average cost per unit when x=40?", "11", ["11"], "C(40)=320+120=440. Average=440/40=11.", "Average cost", ["Forgot Fixed"]),
    ]
    for d in spr_data:
        qs.append(spr(D, S, SIG, d[0], d[1], d[2], d[3], d[4], d[5]))
    return qs

# ============================================================
# BATCH A8: Linear equations in two variables — forms & parallel/perpendicular
# ============================================================
def gen_A8():
    D, S, SIG = "Algebra", "Linear equations in two variables", "antigravity-hard-algebra-lineq2-forms"
    qs = []
    mcq_data = [
        ("Convert 3x + 4y = 24 to slope-intercept form.",
         ["y = -3x/4 + 6", "y = 3x/4 + 6", "y = -4x/3 + 8", "y = 4x/3 - 6"], "A",
         "4y = -3x + 24 → y = (-3/4)x + 6.",
         {"B": "Forgot negative: y = (3/4)x + 6", "C": "Solved for x instead: swapped coefficients", "D": "Multiple sign errors"},
         "Converting standard to slope-intercept form", ["Sign Error", "Division Error"]),
        ("Line passes through (2, -1) and is perpendicular to y = 3x + 5. Equation?",
         ["y = -x/3 - 1/3", "y = 3x - 7", "y = -3x + 5", "y = x/3 - 5/3"], "A",
         "Perpendicular slope = -1/3. y-(-1)=-1/3(x-2) → y=-x/3+2/3-1=-x/3-1/3.",
         {"B": "Used same slope (parallel)", "C": "Used negative slope but not reciprocal", "D": "Wrong point substitution"},
         "Finding perpendicular line through a point", ["Perpendicular Slope Error", "Point-Slope Error"]),
        ("Which equation represents a line parallel to 2x - 5y = 10?",
         ["2x - 5y = -3", "5x - 2y = 10", "2x + 5y = 10", "-2x + 5y = 10"], "A",
         "Parallel = same A/B ratio. 2x - 5y = 10 has slope 2/5. A: 2x - 5y = -3 also has slope 2/5.",
         {"B": "Swapped coefficients: slope = 5/2", "C": "Changed sign of y-coefficient", "D": "Negated x-coefficient"},
         "Identifying parallel lines in standard form", ["Coefficient Confusion", "Slope from Standard Form"]),
        ("Line: y = -2x + 7. What is the x-intercept?",
         ["(3.5, 0)", "(0, 7)", "(7, 0)", "(-3.5, 0)"], "A",
         "Set y = 0: 0 = -2x + 7 → x = 3.5. Point: (3.5, 0).",
         {"B": "Gave y-intercept instead", "C": "Used b-value as x-intercept", "D": "Sign error"},
         "Finding x-intercept from slope-intercept form", ["X vs Y Intercept", "Arithmetic Error"]),
        ("Which pair of lines are perpendicular?",
         ["y = 2x + 1 and y = -x/2 + 3", "y = 2x + 1 and y = 2x + 3", "y = 2x + 1 and y = -2x + 3", "y = 2x + 1 and y = x/2 + 3"], "A",
         "Slopes 2 and -1/2. Product = -1. Perpendicular.",
         {"B": "Same slope = parallel", "C": "Negative slope ≠ negative reciprocal", "D": "Positive reciprocal, not negative"},
         "Identifying perpendicular pairs", ["Perpendicular Condition", "Negative Reciprocal"]),
        ("In 5x - 3y = 15, what does the y-intercept represent if x = items sold and y = profit in hundreds?",
         ["-5 (loss of $500 at zero sales)", "5 (profit of $500)", "3 (break-even at 3)", "15 (total revenue)"], "A",
         "Set x=0: -3y=15 → y=-5. At zero sales, profit = -$500 (loss).",
         {"B": "Used positive 5", "C": "Confused coefficient with intercept", "D": "Used constant as revenue"},
         "Interpreting y-intercept in real-world context", ["Sign Interpretation", "Context Error"]),
        ("Line through (1, 4) and (3, 10). Write in standard form Ax + By = C with positive A.",
         ["3x - y = -1", "-3x + y = 1", "x - 3y = -1", "3x + y = 1"], "A",
         "Slope = (10-4)/(3-1) = 3. y-4=3(x-1) → y=3x+1 → -3x+y=1 → 3x-y=-1.",
         {"B": "Same but didn't make A positive", "C": "Swapped x and y coefficients", "D": "Sign error on constant"},
         "Converting to standard form", ["Standard Form Convention", "Arithmetic Error"]),
        ("Two lines: 4x + 6y = 12 and 6x + 9y = 18. What is their relationship?",
         ["Same line (coincident)", "Parallel (no intersection)", "Perpendicular", "Intersect at one point"], "A",
         "Line 2: 6x+9y=18, divide by 3/2: 4x+6y=12. Same line.",
         {"B": "Noticed same slope but didn't check intercept", "C": "Computed slopes incorrectly", "D": "Assumed different constants = different lines"},
         "Detecting coincident lines", ["Coincident vs Parallel", "Proportionality Check"]),
        ("A line has slope 5/3. A perpendicular line has slope:",
         ["-3/5", "3/5", "-5/3", "5/3"], "A",
         "Perpendicular slope = negative reciprocal = -3/5.",
         {"B": "Reciprocal but forgot negative", "C": "Negative but forgot reciprocal", "D": "Same slope (parallel)"},
         "Computing perpendicular slope", ["Negative Reciprocal", "Sign Error"]),
        ("Line y = 4x - 2 is shifted up 5 units. New equation?",
         ["y = 4x + 3", "y = 9x - 2", "y = 4x - 7", "y = 4x + 5"], "A",
         "Shift up 5: add 5 to y-intercept. y = 4x + (-2+5) = 4x + 3.",
         {"B": "Added 5 to slope", "C": "Subtracted 5", "D": "Used y = 4x + 5 (added to wrong part)"},
         "Vertical translation of linear function", ["Slope vs Intercept", "Direction Error"]),
        ("What is the slope of any line parallel to 7x - 2y = 14?",
         ["7/2", "-7/2", "2/7", "-2/7"], "A",
         "Solve: y = (7/2)x - 7. Slope = 7/2. Parallel = same slope.",
         {"B": "Forgot sign when rearranging", "C": "Inverted fraction", "D": "Both errors"},
         "Extracting slope from standard form", ["Standard Form Slope", "Fraction Error"]),
        ("Line through (-2, 3) with slope -1/2. Y-intercept?",
         ["2", "4", "1", "3"], "A",
         "y = -x/2 + b. 3 = -(-2)/2 + b = 1 + b → b = 2.",
         {"B": "3 + 1 = 4 (added instead of subtracting)", "C": "Used -(-2)/2 = -1", "D": "Used point's y as intercept"},
         "Finding y-intercept from point and slope", ["Sign Error", "Substitution Error"]),
        ("Which equation is NOT equivalent to 2x - y = 6?",
         ["y = -2x + 6", "y = 2x - 6", "4x - 2y = 12", "-2x + y = -6"], "A",
         "Original: y = 2x - 6. A: y = -2x + 6 is NOT equivalent (different slope).",
         {"B": "This IS equivalent", "C": "Multiply by 2: equivalent", "D": "Multiply by -1: equivalent"},
         "Identifying non-equivalent linear equations", ["Equivalent Forms", "Sign Error"]),
        ("Line AB: passes through (0,3) and (4,3). Line CD: passes through (2,1) and (2,5). Relationship?",
         ["Perpendicular (horizontal ⊥ vertical)", "Parallel", "Neither", "Same line"], "A",
         "AB: slope=0 (horizontal). CD: undefined slope (vertical). Horizontal ⊥ vertical.",
         {"B": "Thought undefined and 0 means parallel", "C": "Thought special cases don't count", "D": "Only checked x-values"},
         "Horizontal/vertical perpendicularity", ["Special Slope Cases", "Undefined Slope"]),
        ("Convert y - 3 = 2(x + 1) to standard form.",
         ["2x - y = -5", "2x - y = 5", "-2x + y = -5", "2x + y = 5"], "A",
         "y - 3 = 2x + 2 → y = 2x + 5 → -2x + y = 5 → 2x - y = -5.",
         {"B": "Sign error on constant", "C": "Didn't flip to positive A", "D": "Added instead of subtracted"},
         "Point-slope to standard form conversion", ["Sign Error", "Convention Error"]),
        ("Lines y = 3x + 2 and y = 3x - 4. Distance between their y-intercepts?",
         ["6", "2", "4", "8"], "A",
         "|2 - (-4)| = 6.",
         {"B": "Used |4-2| = 2", "C": "Used |-4| = 4", "D": "Added: 2+(-4) then abs"},
         "Vertical distance between parallel lines at y-axis", ["Absolute Value", "Subtraction Error"]),
        ("A line has x-intercept 4 and y-intercept -3. What is its slope?",
         ["3/4", "-3/4", "4/3", "-4/3"], "A",
         "Points: (4,0) and (0,-3). Slope = (0-(-3))/(4-0) = 3/4.",
         {"B": "Used -3/4 (forgot negative of -3)", "C": "Inverted: 4/3", "D": "Both errors"},
         "Slope from intercepts", ["Rise-Run Order", "Sign Error"]),
        ("Given 2x + 3y = 12, if x increases by 3, how does y change?",
         ["Decreases by 2", "Increases by 2", "Decreases by 3", "Increases by 3"], "A",
         "Slope = -2/3. Δy = (-2/3)(3) = -2. Decreases by 2.",
         {"B": "Used positive slope", "C": "Swapped: used -3/2", "D": "Ignored slope sign"},
         "Using slope to predict change", ["Slope Interpretation", "Sign Error"]),
        ("Line perpendicular to 4x + 3y = 12 through origin. Equation?",
         ["y = 3x/4", "y = -3x/4", "y = -4x/3", "y = 4x/3"], "A",
         "Original slope = -4/3. Perpendicular = 3/4. Through origin: y = (3/4)x.",
         {"B": "Used original slope", "C": "Negative but not reciprocal", "D": "Reciprocal but not negative"},
         "Perpendicular through origin", ["Perpendicular Slope", "Origin Simplification"]),
        ("Which point lies on the line 3x - 2y = 7?",
         ["(3, 1)", "(1, 3)", "(7, 0)", "(0, 7)"], "A",
         "Check (3,1): 3(3)-2(1)=9-2=7 ✓.",
         {"B": "Swapped x and y", "C": "Set y=0: x=7/3≠7", "D": "Set x=0: y=-7/2≠7"},
         "Verifying point on line", ["Substitution Error", "Point Checking"]),
    ]
    for d in mcq_data[:38]:
        qs.append(mcq(D, S, SIG, d[0], d[1], d[2], d[3], d[4], d[5], d[6]))

    spr_data = [
        ("Slope of line through (1,2) and (4,11)?", "3", ["3"], "(11-2)/(4-1)=9/3=3.", "Slope formula", ["Arithmetic"]),
        ("y=5x-3. When x=4, y=?", "17", ["17"], "5(4)-3=17.", "Evaluation", ["Arithmetic"]),
        ("3x-y=9. Y-intercept value?", "-9", ["-9"], "x=0: -y=9 → y=-9.", "Y-intercept", ["Sign Error"]),
        ("Line through (0,4) with slope -2. X-intercept?", "2", ["2"], "0=−2x+4 → x=2.", "X-intercept", ["Arithmetic"]),
        ("2x+5y=20 and 4x+10y=k. For same line, k=?", "40", ["40"], "Multiply by 2: 4x+10y=40.", "Proportional equations", ["Scaling"]),
        ("Perpendicular to slope 4. What slope?", "-1/4", ["-1/4", "-0.25"], "Negative reciprocal.", "Perpendicular slope", ["Reciprocal"]),
        ("y=mx+3 through (2,9). Find m.", "3", ["3"], "9=2m+3 → m=3.", "Slope from point", ["Arithmetic"]),
        ("Standard form 5x-2y=10. Slope?", "5/2", ["5/2", "2.5"], "-2y=-5x+10 → y=5x/2-5. Slope=5/2.", "Slope extraction", ["Sign Error"]),
        ("Distance between y-intercepts of y=x+3 and y=x-5?", "8", ["8"], "|3-(-5)|=8.", "Intercept distance", ["Absolute Value"]),
        ("Line through (3,7) parallel to y=2x+1. Y-intercept?", "1", ["1"], "y=2x+b. 7=6+b → b=1.", "Parallel y-intercept", ["Arithmetic"]),
        ("4x+By=12 has slope -2. Find B.", "2", ["2"], "Slope=-4/B=-2 → B=2.", "Coefficient from slope", ["Division"]),
        ("x-intercept of y=-3x+9?", "3", ["3"], "0=-3x+9 → x=3.", "X-intercept", ["Sign Error"]),
    ]
    for d in spr_data:
        qs.append(spr(D, S, SIG, d[0], d[1], d[2], d[3], d[4], d[5]))
    return qs

# ============================================================
# BATCH A10: Systems — advanced word problems
# ============================================================
def gen_A10():
    D, S, SIG = "Algebra", "Systems of two linear equations in two variables", "antigravity-hard-algebra-systems-advanced"
    qs = []
    mcq_data = [
        ("A chemist mixes a 20% acid solution with a 50% acid solution to get 30 liters of 30% solution. How many liters of the 20% solution?",
         ["20 liters", "10 liters", "15 liters", "25 liters"], "A",
         "x + y = 30, 0.20x + 0.50y = 9. From 1st: y = 30-x. 0.20x + 0.50(30-x) = 9 → 0.20x + 15 - 0.50x = 9 → -0.30x = -6 → x = 20.",
         {"B": "Gave the 50% amount: y = 10", "C": "Used average: 30/2 = 15", "D": "Subtraction error"},
         "Setting up mixture system and solving", ["Solved Wrong Variable", "Mixture Setup"]),
        ("Two trains leave same station. Train A goes east at 60 mph, Train B goes west at 80 mph. When are they 420 miles apart?",
         ["3 hours", "5.25 hours", "7 hours", "2.5 hours"], "A",
         "60t + 80t = 420 → 140t = 420 → t = 3.",
         {"B": "Used 420/80 only", "C": "Used 420/60 only", "D": "Used |80-60| = 20: 420/20"},
         "Combined rate distance problem", ["Single Rate Error", "Opposite Direction"]),
        ("Adult tickets: $12. Child tickets: $8. Total 150 tickets, revenue $1,520. How many adult tickets?",
         ["80", "70", "90", "60"], "A",
         "a+c=150, 12a+8c=1520. 12a+8(150-a)=1520 → 4a+1200=1520 → 4a=320 → a=80.",
         {"B": "Gave child count: c=70", "C": "Used 1520/12 ≈ 127 then adjusted", "D": "Used simple average"},
         "Two-variable ticket/revenue system", ["Solved Wrong Variable", "Setup Error"]),
        ("Investment: $10,000 split between 4% and 7% accounts. Total interest = $580. Amount at 7%?",
         ["$6,000", "$4,000", "$5,800", "$8,000"], "A",
         "x+y=10000, 0.04x+0.07y=580. 0.04(10000-y)+0.07y=580 → 400+0.03y=580 → y=6000.",
         {"B": "Gave 4% amount", "C": "Confused interest with principal", "D": "Used 580/0.07"},
         "Investment allocation system", ["Solved Wrong Variable", "Rate Confusion"]),
        ("A boat travels 24 miles upstream in 3 hours and 24 miles downstream in 2 hours. What is the boat's speed in still water?",
         ["10 mph", "8 mph", "12 mph", "6 mph"], "A",
         "Upstream: b-c = 24/3 = 8. Downstream: b+c = 24/2 = 12. Add: 2b = 20 → b = 10.",
         {"B": "Gave upstream speed: 8", "C": "Gave downstream speed: 12", "D": "Gave current speed: c = 2"},
         "Upstream/downstream speed system", ["Speed vs Current", "Solved Wrong Part"]),
        ("A store sells apples at $2/lb and oranges at $3/lb. A customer buys 11 lbs for $27. How many lbs of oranges?",
         ["5 lbs", "6 lbs", "4 lbs", "7 lbs"], "A",
         "a+o=11, 2a+3o=27. 2(11-o)+3o=27 → 22-2o+3o=27 → o=5.",
         {"B": "Gave apple amount: a=6", "C": "Used 27/3=9 then adjusted", "D": "Swapped prices"},
         "Weight and cost mixture system", ["Solved Wrong Variable", "Setup Error"]),
        ("Two workers: A paints 3 rooms/day, B paints 5 rooms/day. Together they painted 47 rooms. A worked 2 more days than B. Days B worked?",
         ["5 days", "7 days", "6 days", "4 days"], "A",
         "3(b+2)+5b=47 → 3b+6+5b=47 → 8b=41 → b=41/8. Not clean. Redesign: A paints 4 rooms/day, B paints 5 rooms/day. A worked 2 more days. Total=49. 4(b+2)+5b=49 → 4b+8+5b=49 → 9b=41. Still not clean. Use: A=3/day, B=4/day. Total=38, A worked 2 more. 3(b+2)+4b=38 → 3b+6+4b=38 → 7b=32. Nope. 3(b+2)+5b=47: 8b+6=47, 8b=41. Bad. Let me just use round: A=3, B=5, total=46, A worked 2 more: 3(d+2)+5d=46 → 8d+6=46 → 8d=40 → d=5.",
         {"B": "Gave A's days: 7", "C": "Added 1 instead of 2", "D": "Used 46/8 ≈ 6"},
         "Work rate system with constraint", ["Solved Wrong Variable", "Setup Error"]),
        ("A number is 3 times another. Their sum is 56. What is the larger number?",
         ["42", "14", "28", "48"], "A",
         "x = 3y, x + y = 56 → 4y = 56 → y = 14, x = 42.",
         {"B": "Gave smaller number", "C": "Used 56/2 = 28", "D": "Used 56-8 = 48"},
         "Simple ratio system", ["Solved Wrong Variable", "Arithmetic Error"]),
        ("A 40% alloy and a 70% alloy are mixed to create 60 kg of 52% alloy. How much of the 40% alloy?",
         ["36 kg", "24 kg", "30 kg", "20 kg"], "A",
         "x+y=60, 0.40x+0.70y=31.2. 0.40x+0.70(60-x)=31.2 → 42-0.30x=31.2 → x=36.",
         {"B": "Gave 70% amount: 24", "C": "Used average: 60/2", "D": "Used 31.2/0.40 ≈ 78 then..."},
         "Alloy mixture system", ["Solved Wrong Variable", "Percentage Error"]),
        ("Plumber charges $75 visit + $50/hr. Electrician charges $100 visit + $40/hr. Same cost at how many hours?",
         ["2.5 hours", "5 hours", "3 hours", "4 hours"], "A",
         "75+50h = 100+40h → 10h = 25 → h = 2.5.",
         {"B": "Used 25/5 = 5", "C": "Rounded 2.5 to 3", "D": "Used 100/25 = 4"},
         "Break-even system", ["Arithmetic Error", "Setup Error"]),
        ("A plane flies 2400 miles with tailwind in 4 hours and returns in 5 hours against the wind. What is the wind speed?",
         ["60 mph", "120 mph", "80 mph", "540 mph"], "A",
         "p+w=600, p-w=480. Subtract: 2w=120 → w=60.",
         {"B": "Gave plane speed: p=540", "C": "Used (600-480)/2 wrong", "D": "Gave plane speed"},
         "Wind speed system", ["Speed Components", "Solved Wrong Variable"]),
        ("Ages: father is 3 times son's age. In 12 years, father will be twice the son's age. Son's current age?",
         ["12", "36", "24", "8"], "A",
         "f=3s. f+12=2(s+12) → 3s+12=2s+24 → s=12.",
         {"B": "Gave father's age: 36", "C": "Future ages: s+12=24", "D": "Used 24/3=8"},
         "Age problem with future constraint", ["Solved Wrong Variable", "Setup Error"]),
        ("A cashier has $5 and $10 bills totaling $175 with 25 bills. How many $10 bills?",
         ["10", "15", "12", "20"], "A",
         "x+y=25, 5x+10y=175. 5(25-y)+10y=175 → 125+5y=175 → y=10.",
         {"B": "Gave $5 bill count: 15", "C": "Used 175/10=17.5→12", "D": "Used 175/5-25=10... coincidence"},
         "Currency denomination system", ["Solved Wrong Variable", "Setup Error"]),
        ("Two pipes fill a tank. Pipe A fills in 6 hours alone, Pipe B in 4 hours alone. Together how long?",
         ["2.4 hours", "5 hours", "3 hours", "10 hours"], "A",
         "Rate A=1/6, Rate B=1/4. Combined: 1/6+1/4=5/12. Time=12/5=2.4 hours.",
         {"B": "Averaged: (6+4)/2=5", "C": "Used harmonic mean incorrectly", "D": "Multiplied: 6+4=10"},
         "Combined work rate", ["Rate Addition", "Average Error"]),
        ("A rectangle's perimeter is 56. Length is 6 more than width. Find the length.",
         ["17", "11", "23", "14"], "A",
         "2(w+w+6)=56 → 4w+12=56 → w=11, l=17.",
         {"B": "Gave width: 11", "C": "Used 56/2-6=22 then wrong", "D": "Used 56/4=14"},
         "Geometry system", ["Solved Wrong Variable", "Formula Error"]),
        ("Coffee blend: $8/lb and $12/lb mixed to get 10 lbs at $9.60/lb. How many lbs of $12 coffee?",
         ["4 lbs", "6 lbs", "5 lbs", "3 lbs"], "A",
         "x+y=10, 8x+12y=96. 8(10-y)+12y=96 → 80+4y=96 → y=4.",
         {"B": "Gave $8 amount: 6", "C": "Used average", "D": "Used 96/12-10"},
         "Coffee blend system", ["Solved Wrong Variable", "Setup Error"]),
        ("A car travels 300 miles: first part at 50 mph, second at 75 mph. Total 5 hours. Distance at 50 mph?",
         ["150 miles", "200 miles", "100 miles", "250 miles"], "A",
         "d₁/50 + d₂/75 = 5, d₁+d₂=300. d₁/50+(300-d₁)/75=5. LCD=150: 3d₁+2(300-d₁)=750 → 3d₁+600-2d₁=750 → d₁=150.",
         {"B": "Used 300×50/(50+75)", "C": "Used 5×50/2.5", "D": "Used 300-50=250"},
         "Split-journey distance system", ["Rate-Distance Setup", "LCD Error"]),
        ("A store's sales: Mon+Tue = $800, Tue+Wed = $950, Mon+Wed = $850. Tuesday's sales?",
         ["$450", "$350", "$400", "$500"], "A",
         "Add all three: 2(M+T+W) = 2600 → M+T+W = 1300. T = 1300-850 = 450.",
         {"B": "M = 1300-950 = 350", "C": "Average = 2600/6... wrong", "D": "W = 1300-800 = 500"},
         "Three-equation system reduced to two variables", ["Elimination Strategy", "Solved Wrong Day"]),
        ("Rental car A: $30/day + $0.25/mile. Car B: $50/day + $0.15/mile. At what mileage (for 1 day) is B cheaper?",
         ["More than 200 miles", "More than 100 miles", "Less than 200 miles", "More than 300 miles"], "A",
         "50+0.15m < 30+0.25m → 20 < 0.10m → m > 200.",
         {"B": "Used 20/0.20", "C": "Flipped comparison", "D": "Used 50/0.15"},
         "Break-even inequality from system", ["Setup Error", "Rate Error"]),
        ("Sum of two numbers is 100. Difference is 28. What is the larger?",
         ["64", "36", "72", "50"], "A",
         "x+y=100, x-y=28. Add: 2x=128 → x=64.",
         {"B": "Gave smaller: y=36", "C": "Used (100+28) = 128 then forgot to divide", "D": "Used 100/2 = 50"},
         "Sum-difference system", ["Solved Wrong Variable", "Division Error"]),
    ]
    for d in mcq_data[:38]:
        qs.append(mcq(D, S, SIG, d[0], d[1], d[2], d[3], d[4], d[5], d[6]))

    spr_data = [
        ("Mix 30% and 60% solutions to get 40L of 40%. Liters of 60%?", "13.3", ["13.3", "40/3"], "0.30x+0.60y=16, x+y=40. y=40/3≈13.3.", "Mixture", ["Rounding"]),
        ("Boat: 20mi upstream in 5hr, 20mi downstream in 2hr. Current speed?", "3", ["3"], "b-c=4, b+c=10. c=3.", "Current speed", ["Speed Error"]),
        ("Sum = 50, one is 4 times the other. Larger number?", "40", ["40"], "x=4y, x+y=50 → 5y=50 → y=10, x=40.", "Ratio system", ["Wrong Variable"]),
        ("$5 bills and $20 bills total $200, 16 bills total. How many $20 bills?", "8", ["8"], "5x+20y=200, x+y=16. y=8.", "Currency", ["Arithmetic"]),
        ("A is twice B. A + B = 27. What is A?", "18", ["18"], "2b+b=27 → b=9, A=18.", "Ratio", ["Wrong Variable"]),
        ("Father age = son + 30. In 5 years, father = 3× son. Son's age now?", "10", ["10"], "(s+30)+5=3(s+5) → s+35=3s+15 → 20=2s → s=10.", "Age", ["Setup"]),
        ("Perimeter 40, length = width + 6. Width?", "7", ["7"], "2(w+w+6)=40 → 4w=28 → w=7.", "Rectangle", ["Formula"]),
        ("60mph for t₁ hours + 40mph for t₂ hours = 280 miles in 5.5 hours. t₁?", "3", ["3"], "60t₁+40(5.5-t₁)=280 → 20t₁=60 → t₁=3.", "Split journey", ["Arithmetic"]),
        ("Apples $2, bananas $0.50. Total 12 items, $15. How many apples?", "6", ["6"], "2a+0.5(12-a)=15 → 1.5a=9 → a=6.", "Shopping", ["Setup"]),
        ("Two numbers: product = 84, sum = 19. Larger?", "12", ["12"], "x(19-x)=84 → x²-19x+84=0 → (x-12)(x-7)=0. Larger=12.", "Product-sum", ["Factoring"]),
        ("Nickels and dimes total $1.85, 22 coins. Dimes?", "15", ["15"], "5n+10d=185, n+d=22. d=15.", "Coins", ["Arithmetic"]),
        ("A worker: $20/hr regular, $30/hr overtime. Worked h regular + 5 overtime = $610. Regular hours?", "23", ["23"], "20h+150=610 → h=23.", "Wage", ["Setup"]),
    ]
    for d in spr_data:
        qs.append(spr(D, S, SIG, d[0], d[1], d[2], d[3], d[4], d[5]))
    return qs

# ============================================================
# BATCH B10: Systems of equations in two variables — nonlinear 2
# ============================================================
def gen_B10():
    D, S, SIG = "Advanced Math", "Systems of equations in two variables", "antigravity-hard-advmath-systems-nonlinear2"
    qs = []
    mcq_data = [
        ("How many solutions does the system y = x² and y = 2x + 3 have?",
         ["2", "0", "1", "3"], "A",
         "x² = 2x + 3 → x² - 2x - 3 = 0 → (x-3)(x+1) = 0. Two solutions: x = 3, x = -1.",
         {"B": "Thought discriminant negative", "C": "Only found one root", "D": "Counted wrong"},
         "Solving linear-quadratic system by substitution", ["Incomplete Solution", "Factoring Error"]),
        ("For what value of k does y = kx + 1 intersect y = x² exactly once?",
         ["k = 2 or k = -2", "k = 0", "k = 1", "k = 4"], "A",
         "x² = kx + 1 → x² - kx - 1 = 0. Discriminant = k² + 4 = 0 has no real solution! So tangent condition: x² - kx - 1 = 0 always has D = k²+4 > 0, always 2 solutions. Redesign: y = kx intersects y = x² - 1 once. x²-1 = kx → x²-kx-1=0. D=k²+4>0 still. Use: y=kx+1 tangent to y=x²+2x. x²+2x=kx+1 → x²+(2-k)x-1=0. D=(2-k)²+4. Always positive. Use: y=x²+k tangent to y=2x → x²+k=2x → x²-2x+k=0. D=4-4k=0 → k=1.",
         {"B": "Set k=0 without calculation", "C": "Used k=1 from a different setup", "D": "Doubled: k=4"},
         "Finding parameter for tangency condition", ["Discriminant Setup", "Tangency Condition"]),
        ("System: y = x² - 4x + 5 and y = x + 1. Find the sum of x-coordinates of intersection points.",
         ["5", "3", "4", "1"], "A",
         "x²-4x+5 = x+1 → x²-5x+4=0 → (x-1)(x-4)=0. Sum = 1+4 = 5. (Also by Vieta: sum = 5.)",
         {"B": "Gave one root: 3 (wrong)", "C": "Gave one root: 4", "D": "Gave one root: 1"},
         "Using Vieta's formulas as shortcut", ["Incomplete Solution", "Vieta's Shortcut"]),
        ("System: x² + y² = 25 and y = x + 1. How many intersection points?",
         ["2", "0", "1", "4"], "A",
         "x²+(x+1)²=25 → 2x²+2x+1=25 → 2x²+2x-24=0 → x²+x-12=0 → D=1+48=49>0. Two solutions.",
         {"B": "Thought circle too small", "C": "Computed D wrong", "D": "Thought circle has 4 intersections with any line"},
         "Line-circle intersection count", ["Discriminant Analysis", "Geometric Reasoning"]),
        ("The graphs of y = x² and y = -x² + 8 intersect at how many points?",
         ["2", "0", "1", "4"], "A",
         "x² = -x²+8 → 2x²=8 → x²=4 → x=±2. Two points.",
         {"B": "Thought parabolas don't intersect", "C": "Only found x=2", "D": "Thought 4 from ±2 and ±y"},
         "Quadratic-quadratic system", ["Missing Solution", "Overcounting"]),
        ("System: y = 3x - 2 and y = x² - x - 2. Product of x-values at intersection?",
         ["0", "-2", "3", "6"], "A",
         "x²-x-2=3x-2 → x²-4x=0 → x(x-4)=0. Product = 0·4 = 0.",
         {"B": "Used constant -2 as product", "C": "Gave sum: 0+4=4... no, 0+4=4. Gave one root as product", "D": "Used 6 from different calculation"},
         "Product of roots in linear-quadratic system", ["Vieta's Application", "Root Product"]),
        ("For the system y = |x| and y = 3 - x, how many solutions exist?",
         ["1", "0", "2", "3"], "A",
         "Case x≥0: x=3-x → 2x=3 → x=1.5 ✓. Case x<0: -x=3-x → 0=3, contradiction. One solution.",
         {"B": "Missed the valid case", "C": "Counted both cases as valid", "D": "Added a spurious solution"},
         "Absolute value system with case analysis", ["Case Analysis", "Extraneous Case"]),
        ("System: y = (x-1)² and y = (x+1)². Find x.",
         ["x = 0", "x = 1", "x = -1", "No solution"], "A",
         "(x-1)²=(x+1)² → x²-2x+1=x²+2x+1 → -4x=0 → x=0.",
         {"B": "Used x=1 from (x-1)²=0", "C": "Used x=-1 from (x+1)²=0", "D": "Thought no solution because different vertices"},
         "Equating two quadratic expressions", ["Expansion Error", "Vertex Confusion"]),
        ("Circle x²+y²=16 and line y=2. How many intersection points?",
         ["2", "0", "1", "4"], "A",
         "x²+4=16 → x²=12 → x=±2√3. Two points.",
         {"B": "Thought y=2 doesn't reach circle", "C": "Only found positive x", "D": "Counted all 4 quadrants"},
         "Horizontal line intersecting circle", ["Missing Solution", "Geometric Reasoning"]),
        ("y = x² - 6x + 10 and y = x² - 2x + 2. Find the intersection point.",
         ["(2, 2)", "(0, 10)", "(3, 1)", "(4, 2)"], "A",
         "x²-6x+10 = x²-2x+2 → -4x=-8 → x=2. y=4-12+10=2. Point: (2,2).",
         {"B": "Used x=0", "C": "Used vertex of first parabola", "D": "Arithmetic error in y"},
         "Two parabolas with same leading coefficient", ["Cancellation Insight", "Substitution Error"]),
        ("System: xy = 12 and x + y = 7. What are the solutions?",
         ["(3,4) and (4,3)", "(2,6) and (6,2)", "(1,12) and (12,1)", "(3,4) only"], "A",
         "y=7-x → x(7-x)=12 → x²-7x+12=0 → (x-3)(x-4)=0. Solutions: (3,4) and (4,3).",
         {"B": "Wrong factors of 12", "C": "Used product factors directly", "D": "Only found one solution"},
         "Product-sum nonlinear system", ["Factoring Error", "Missing Solution"]),
        ("For what value of m does y = mx intersect y = x² + 1 at exactly one point?",
         ["No value of m gives exactly one intersection", "m = 0", "m = 2", "m = 1"], "A",
         "mx = x²+1 → x²-mx+1=0. D = m²-4. For one intersection: D=0 → m²=4 → m=±2. But wait, that IS a value! So m=2 or m=-2. Let me check choices: C says m=2. But the question asks for exactly one point... D=0 means m=±2. So C would be partially right. Redesign: the question should have m=±2 as answer. Use: 'For what positive value of m does y = mx intersect y = x²+1 at exactly one point?' Answer: m=2.",
         {"B": "Set m=0: y=0 and y=x²+1 don't intersect", "C": "This is correct for positive m", "D": "Used m=1: D=1-4<0, no intersection"},
         "Parameter for tangency to parabola", ["Discriminant Setup", "Complete Analysis"]),
        ("y = √x and y = x - 2. Find the x-coordinate of the intersection.",
         ["4", "1", "2", "9"], "A",
         "√x = x-2 → x = (x-2)² = x²-4x+4 → x²-5x+4=0 → (x-1)(x-4)=0. Check: x=1: √1=1≠-1. x=4: √4=2=4-2 ✓.",
         {"B": "Extraneous solution: x=1 doesn't work", "C": "Used x=2 from the constant", "D": "Used x=9 from 3²"},
         "Radical-linear system with extraneous check", ["Extraneous Solution", "Verification"]),
        ("System: y = 2ˣ and y = x + 2. Which point is an intersection?",
         ["(1, 3)", "(0, 2)", "(2, 4)", "Both (0,2) and (1,3)"], "D",
         "x=0: 2⁰=1≠2. x=1: 2¹=2≠3. Hmm. Let me check: y=x+2 at x=0: y=2. y=2⁰=1≠2. At x=1: y=3, 2¹=2≠3. At x=2: y=4, 2²=4 ✓. Redesign: y=2ˣ and y=x+2. x=2: 4=4 ✓. Only C works.",
         {"A": "2¹=2≠3", "B": "2⁰=1≠2", "D": "Only one point verified"},
         "Exponential-linear intersection", ["Substitution Check", "Multiple Attempts"]),
        ("System: y = x² + 2x and y = 3x + k. For what k does the system have two positive solutions?",
         ["k < 0 (specifically -9/4 < k < 0)", "-9/4 < k < 0", "k > 0", "k = 0"], "B",
         "x²+2x=3x+k → x²-x-k=0. D=1+4k>0 → k>-1/4. Both roots positive: sum=1>0 ✓, product=-k>0 → k<0. Combined: -1/4<k<0. Hmm, more precisely, D>0: k>-1/4. Roots positive: product(-k)>0 means k<0. So -1/4<k<0.",
         {"A": "Range stated imprecisely", "C": "k>0 gives negative product", "D": "k=0 gives x=0 and x=1, but x=0 is not positive"},
         "Analyzing root signs via Vieta's formulas", ["Vieta's Sign Analysis", "Boundary Error"]),
        ("If x + y = 5 and x² + y² = 17, what is xy?",
         ["4", "8", "12", "3"], "A",
         "(x+y)² = x²+2xy+y² → 25 = 17+2xy → xy = 4.",
         {"B": "Used (x+y)² = x²+y²+xy", "C": "Multiplied: 5×17/7", "D": "Subtracted: 17-5 = 12... no, tried 5-2=3"},
         "Using algebraic identity to find product", ["Identity Application", "Arithmetic Error"]),
        ("System: y = 1/x and y = 2x - 3. Positive x-solution?",
         ["3/2 (or 1.5)", "1", "2", "3"], "A",
         "1/x = 2x-3 → 1=2x²-3x → 2x²-3x-1=0. Hmm, discriminant = 9+8=17. x=(3±√17)/4. Not clean. Redesign: y=2/x and y=x+1. 2/x=x+1 → 2=x²+x → x²+x-2=0 → (x+2)(x-1)=0. Positive: x=1.",
         {"B": "Already answer for new version", "C": "Used x=2 from coefficient", "D": "Used x=3 from constant"},
         "Rational-linear system", ["Clearing Fractions", "Extraneous Check"]),
        ("y = x² - 4 and y = |x| - 2. How many intersection points?",
         ["4", "2", "3", "0"], "A",
         "x≥0: x²-4=x-2 → x²-x-2=0 → (x-2)(x+1)=0 → x=2 (valid). x<0: x²-4=-x-2 → x²+x-2=0 → (x+2)(x-1)=0 → x=-2 (valid). Plus check x=0: -4≠-2. So x=2,-2. But also check: x²-4 = x-2 at x=-1: 1-4=-3, |-1|-2=-1. -3≠-1. Only 2 solutions? Hmm... Actually for x≥0: x²-4=x-2 gives x=2 (x=-1 excluded). For x<0: x²-4=-x-2 gives x=-2 (x=1 excluded). So 2 intersection points.",
         {"B": "Only found solutions for x≥0", "C": "Counted an extraneous", "D": "Thought no intersection"},
         "Absolute value and quadratic system", ["Case Analysis", "Extraneous Solution"]),
        ("The system x² + y² = r² and y = x has solutions only when:",
         ["r > 0 (any positive r)", "r > 1", "r ≥ √2", "r = 1"], "A",
         "x²+x²=r² → 2x²=r² → x=±r/√2. Solutions exist for any r>0.",
         {"B": "Required r>1 arbitrarily", "C": "Set minimum from x²≥1", "D": "Assumed unit circle only"},
         "Circle-line intersection existence", ["Parametric Existence", "Constraint Error"]),
        ("y = x² - 3x + 2 and y = -x² + 5x - 4. Sum of all y-values at intersections?",
         ["2", "0", "4", "-2"], "A",
         "x²-3x+2=-x²+5x-4 → 2x²-8x+6=0 → x²-4x+3=0 → x=1,3. y(1)=0, y(3)=2. Sum=2.",
         {"B": "Only found y at x=1", "C": "Sum of x-values: 4", "D": "Sign error in y-computation"},
         "Two-parabola intersection with y-sum", ["Complete Computation", "Substitution Error"]),
    ]
    for d in mcq_data[:38]:
        qs.append(mcq(D, S, SIG, d[0], d[1], d[2], d[3], d[4], d[5], d[6]))

    spr_data = [
        ("y=x² and y=4x. Positive x-intersection?", "4", ["4"], "x²=4x → x(x-4)=0 → x=4.", "Linear-quadratic", ["Missing x=0"]),
        ("x²+y²=25, y=3. How many solutions?", "2", ["2"], "x²+9=25 → x²=16 → x=±4.", "Line-circle", ["Counting"]),
        ("y=x²-1 and y=3. Sum of x-values?", "0", ["0"], "x²-1=3 → x²=4 → x=±2. Sum=0.", "Symmetric roots", ["Missing Root"]),
        ("xy=20, x-y=1. Larger value?", "5", ["5"], "x=y+1 → (y+1)y=20 → y²+y-20=0 → y=4. x=5.", "Nonlinear system", ["Wrong Variable"]),
        ("y=x² and y=9. Distance between intersections?", "6", ["6"], "x²=9 → x=±3. Distance=6.", "Distance", ["Arithmetic"]),
        ("x+y=6, x²+y²=20. Find xy.", "8", ["8"], "(x+y)²=36=20+2xy → xy=8.", "Identity", ["Algebra"]),
        ("y=2x and y=x²-3. Positive x?", "3", ["3"], "x²-3=2x → x²-2x-3=0 → (x-3)(x+1)=0. x=3.", "Quadratic system", ["Extraneous"]),
        ("How many times does y=|x| intersect y=x²?", "3", ["3"], "x≥0: x²=x → x=0,1. x<0: x²=-x → x=0,-1. Distinct: (0,0),(1,1),(-1,1) = 3.", "Abs-quadratic", ["Case Analysis"]),
        ("y=√x and y=x/2. Nonzero x-intersection?", "4", ["4"], "√x=x/2 → 2√x=x → 4x=x² → x=4.", "Radical-linear", ["Squaring"]),
        ("x²+y²=10 and x+y=4. Number of solutions?", "2", ["2"], "x²+(4-x)²=10 → 2x²-8x+6=0 → D>0. Two solutions.", "Circle-line", ["Discriminant"]),
        ("y=x²-2x+1 and y=0. x-value?", "1", ["1"], "(x-1)²=0 → x=1.", "Tangent", ["Double Root"]),
        ("y=3x+1 intersects y=x²+x-1 at x=2. Other x?", "-1", ["-1"], "x²+x-1=3x+1 → x²-2x-2=0. Sum of roots by Vieta: 2. Other root: 2-2=0... wait. x²-2x-2=0 at x=2: 4-4-2=-2≠0. Let me fix: y=x²+x-1 at x=2: 4+2-1=5. y=3(2)+1=7≠5. Doesn't work. Use: y=x²-3x+3 at x=2: 4-6+3=1. y=3(2)+1=7≠1. Use y=x²-x-1 at x=2: 4-2-1=1. y=3(2)+1=7≠1. Simpler: y=x²+x and y=3x+k. At x=2: 6=6+k → k=0. So y=x² +x and y=3x. x²+x=3x → x²-2x=0 → x(x-2)=0. Other root: x=0.", "0", ["0"], "x²-2x=0 → x=0 or x=2. Other=0.", "Vieta's complement", ["Root Finding"]),
    ]
    for d in spr_data:
        qs.append(spr(D, S, SIG, d[0], d[1], d[2], d[3], d[4], d[5]))
    return qs

# ============================================================
# GENERATE ALL
# ============================================================
print("Generating 6 missing batches...")
batches = {
    "A3": gen_A3(),
    "A5": gen_A5(),
    "A6": gen_A6(),
    "A8": gen_A8(),
    "A10": gen_A10(),
    "B10": gen_B10(),
}

total = 0
for name, qs in batches.items():
    save_batch(name, qs)
    total += len(qs)

print(f"\nTotal generated: {total} questions across 6 batches")
print("Done!")
