const { spawnSync } = require("node:child_process");

const includeSmoke = process.argv.includes("--smoke");

const commands = [
  ["node", ["--check", "app.js"]],
  ["node", ["--check", "sat_core.js"]],
  ["node", ["--check", "sat_architecture_manifest.js"]],
  ["node", ["--check", "sat_i18n.js"]],
  ["node", ["--check", "sat_storage.js"]],
  ["node", ["--check", "sat_indexeddb.js"]],
  ["node", ["--check", "sat_public_api.js"]],
  ["node", ["--check", "sat_richtext.js"]],
  ["node", ["--check", "sat_design_system.js"]],
  ["node", ["--check", "sat_entry_engine.js"]],
  ["node", ["--check", "app_student.js"]],
  ["node", ["--check", "app_parent.js"]],
  ["node", ["--check", "app_admin.js"]],
  ["node", ["--check", "sat_view_renderers.js"]],
  ["node", ["--check", "sat_admin_view_renderers.js"]],
  ["node", ["--check", "sat_account_view_renderers.js"]],
  ["node", ["--check", "sat_content_lifecycle_engine.js"]],
  ["node", ["--check", "sat_permissions.js"]],
  ["node", ["--check", "sat_role_boundary_engine.js"]],
  ["node", ["--check", "sat_public_manifest_engine.js"]],
  ["node", ["--check", "sat_question_query_engine.js"]],
  ["node", ["--check", "sat_content_package_engine.js"]],
  ["node", ["--check", "sat_learner_content_gateway.js"]],
  ["node", ["--check", "sat_content_admin_engine.js"]],
  ["node", ["--check", "sat_question_import.js"]],
  ["node", ["--check", "sat_import_engine.js"]],
  ["node", ["--check", "sat_router_engine.js"]],
  ["node", ["--check", "sat_dashboard_engine.js"]],
  ["node", ["--check", "sat_data_loaders.js"]],
  ["node", ["--check", "sat_adaptive_routing_engine.js"]],
  ["node", ["--check", "sat_diagnostic_engine.js"]],
  ["node", ["--check", "sat_lesson_engine.js"]],
  ["node", ["--check", "sat_remediation_engine.js"]],
  ["node", ["--check", "sat_practice_engine.js"]],
  ["node", ["--check", "sat_mastery_engine.js"]],
  ["node", ["--check", "sat_roadmap_engine.js"]],
  ["node", ["--check", "sat_student_experience_engine.js"]],
  ["node", ["--check", "sat_learning_event_engine.js"]],
  ["node", ["--check", "sat_duplicate_engine.js"]],
  ["node", ["--check", "sat_authoring_engine.js"]],
  ["node", ["--check", "sat_quality_intake_engine.js"]],
  ["node", ["--check", "sat_account_engine.js"]],
  ["node", ["--check", "sat_exam_review_engine.js"]],
  ["node", ["--check", "sat_question_audit_engine.js"]],
  ["node", ["--check", "sat_item_analytics_engine.js"]],
  ["node", ["--check", "sat_irt_calibration_engine.js"]],
  ["node", ["--check", "scripts/export_public_manifest_artifact.js"]],
  ["node", ["--check", "scripts/review_and_promote_public_safe_questions.js"]],
  ["node", ["--check", "scripts/resolve_question_audit.js"]],
  ["node", ["--check", "scripts/save_authored_question.js"]],
  ["node", ["--check", "scripts/save_source_signal.js"]],
  ["node", ["scripts/core_unit_tests.js"]],
  ["node", ["scripts/architecture_boundary_tests.js"]],
  ["node", ["scripts/i18n_unit_tests.js"]],
  ["node", ["scripts/storage_unit_tests.js"]],
  ["node", ["scripts/indexeddb_unit_tests.js"]],
  ["node", ["scripts/public_api_unit_tests.js"]],
  ["node", ["scripts/richtext_unit_tests.js"]],
  ["node", ["scripts/design_system_unit_tests.js"]],
  ["node", ["scripts/entry_engine_unit_tests.js"]],
  ["node", ["scripts/view_renderers_unit_tests.js"]],
  ["node", ["scripts/admin_view_renderers_unit_tests.js"]],
  ["node", ["scripts/account_view_renderers_unit_tests.js"]],
  ["node", ["scripts/content_lifecycle_engine_unit_tests.js"]],
  ["node", ["scripts/permissions_unit_tests.js"]],
  ["node", ["scripts/role_boundary_engine_unit_tests.js"]],
  ["node", ["scripts/public_manifest_engine_unit_tests.js"]],
  ["node", ["scripts/question_query_engine_unit_tests.js"]],
  ["node", ["scripts/content_package_engine_unit_tests.js"]],
  ["node", ["scripts/learner_content_gateway_unit_tests.js"]],
  ["node", ["scripts/content_admin_engine_unit_tests.js"]],
  ["node", ["scripts/question_import_unit_tests.js"]],
  ["node", ["scripts/import_engine_unit_tests.js"]],
  ["node", ["scripts/router_engine_unit_tests.js"]],
  ["node", ["scripts/dashboard_engine_unit_tests.js"]],
  ["node", ["scripts/data_loaders_unit_tests.js"]],
  ["node", ["scripts/adaptive_routing_engine_unit_tests.js"]],
  ["node", ["scripts/diagnostic_engine_unit_tests.js"]],
  ["node", ["scripts/lesson_engine_unit_tests.js"]],
  ["node", ["scripts/remediation_engine_unit_tests.js"]],
  ["node", ["scripts/practice_engine_unit_tests.js"]],
  ["node", ["scripts/mastery_engine_unit_tests.js"]],
  ["node", ["scripts/roadmap_engine_unit_tests.js"]],
  ["node", ["scripts/learning_event_engine_unit_tests.js"]],
  ["node", ["scripts/duplicate_engine_unit_tests.js"]],
  ["node", ["scripts/authoring_engine_unit_tests.js"]],
  ["node", ["scripts/quality_intake_engine_unit_tests.js"]],
  ["node", ["scripts/account_engine_unit_tests.js"]],
  ["node", ["scripts/exam_review_engine_unit_tests.js"]],
  ["node", ["scripts/question_audit_engine_unit_tests.js"]],
  ["node", ["scripts/item_analytics_engine_unit_tests.js"]],
  ["node", ["scripts/irt_calibration_engine_unit_tests.js"]],
  ["node", ["scripts/public_manifest_artifact_export_unit_tests.js"]],
  ["node", ["scripts/public_promotion_gate_unit_tests.js"]],
  ["node", ["scripts/audit_resolution_workflow_unit_tests.js"]],
  ["node", ["scripts/authoring_save_workflow_unit_tests.js"]],
  ["node", ["scripts/source_signal_save_workflow_unit_tests.js"]],
  ["cmd", ["/c", "npm", "run", "test:vite"]],
  ["node", ["scripts/export_public_manifest_artifact.js", "--check"]],
  ["node", ["scripts/static_audit_tests.js"]],
  ["python", ["scripts/math_verifier_tests.py"]],
  ["python", ["scripts/check_questions_unit_tests.py"]],
  ["python", ["scripts/sat_training_metadata_enrichment_unit_tests.py"]],
  ["python", ["scripts/sat_2026_readiness_unit_tests.py"]],
  ["python", ["scripts/public_backend_unit_tests.py"]],
  ["python", ["scripts/public_backup_unit_tests.py"]],
  ["python", ["scripts/public_restore_unit_tests.py"]],
  ["python", ["scripts/public_health_check_unit_tests.py"]],
  ["python", ["scripts/public_app_static_tests.py"]],
  ["python", ["scripts/public_deploy_static_tests.py"]],
  ["python", ["scripts/public_deploy_readiness_unit_tests.py"]],
  ["python", ["scripts/public_backend_load_smoke_unit_tests.py"]],
  ["python", ["scripts/public_postgres_migration_unit_tests.py"]],
  ["python", ["scripts/public_domain_verify_unit_tests.py"]],
  ["python", ["scripts/vite_legacy_parity_audit_unit_tests.py"]],
  ["python", ["scripts/audit_vite_legacy_parity.py"]],
  ["python", ["scripts/release_checklist_unit_tests.py"]],
  ["python", ["scripts/check_questions.py", "--summary-only"]],
  ["python", ["scripts/audit_sat_2026_readiness.py"]],
  ["python", ["scripts/audit_closed_loop_training_system.py"]],
  ["python", ["scripts/audit_sat_studio_implementation_plan.py"]],
  ["python", ["-m", "py_compile", "server.py", "sat_public_backend.py", "sat_public_app.py", "scripts/browser_smoke_test.py", "scripts/vite_student_smoke_test.py", "scripts/vite_parent_smoke_test.py", "scripts/vite_admin_smoke_test.py", "scripts/role_experience_smoke_test.py", "scripts/entry_role_smoke_test.py", "scripts/check_questions.py", "scripts/math_verifier.py", "scripts/antigravity_engine.py", "scripts/enforce_topic_pool_policy.py", "scripts/enrich_sat_training_metadata.py", "scripts/audit_sat_2026_readiness.py", "scripts/audit_closed_loop_training_system.py", "scripts/audit_sat_studio_implementation_plan.py", "scripts/audit_vite_legacy_parity.py", "scripts/sat_training_metadata_enrichment_unit_tests.py", "scripts/sat_2026_readiness_unit_tests.py", "scripts/public_backend_unit_tests.py", "scripts/public_backup_unit_tests.py", "scripts/public_restore_unit_tests.py", "scripts/public_health_check_unit_tests.py", "scripts/check_public_backend_health.py", "scripts/check_public_deploy_readiness.py", "scripts/restore_public_backend_backup.py", "scripts/public_backend_load_smoke.py", "scripts/check_postgres_migration_artifact.py", "scripts/verify_public_domain.py", "scripts/public_app_static_tests.py", "scripts/public_deploy_static_tests.py", "scripts/public_deploy_readiness_unit_tests.py", "scripts/public_backend_load_smoke_unit_tests.py", "scripts/public_postgres_migration_unit_tests.py", "scripts/public_domain_verify_unit_tests.py", "scripts/vite_legacy_parity_audit_unit_tests.py", "scripts/run_public_backend.py", "scripts/backup_public_backend.py", "scripts/release_checklist.py", "scripts/release_checklist_unit_tests.py"]],
];

if (includeSmoke) {
  commands.push(["python", ["scripts/browser_smoke_test.py"]]);
  commands.push(["python", ["scripts/vite_student_smoke_test.py"]]);
  commands.push(["python", ["scripts/vite_parent_smoke_test.py"]]);
  commands.push(["python", ["scripts/vite_admin_smoke_test.py"]]);
  commands.push(["python", ["scripts/entry_role_smoke_test.py"]]);
  commands.push(["python", ["scripts/role_experience_smoke_test.py"]]);
  commands.push(["python", ["scripts/student_experience_smoke_test.py"]]);
}

for (const [command, args] of commands) {
  const label = `${command} ${args.join(" ")}`;
  console.log(`\n> ${label}`);
  const result = spawnSync(command, args, { stdio: "inherit" });
  if (result.status !== 0) {
    console.error(`\nquality check failed: ${label}`);
    process.exit(result.status || 1);
  }
}

console.log(`\nquality checks passed${includeSmoke ? " with browser smoke" : ""}`);
