const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
const index = fs.readFileSync(path.join(root, "index.html"), "utf8");
const bootstrapLoader = fs.readFileSync(path.join(root, "sat_bootstrap_loader.js"), "utf8");
const viewRenderers = fs.readFileSync(path.join(root, "sat_view_renderers.js"), "utf8");
const adminViewRenderers = fs.readFileSync(path.join(root, "sat_admin_view_renderers.js"), "utf8");
const accountViewRenderers = fs.readFileSync(path.join(root, "sat_account_view_renderers.js"), "utf8");
const authoringEngine = fs.readFileSync(path.join(root, "sat_authoring_engine.js"), "utf8");
const importEngine = fs.readFileSync(path.join(root, "sat_import_engine.js"), "utf8");
const routerEngine = fs.readFileSync(path.join(root, "sat_router_engine.js"), "utf8");
const dashboardEngine = fs.readFileSync(path.join(root, "sat_dashboard_engine.js"), "utf8");
const adaptiveRoutingEngine = fs.readFileSync(path.join(root, "sat_adaptive_routing_engine.js"), "utf8");
const itemAnalyticsEngine = fs.readFileSync(path.join(root, "sat_item_analytics_engine.js"), "utf8");
const irtCalibrationEngine = fs.readFileSync(path.join(root, "sat_irt_calibration_engine.js"), "utf8");
const qualityIntakeEngine = fs.readFileSync(path.join(root, "sat_quality_intake_engine.js"), "utf8");
const accountEngine = fs.readFileSync(path.join(root, "sat_account_engine.js"), "utf8");
const questionQueryEngine = fs.readFileSync(path.join(root, "sat_question_query_engine.js"), "utf8");
const contentPackageEngine = fs.readFileSync(path.join(root, "sat_content_package_engine.js"), "utf8");
const learnerContentGateway = fs.readFileSync(path.join(root, "sat_learner_content_gateway.js"), "utf8");
const studyPolicyEngine = fs.readFileSync(path.join(root, "sat_study_policy_engine.js"), "utf8");
const samplerEngine = fs.readFileSync(path.join(root, "sat_sampler_engine.js"), "utf8");
const sourceLedger = fs.readFileSync(path.join(root, "sat_source_ledger.js"), "utf8");
const contentAdminEngine = fs.readFileSync(path.join(root, "sat_content_admin_engine.js"), "utf8");
const publicManifestEngine = fs.readFileSync(path.join(root, "sat_public_manifest_engine.js"), "utf8");
const designSystem = fs.readFileSync(path.join(root, "sat_design_system.js"), "utf8");
const roleBoundaryEngine = fs.readFileSync(path.join(root, "sat_role_boundary_engine.js"), "utf8");
const entryEngine = fs.readFileSync(path.join(root, "sat_entry_engine.js"), "utf8");
const appStudent = fs.readFileSync(path.join(root, "app_student.js"), "utf8");
const appParent = fs.readFileSync(path.join(root, "app_parent.js"), "utf8");
const appAdmin = fs.readFileSync(path.join(root, "app_admin.js"), "utf8");
const studentHtml = fs.readFileSync(path.join(root, "student.html"), "utf8");
const parentHtml = fs.readFileSync(path.join(root, "parent.html"), "utf8");
const adminHtml = fs.readFileSync(path.join(root, "admin.html"), "utf8");
const releaseChecklist = fs.readFileSync(path.join(root, "scripts", "release_checklist.py"), "utf8");
const checkQuestions = fs.readFileSync(path.join(root, "scripts", "check_questions.py"), "utf8");

function run() {
  assert.equal(/state\.questions\.find/.test(app), false, "Use getQuestionById() instead of state.questions.find(...) for ID lookups.");
  assert.equal(/\sstyle=/.test(app + index), false, "Do not render inline style= attributes.");

  const scriptOrder = [...(index + "\n" + bootstrapLoader).matchAll(/"([^"]+\.js)"/g)].map((match) => match[1]);
  const coreIndex = scriptOrder.indexOf("sat_core.js");
  const storageIndex = scriptOrder.indexOf("sat_storage.js");
  const indexedDbIndex = scriptOrder.indexOf("sat_indexeddb.js");
const publicApiIndex = scriptOrder.indexOf("sat_public_api.js");
const richTextIndex = scriptOrder.indexOf("sat_richtext.js");
  const designSystemIndex = scriptOrder.indexOf("sat_design_system.js");
const viewRenderersIndex = scriptOrder.indexOf("sat_view_renderers.js");
  const adminViewRenderersIndex = scriptOrder.indexOf("sat_admin_view_renderers.js");
  const accountViewRenderersIndex = scriptOrder.indexOf("sat_account_view_renderers.js");
  const permissionsIndex = scriptOrder.indexOf("sat_permissions.js");
  const roleBoundaryEngineIndex = scriptOrder.indexOf("sat_role_boundary_engine.js");
  const entryEngineIndex = scriptOrder.indexOf("sat_entry_engine.js");
  const sourceLedgerIndex = scriptOrder.indexOf("sat_source_ledger.js");
  const publicManifestEngineIndex = scriptOrder.indexOf("sat_public_manifest_engine.js");
  const questionQueryEngineIndex = scriptOrder.indexOf("sat_question_query_engine.js");
  const studyPolicyEngineIndex = scriptOrder.indexOf("sat_study_policy_engine.js");
  const samplerEngineIndex = scriptOrder.indexOf("sat_sampler_engine.js");
  const contentAdminEngineIndex = scriptOrder.indexOf("sat_content_admin_engine.js");
  const questionImportIndex = scriptOrder.indexOf("sat_question_import.js");
  const importEngineIndex = scriptOrder.indexOf("sat_import_engine.js");
  const routerEngineIndex = scriptOrder.indexOf("sat_router_engine.js");
  const dashboardEngineIndex = scriptOrder.indexOf("sat_dashboard_engine.js");
  const dataLoadersIndex = scriptOrder.indexOf("sat_data_loaders.js");
  const adaptiveRoutingEngineIndex = scriptOrder.indexOf("sat_adaptive_routing_engine.js");
  const diagnosticEngineIndex = scriptOrder.indexOf("sat_diagnostic_engine.js");
  const lessonEngineIndex = scriptOrder.indexOf("sat_lesson_engine.js");
  const remediationEngineIndex = scriptOrder.indexOf("sat_remediation_engine.js");
  const practiceEngineIndex = scriptOrder.indexOf("sat_practice_engine.js");
  const masteryEngineIndex = scriptOrder.indexOf("sat_mastery_engine.js");
  const roadmapEngineIndex = scriptOrder.indexOf("sat_roadmap_engine.js");
  const studentExperienceEngineIndex = scriptOrder.indexOf("sat_student_experience_engine.js");
  const itemAnalyticsEngineIndex = scriptOrder.indexOf("sat_item_analytics_engine.js");
  const irtCalibrationEngineIndex = scriptOrder.indexOf("sat_irt_calibration_engine.js");
  const duplicateEngineIndex = scriptOrder.indexOf("sat_duplicate_engine.js");
  const authoringEngineIndex = scriptOrder.indexOf("sat_authoring_engine.js");
  const qualityIntakeEngineIndex = scriptOrder.indexOf("sat_quality_intake_engine.js");
  const accountEngineIndex = scriptOrder.indexOf("sat_account_engine.js");
  const examReviewEngineIndex = scriptOrder.indexOf("sat_exam_review_engine.js");
  const questionAuditEngineIndex = scriptOrder.indexOf("sat_question_audit_engine.js");
  const appIndex = scriptOrder.indexOf("app.js");
  assert.ok(coreIndex >= 0, "sat_core.js must be loaded.");
  assert.ok(storageIndex >= 0, "sat_storage.js must be loaded.");
  assert.ok(indexedDbIndex >= 0, "sat_indexeddb.js must be loaded.");
  assert.ok(publicApiIndex >= 0, "sat_public_api.js must be loaded.");
  assert.ok(richTextIndex >= 0, "sat_richtext.js must be loaded.");
  assert.ok(designSystemIndex >= 0, "sat_design_system.js must be loaded.");
  assert.ok(viewRenderersIndex >= 0, "sat_view_renderers.js must be loaded.");
  assert.ok(adminViewRenderersIndex >= 0, "sat_admin_view_renderers.js must be loaded.");
  assert.ok(accountViewRenderersIndex >= 0, "sat_account_view_renderers.js must be loaded.");
  assert.ok(permissionsIndex >= 0, "sat_permissions.js must be loaded.");
  assert.ok(roleBoundaryEngineIndex >= 0, "sat_role_boundary_engine.js must be loaded.");
  assert.ok(entryEngineIndex >= 0, "sat_entry_engine.js must be loaded.");
  assert.ok(sourceLedgerIndex >= 0, "sat_source_ledger.js must be loaded.");
  assert.ok(publicManifestEngineIndex >= 0, "sat_public_manifest_engine.js must be loaded.");
  assert.ok(questionQueryEngineIndex >= 0, "sat_question_query_engine.js must be loaded.");
  assert.ok(studyPolicyEngineIndex >= 0, "sat_study_policy_engine.js must be loaded.");
  assert.ok(samplerEngineIndex >= 0, "sat_sampler_engine.js must be loaded.");
  assert.ok(contentAdminEngineIndex >= 0, "sat_content_admin_engine.js must be loaded.");
  assert.ok(questionImportIndex >= 0, "sat_question_import.js must be loaded.");
  assert.ok(importEngineIndex >= 0, "sat_import_engine.js must be loaded.");
  assert.ok(routerEngineIndex >= 0, "sat_router_engine.js must be loaded.");
  assert.ok(dashboardEngineIndex >= 0, "sat_dashboard_engine.js must be loaded.");
  assert.ok(dataLoadersIndex >= 0, "sat_data_loaders.js must be loaded.");
  assert.ok(adaptiveRoutingEngineIndex >= 0, "sat_adaptive_routing_engine.js must be loaded.");
  assert.ok(diagnosticEngineIndex >= 0, "sat_diagnostic_engine.js must be loaded.");
  assert.ok(lessonEngineIndex >= 0, "sat_lesson_engine.js must be loaded.");
  assert.ok(remediationEngineIndex >= 0, "sat_remediation_engine.js must be loaded.");
  assert.ok(practiceEngineIndex >= 0, "sat_practice_engine.js must be loaded.");
  assert.ok(masteryEngineIndex >= 0, "sat_mastery_engine.js must be loaded.");
  assert.ok(roadmapEngineIndex >= 0, "sat_roadmap_engine.js must be loaded.");
  assert.ok(studentExperienceEngineIndex >= 0, "sat_student_experience_engine.js must be loaded.");
  assert.ok(itemAnalyticsEngineIndex >= 0, "sat_item_analytics_engine.js must be loaded.");
  assert.ok(irtCalibrationEngineIndex >= 0, "sat_irt_calibration_engine.js must be loaded.");
  assert.ok(duplicateEngineIndex >= 0, "sat_duplicate_engine.js must be loaded.");
  assert.ok(authoringEngineIndex >= 0, "sat_authoring_engine.js must be loaded.");
  assert.ok(qualityIntakeEngineIndex >= 0, "sat_quality_intake_engine.js must be loaded.");
  assert.ok(accountEngineIndex >= 0, "sat_account_engine.js must be loaded.");
  assert.ok(examReviewEngineIndex >= 0, "sat_exam_review_engine.js must be loaded.");
  assert.ok(questionAuditEngineIndex >= 0, "sat_question_audit_engine.js must be loaded.");
  assert.ok(appIndex >= 0, "app.js must be loaded.");
  assert.ok(coreIndex < appIndex, "sat_core.js must load before app.js.");
  assert.ok(storageIndex < appIndex, "sat_storage.js must load before app.js.");
  assert.ok(indexedDbIndex < appIndex, "sat_indexeddb.js must load before app.js.");
  assert.ok(publicApiIndex < appIndex, "sat_public_api.js must load before app.js.");
  assert.ok(richTextIndex < appIndex, "sat_richtext.js must load before app.js.");
  assert.ok(designSystemIndex < appIndex, "sat_design_system.js must load before app.js.");
  assert.ok(richTextIndex < designSystemIndex, "sat_richtext.js should load before sat_design_system.js.");
  assert.ok(viewRenderersIndex < appIndex, "sat_view_renderers.js must load before app.js.");
  assert.ok(adminViewRenderersIndex < appIndex, "sat_admin_view_renderers.js must load before app.js.");
  assert.ok(accountViewRenderersIndex < appIndex, "sat_account_view_renderers.js must load before app.js.");
  assert.ok(permissionsIndex < appIndex, "sat_permissions.js must load before app.js.");
  assert.ok(roleBoundaryEngineIndex < appIndex, "sat_role_boundary_engine.js must load before app.js.");
  assert.ok(permissionsIndex < roleBoundaryEngineIndex, "sat_permissions.js should load before sat_role_boundary_engine.js.");
  assert.ok(entryEngineIndex < appIndex, "sat_entry_engine.js must load before app.js.");
  assert.ok(roleBoundaryEngineIndex < entryEngineIndex, "sat_role_boundary_engine.js should load before sat_entry_engine.js.");
  assert.ok(sourceLedgerIndex < appIndex, "sat_source_ledger.js must load before app.js.");
  assert.ok(publicManifestEngineIndex < appIndex, "sat_public_manifest_engine.js must load before app.js.");
  assert.ok(permissionsIndex < publicManifestEngineIndex, "sat_permissions.js must load before sat_public_manifest_engine.js.");
  assert.ok(questionQueryEngineIndex < appIndex, "sat_question_query_engine.js must load before app.js.");
  assert.ok(studyPolicyEngineIndex < appIndex, "sat_study_policy_engine.js must load before app.js.");
  assert.ok(samplerEngineIndex < diagnosticEngineIndex, "sat_sampler_engine.js must load before sat_diagnostic_engine.js.");
  assert.ok(contentAdminEngineIndex < appIndex, "sat_content_admin_engine.js must load before app.js.");
  assert.ok(questionQueryEngineIndex < contentAdminEngineIndex, "sat_question_query_engine.js should load before sat_content_admin_engine.js.");
  assert.ok(questionImportIndex < appIndex, "sat_question_import.js must load before app.js.");
  assert.ok(importEngineIndex < appIndex, "sat_import_engine.js must load before app.js.");
  assert.ok(routerEngineIndex < appIndex, "sat_router_engine.js must load before app.js.");
  assert.ok(dashboardEngineIndex < appIndex, "sat_dashboard_engine.js must load before app.js.");
  assert.ok(dataLoadersIndex < appIndex, "sat_data_loaders.js must load before app.js.");
  assert.ok(adaptiveRoutingEngineIndex < appIndex, "sat_adaptive_routing_engine.js must load before app.js.");
  assert.ok(dataLoadersIndex < adaptiveRoutingEngineIndex, "sat_data_loaders.js should load before sat_adaptive_routing_engine.js.");
  assert.ok(adaptiveRoutingEngineIndex < diagnosticEngineIndex, "sat_adaptive_routing_engine.js should load before sat_diagnostic_engine.js.");
  assert.ok(diagnosticEngineIndex < appIndex, "sat_diagnostic_engine.js must load before app.js.");
  assert.ok(lessonEngineIndex < appIndex, "sat_lesson_engine.js must load before app.js.");
  assert.ok(remediationEngineIndex < appIndex, "sat_remediation_engine.js must load before app.js.");
  assert.ok(practiceEngineIndex < appIndex, "sat_practice_engine.js must load before app.js.");
  assert.ok(masteryEngineIndex < appIndex, "sat_mastery_engine.js must load before app.js.");
  assert.ok(roadmapEngineIndex < appIndex, "sat_roadmap_engine.js must load before app.js.");
  assert.ok(studentExperienceEngineIndex < appIndex, "sat_student_experience_engine.js must load before app.js.");
  assert.ok(itemAnalyticsEngineIndex < appIndex, "sat_item_analytics_engine.js must load before app.js.");
  assert.ok(irtCalibrationEngineIndex < appIndex, "sat_irt_calibration_engine.js must load before app.js.");
  assert.ok(duplicateEngineIndex < appIndex, "sat_duplicate_engine.js must load before app.js.");
  assert.ok(authoringEngineIndex < appIndex, "sat_authoring_engine.js must load before app.js.");
  assert.ok(qualityIntakeEngineIndex < appIndex, "sat_quality_intake_engine.js must load before app.js.");
  assert.ok(authoringEngineIndex < qualityIntakeEngineIndex, "sat_authoring_engine.js must load before sat_quality_intake_engine.js.");
  assert.ok(accountEngineIndex < appIndex, "sat_account_engine.js must load before app.js.");
  assert.ok(examReviewEngineIndex < appIndex, "sat_exam_review_engine.js must load before app.js.");
  assert.ok(questionAuditEngineIndex < appIndex, "sat_question_audit_engine.js must load before app.js.");

  assert.ok(app.includes("SatStorage.readStoredStateJson"), "app.js should use SatStorage for local persistence.");
  assert.ok(app.includes("SatStorage.storedStateSnapshot"), "app.js should show local storage health.");
  assert.ok(app.includes("SatPublicApi.buildProgressSnapshot"), "app.js should expose the public backend adapter readiness.");
  assert.ok(app.includes("SatPublicManifestEngine.buildPublicManifest"), "app.js should use the shared public manifest gate.");
  assert.ok(app.includes("SatPublicManifestEngine.buildPublicManifestArtifact"), "app.js should export public manifest artifacts through the shared engine.");
  assert.ok(viewRenderers.includes("admin-export-public-manifest"), "Admin Center should expose a public manifest artifact export action.");
  assert.ok(publicManifestEngine.includes("buildPublicManifestArtifact"), "sat_public_manifest_engine.js should build manifest export artifacts.");
  assert.ok(publicManifestEngine.includes("stableContentChecksum"), "public manifest artifacts should include a stable content checksum.");
  assert.ok(index.includes("public-backend-status"), "index.html should expose public backend sync status UI.");
  assert.ok(index.includes("public-backend-auto-sync"), "index.html should expose an auto-sync toggle for backend progress.");
  assert.ok(index.includes("public-backend-refresh"), "index.html should expose backend token refresh UI.");
  assert.ok(index.includes("public-backend-sync-progress"), "index.html should expose manual progress sync UI.");
  assert.ok(index.includes("public-backend-sync-profile"), "index.html should expose full profile sync UI.");
  assert.ok(index.includes("public-backend-apply-profile"), "index.html should expose reviewed server profile apply UI.");
  assert.ok(index.includes("public-backend-monitoring"), "index.html should expose backend monitoring UI.");
  assert.ok(app.includes("PUBLIC_BACKEND_TOKEN_KEY"), "app.js should use a dedicated public backend token key.");
  assert.ok(app.includes("PUBLIC_BACKEND_COOKIE_SESSION"), "app.js should use an HttpOnly cookie session sentinel.");
  assert.ok(app.includes("sessionStorage.removeItem(PUBLIC_BACKEND_TOKEN_KEY"), "app.js should clear legacy browser-stored bearer tokens.");
  assert.ok(!app.includes("sessionStorage.setItem(PUBLIC_BACKEND_TOKEN_KEY"), "app.js must not persist backend bearer tokens in sessionStorage.");
  assert.ok(app.includes("SatPublicApi.saveProgress"), "app.js should sync local progress through the public API adapter.");
  assert.ok(app.includes("SatPublicApi.saveProfile"), "app.js should sync full learner profiles through the public API adapter.");
  assert.ok(app.includes("requestLearningProfileSync"), "app.js should enqueue backend-first learning profile sync after attempts, diagnostics, and roadmap updates.");
  assert.ok(app.includes("canAutoSyncLearningProfile"), "app.js should gate learning profile auto-sync behind backend session readiness.");
  assert.ok(app.includes("SatPublicApi.getProfile"), "app.js should load server profile metadata through the public API adapter.");
  assert.ok(app.includes("applyPendingServerProfile"), "app.js should require explicit review before applying a server profile.");
  assert.ok(app.includes("SatPublicApi.monitoring"), "app.js should read backend monitoring through the public API adapter.");
  assert.ok(app.includes("SatPublicApi.refreshSession"), "app.js should rotate public backend bearer tokens.");
  assert.ok(app.includes("SatPublicApi.logout"), "app.js should revoke backend sessions on logout.");
  assert.ok(app.includes("SatPublicApi.exportSnapshot"), "app.js should export server snapshots through the public API adapter.");
  assert.ok(app.includes("SatStudioIndexedDB.loadBank"), "app.js should load custom question banks from IndexedDB.");
  assert.ok(app.includes("SatStudioIndexedDB.saveBank"), "app.js should save custom question banks to IndexedDB.");
  assert.ok(app.includes("SatCore.buildQuestionIndex"), "app.js should use SatCore question indexing.");
  assert.ok(app.includes("SatQuestionQueryEngine.reviewedStudyQuestions"), "student content retrieval should use the reviewed study content API.");
  assert.ok(app.includes("reviewedContentRepositoryCache"), "student content retrieval should cache the reviewed repository by account/revision.");
  assert.ok(studyPolicyEngine.includes("question-study-policy.json"), "student content retrieval should load the lightweight study policy.");
  assert.ok(studyPolicyEngine.includes("suppressedDefaultStudyIds"), "student content retrieval should suppress low-priority overflow content from default study.");
  assert.ok(sourceLedger.includes("CrackSAT Reference"), "source ledger policy should live outside the browser shell.");
  assert.ok(samplerEngine.includes("selectQuestionsByBlueprint"), "SAT sampler should expose blueprint-based question selection.");
  assert.ok(samplerEngine.includes("buildSelectionAudit"), "SAT sampler should audit domain, difficulty, grid-in, and tool-tag balance.");
  assert.ok(samplerEngine.includes("buildDomainBlueprint"), "SAT sampler should build section blueprint quotas from SAT domain weights.");
  assert.ok(samplerEngine.includes("topicRepetitionReport"), "SAT sampler should report topic repetition against a cap.");
  assert.ok(checkQuestions.includes("question-study-policy.json"), "question integrity checks should write a lightweight study policy artifact.");
  assert.ok(app.includes("SatRichText.renderExplanation"), "app.js should use SatRichText for rich explanations.");
  assert.ok(app.includes("SatDesignSystem.loadingPanel"), "app.js should use SatDesignSystem for learner loading panels.");
  assert.ok(app.includes("SatDesignSystem.badge"), "app.js should use SatDesignSystem for shared badges.");
  assert.ok(app.includes("SatRoleBoundaryEngine.filterQuestionsForRole"), "app.js should role-scope visible question banks.");
  assert.ok(app.includes("SatRoleBoundaryEngine.roleQuestionForDisplay"), "app.js should sanitize student question display models.");
  assert.ok(app.includes("SatRoleBoundaryEngine.buildRolePreloadPlan"), "app.js should role-scope preload plans.");
  assert.ok(app.includes("SatEntryEngine.entryConfigFromLocation"), "app.js should consume entry-role configuration.");
  assert.ok(app.includes("applyEntryRoleGate"), "app.js should gate active accounts by entry role.");
  assert.ok(designSystem.includes("loadingPanel"), "sat_design_system.js should expose loading panels.");
  assert.ok(designSystem.includes("badge"), "sat_design_system.js should expose badges.");
  assert.ok(roleBoundaryEngine.includes("ROLE_ENTRY_POINTS"), "sat_role_boundary_engine.js should declare role entry point contracts.");
  assert.ok(roleBoundaryEngine.includes("scanStudentUiLeakage"), "sat_role_boundary_engine.js should expose student leakage scans.");
  assert.ok(entryEngine.includes("ENTRY_CONFIGS"), "sat_entry_engine.js should declare entry configs.");
  assert.ok(entryEngine.includes("entryConfigFromLocation"), "sat_entry_engine.js should resolve entry configs from URLs.");
  assert.ok(entryEngine.includes("evaluateScriptSequence"), "sat_entry_engine.js should enforce role script performance budgets.");
  assert.ok(bootstrapLoader.includes("SAT_STUDIO_SCRIPT_BUDGET"), "bootstrap loader should expose role script budget evaluation.");
  assert.ok(appStudent.includes('installEntryConfig(root, "student")'), "app_student.js should install the student entry config.");
  assert.ok(appParent.includes('installEntryConfig(root, "parent")'), "app_parent.js should install the parent entry config.");
  assert.ok(appAdmin.includes('installEntryConfig(root, "admin")'), "app_admin.js should install the admin entry config.");
  assert.ok(studentHtml.includes("dist/vite/vite-student.html"), "student.html should route to the Vite student app by default.");
  assert.ok(studentHtml.includes("entry=student"), "student.html should keep a legacy student fallback.");
  assert.ok(parentHtml.includes("dist/vite/vite-parent.html"), "parent.html should route to the Vite parent app by default.");
  assert.ok(parentHtml.includes("entry=parent"), "parent.html should keep a legacy parent fallback.");
  assert.ok(adminHtml.includes("dist/vite/vite-admin.html"), "admin.html should route to the Vite admin app by default.");
  assert.ok(adminHtml.includes("entry=admin"), "admin.html should keep a legacy admin fallback.");
  assert.ok(app.includes("SatViewRenderers.renderDiagnosticReadinessCards"), "app.js should use SatViewRenderers for diagnostic readiness UI.");
  assert.ok(app.includes("SatViewRenderers.renderDiagnosticReview"), "app.js should use SatViewRenderers for diagnostic review UI.");
  assert.ok(app.includes("SatViewRenderers.renderRoadmapEvaluationPanel"), "app.js should use SatViewRenderers for roadmap evaluation UI.");
  assert.ok(app.includes("SatViewRenderers.renderEliteReadinessPanel"), "app.js should use SatViewRenderers for elite readiness UI.");
  assert.ok(app.includes("SatViewRenderers.renderRemediationQueue"), "app.js should use SatViewRenderers for remediation queue UI.");
  assert.ok(app.includes("SatViewRenderers.renderQuestionStem"), "app.js should use SatViewRenderers for practice question stems.");
  assert.ok(app.includes("SatViewRenderers.renderAnswerInputHtml"), "app.js should use SatViewRenderers for answer inputs.");
  assert.ok(app.includes("SatViewRenderers.renderPublicBackendStatus"), "app.js should use SatViewRenderers for public backend status UI.");
  assert.ok(app.includes("SatViewRenderers.renderPracticeSessionEndedFeedback"), "app.js should use SatViewRenderers for practice session feedback UI.");
  assert.ok(app.includes("SatViewRenderers.renderPracticeFeedback"), "app.js should use SatViewRenderers for practice answer feedback UI.");
  assert.ok(app.includes("SatViewRenderers.renderKnowledgeReviewCard"), "app.js should use SatViewRenderers for knowledge review cards.");
  assert.ok(app.includes("SatAdminViewRenderers.renderGenerationIntakePanel"), "app.js should use SatAdminViewRenderers for generated-bank intake UI.");
  assert.ok(app.includes("SatAdminViewRenderers.renderSourceLedgerCards"), "app.js should use SatAdminViewRenderers for source ledger cards.");
  assert.ok(app.includes("SatAdminViewRenderers.renderArchiveRegistrySummary"), "app.js should use SatAdminViewRenderers for archive registry summary.");
  assert.ok(app.includes("SatAdminViewRenderers.renderArchiveRegistryList"), "app.js should use SatAdminViewRenderers for archive registry list.");
  assert.ok(app.includes("SatAdminViewRenderers.renderPublicationStatus"), "app.js should use SatAdminViewRenderers for publication status UI.");
  assert.ok(app.includes("SatAdminViewRenderers.renderQuestionAuditLog"), "app.js should use SatAdminViewRenderers for question audit logs.");
  assert.ok(app.includes("SatAdminViewRenderers.renderGeneratedDraftReviewCard"), "app.js should use SatAdminViewRenderers for authoring draft review cards.");
  assert.ok(app.includes("SatAccountViewRenderers.renderAccountOverview"), "app.js should use SatAccountViewRenderers for account overview.");
  assert.ok(app.includes("SatAccountViewRenderers.renderAccountList"), "app.js should use SatAccountViewRenderers for account lists.");
  assert.ok(app.includes("SatPermissions.isQuestionVisible"), "app.js should use SatPermissions for question visibility.");
  assert.ok(app.includes("SatPermissions.isQuestionBlockedForStudy"), "app.js should keep blocked/audit-failed questions out of practice.");
  assert.ok(app.includes("SatQuestionQueryEngine.visibleQuestionBank"), "app.js should use SatQuestionQueryEngine for visible bank caching.");
  assert.ok(app.includes("SatQuestionQueryEngine.filterQuestions"), "app.js should use SatQuestionQueryEngine for practice/topic filtering.");
  assert.ok(app.includes("SatQuestionQueryEngine.sourceLedgerStats"), "app.js should use SatQuestionQueryEngine for source ledger counts.");
  assert.ok(bootstrapLoader.includes("sat_content_package_engine.js"), "bootstrap loader should preload the backend content package engine for learners and admins.");
  assert.ok(bootstrapLoader.includes("sat_learner_content_gateway.js"), "bootstrap loader should preload the learner content gateway after the content package engine.");
  assert.ok(app.includes("SatLearnerContentGateway.loadReviewedStudyBank"), "app.js should delegate reviewed study-bank orchestration to SatLearnerContentGateway.");
  assert.ok(app.includes("savePublicContentPackageToBackend"), "admin export should save public learner content packages to backend when release gate is ready.");
  assert.ok(contentPackageEngine.includes("PUBLIC_CONTENT_FIELDS"), "content package engine should use an explicit public learner field allowlist.");
  assert.ok(contentPackageEngine.includes("buildPublicContentPackage"), "content package engine should build versioned public learner packages.");
  assert.ok(contentPackageEngine.includes("prepareImportedQuestions"), "content package engine should own backend package import normalization helpers.");
  assert.ok(contentPackageEngine.includes("canUseBackendPackage"), "content package engine should own backend package eligibility checks.");
  assert.ok(learnerContentGateway.includes("loadBackendContentPackage"), "learner content gateway should own backend package loading orchestration.");
  assert.ok(learnerContentGateway.includes("loadReviewedStudyBank"), "learner content gateway should own reviewed study-bank fallback orchestration.");
  assert.ok(learnerContentGateway.includes("replaceBackendContentPackageQuestions"), "learner content gateway should own learner package replacement.");
  assert.ok(viewRenderers.includes("Content package:"), "backend status UI should show public content-package sync state.");
  assert.ok(app.includes("SatContentAdminEngine.buildContentAdminCommandModel"), "app.js should use SatContentAdminEngine for content admin command modeling.");
  assert.ok(app.includes("applyIntegrityCandidatePolicy"), "app.js should expose admin actions for integrity topic governance.");
  assert.ok(app.includes("integrity-hide-candidates"), "integrity report should let admins hide topic overflow candidates.");
  assert.ok(app.includes("integrity-remedial-candidates"), "integrity report should let admins move topic overflow candidates to remediation.");
  assert.ok(app.includes("quarantineIntegrityBlockedRows"), "app.js should quarantine loaded copies of blocked integrity rows.");
  assert.ok(app.includes("integrity-quarantine-blocked"), "integrity report should expose a blocked-row quarantine action.");
  assert.ok(app.includes("importer?.normalizeQuestionRecord"), "app.js should use SatQuestionImport for import normalization with learner-bundle fallback.");
  assert.ok(app.includes("SatImportEngine.buildBankImportOptions"), "app.js should use SatImportEngine for question bank file import options.");
  assert.ok(app.includes("SatImportEngine.buildVaultSummary"), "app.js should use SatImportEngine for vault summaries.");
  assert.ok(app.includes("SatImportEngine.buildPdfInspectionModel"), "app.js should use SatImportEngine for PDF inspection workflow.");
  assert.ok(app.includes("SatImportEngine.buildOfficialPdfLog"), "app.js should use SatImportEngine for metadata-only official PDF logs.");
  assert.ok(app.includes("SatRouterEngine.buildViewState"), "app.js should use SatRouterEngine for page header view state.");
  assert.ok(app.includes("SatRouterEngine.applyViewDom"), "app.js should use SatRouterEngine for view activation.");
  assert.ok(app.includes("SatRouterEngine.buildViewPreloadPlan"), "app.js should use SatRouterEngine for view preload decisions.");
  assert.ok(app.includes("SatDashboardEngine.buildMetricsModel"), "app.js should use SatDashboardEngine for dashboard metrics.");
  assert.ok(app.includes("SatDashboardEngine.buildNextActionModel"), "app.js should use SatDashboardEngine for dashboard next action.");
  assert.ok(app.includes("SatDashboardEngine.buildRewardModel"), "app.js should use SatDashboardEngine for rewards.");
  assert.ok(app.includes("SatDataLoaders.shouldReloadReviewedSourceBank"), "app.js should treat reviewed source rows as one unified mixed bank.");
  assert.ok(app.includes("REVIEWED_SOURCE_BANK_MIN_COUNT"), "app.js should not hard-code fixed Kaplan/archive source counts for reviewed banks.");
  assert.ok(app.includes("SatAdaptiveRoutingEngine.buildAdaptiveRoutingProfile"), "app.js should enrich diagnostic results with adaptive routing confidence.");
  assert.ok(app.includes("SatAdaptiveRoutingEngine.routeForModule"), "app.js should use adaptive routing for diagnostic module progression.");
  assert.ok(adaptiveRoutingEngine.includes("buildQuestionRecommendationPlan"), "sat_adaptive_routing_engine.js should expose adaptive question recommendation plans.");
  assert.ok(adaptiveRoutingEngine.includes("confidenceForEvidence"), "sat_adaptive_routing_engine.js should gate routing by sample-size confidence.");
  assert.ok(app.includes("SatDiagnosticEngine.buildDiagnosticQuestionSet"), "app.js should use SatDiagnosticEngine for diagnostic question selection.");
  assert.ok(app.includes("SatDiagnosticEngine.buildDiagnosticReadiness"), "app.js should use SatDiagnosticEngine for diagnostic readiness.");
  assert.ok(app.includes("SatLessonEngine.lessonStageForSkill"), "app.js should use SatLessonEngine for lesson staging.");
  assert.ok(app.includes("SatLessonEngine.chooseProofQuestionForAttempt"), "app.js should use SatLessonEngine for proof question selection.");
  assert.ok(app.includes("SatRemediationEngine.buildAttemptRemediation"), "app.js should use SatRemediationEngine for remediation setup.");
  assert.ok(app.includes("SatRemediationEngine.buildAdaptiveRemediationQueue"), "app.js should use SatRemediationEngine for remediation queue scheduling.");
  assert.ok(app.includes("SatPracticeEngine.buildSessionCoachPlan"), "app.js should use SatPracticeEngine for practice coaching.");
  assert.ok(app.includes("SatPracticeEngine.buildAttemptRecord"), "app.js should use SatPracticeEngine for attempt records.");
  assert.ok(app.includes("SatMasteryEngine.computeSkillMasteryRows"), "app.js should use SatMasteryEngine for roadmap mastery.");
  assert.ok(app.includes("SatRoadmapEngine.buildRoadmapEvaluation"), "app.js should use SatRoadmapEngine for roadmap evaluation.");
  assert.ok(app.includes("SatItemAnalyticsEngine.buildItemAnalytics"), "app.js should use SatItemAnalyticsEngine for admin item-quality analytics.");
  assert.ok(app.includes("SatDuplicateEngine.buildDuplicateSkeletonScan"), "app.js should use SatDuplicateEngine for duplicate policy.");
  assert.ok(app.includes("SatAuthoringEngine.publicPromotionGate"), "app.js should use SatAuthoringEngine for public promotion.");
  assert.ok(app.includes("SatAuthoringEngine.autoValidateGeneratedDraft"), "app.js should use SatAuthoringEngine for draft validation.");
  assert.ok(app.includes("SatAuthoringEngine.buildSourceSignalDraft"), "app.js should use SatAuthoringEngine for source signal form flow.");
  assert.ok(app.includes("SatAuthoringEngine.buildManualQuestionDraft"), "app.js should use SatAuthoringEngine for manual question authoring.");
  assert.ok(app.includes("SatAuthoringEngine.sourceSignalDraftStats"), "app.js should use SatAuthoringEngine for source signal draft stats.");
  assert.ok(app.includes("SatQualityIntakeEngine.buildGenerationIntakeReport"), "app.js should use SatQualityIntakeEngine for generated-bank intake reporting.");
  assert.ok(app.includes("SatQualityIntakeEngine.applyGenerationIntakePolicy"), "app.js should use SatQualityIntakeEngine for generated-bank intake governance.");
  assert.ok(app.includes("integrity-apply-intake"), "integrity report should expose a generated-bank intake action.");
  assert.ok(app.includes("SatAccountEngine.currentAccount"), "app.js should use SatAccountEngine for active account resolution.");
  assert.ok(app.includes("SatAccountEngine.ensureAccountProfile"), "app.js should use SatAccountEngine for profile normalization.");
  assert.ok(app.includes("SatAccountEngine.buildAccountDraft"), "app.js should use SatAccountEngine for account creation.");
  assert.ok(app.includes("SatAccountEngine.visibleAccountsFor"), "app.js should use SatAccountEngine for account visibility.");
  assert.ok(app.includes("SatExamReviewEngine.buildPracticeSessionReport"), "app.js should use SatExamReviewEngine for session reports.");
  assert.ok(app.includes("SatExamReviewEngine.buildMistakeLedger"), "app.js should use SatExamReviewEngine for mistake ledger.");
  assert.ok(app.includes("SatQuestionAuditEngine.applyAuditReport"), "app.js should use SatQuestionAuditEngine for report escalation.");
  assert.ok(app.includes("SatQuestionAuditEngine.applyQuestionAuditBlock"), "app.js should use SatQuestionAuditEngine for public blocking.");
  assert.ok(viewRenderers.includes("renderPracticeSessionEndedFeedback"), "sat_view_renderers.js should render practice session feedback.");
  assert.ok(viewRenderers.includes("renderPracticeFeedback"), "sat_view_renderers.js should render practice answer feedback.");
  assert.ok(viewRenderers.includes("renderKnowledgeReviewCard"), "sat_view_renderers.js should render knowledge review cards.");
  assert.ok(viewRenderers.includes("renderDashboardWeakSkills"), "sat_view_renderers.js should render dashboard weak-skill rows.");
  assert.ok(viewRenderers.includes("renderDailyQuests"), "sat_view_renderers.js should render dashboard quest rows.");
  assert.ok(adminViewRenderers.includes("renderGenerationIntakePanel"), "sat_admin_view_renderers.js should render generated-bank intake panels.");
  assert.ok(adminViewRenderers.includes("renderSourceLedgerCards"), "sat_admin_view_renderers.js should render source ledger cards.");
  assert.ok(adminViewRenderers.includes("renderArchiveRegistrySummary"), "sat_admin_view_renderers.js should render archive registry summary.");
  assert.ok(adminViewRenderers.includes("renderArchiveRegistryList"), "sat_admin_view_renderers.js should render archive registry list.");
  assert.ok(adminViewRenderers.includes("renderPublicationStatus"), "sat_admin_view_renderers.js should render publication status UI.");
  assert.ok(adminViewRenderers.includes("renderQuestionAuditLog"), "sat_admin_view_renderers.js should render question audit logs.");
  assert.ok(adminViewRenderers.includes("renderGeneratedDraftReviewCard"), "sat_admin_view_renderers.js should render generated draft review cards.");
  assert.ok(adminViewRenderers.includes("renderSourceSignalList"), "sat_admin_view_renderers.js should render source signal lists.");
  assert.ok(adminViewRenderers.includes("renderBankImportResult"), "sat_admin_view_renderers.js should render bank import results.");
  assert.ok(adminViewRenderers.includes("renderVaultSummary"), "sat_admin_view_renderers.js should render vault summaries.");
  assert.ok(adminViewRenderers.includes("renderPdfInspection"), "sat_admin_view_renderers.js should render PDF inspection results.");
  assert.ok(accountViewRenderers.includes("renderAccountOverview"), "sat_account_view_renderers.js should render account overview.");
  assert.ok(accountViewRenderers.includes("renderAccountList"), "sat_account_view_renderers.js should render account lists.");
  assert.ok(authoringEngine.includes("buildSourceSignalDraft"), "sat_authoring_engine.js should build source signals from authoring forms.");
  assert.ok(authoringEngine.includes("buildManualQuestionDraft"), "sat_authoring_engine.js should build manual question drafts.");
  assert.ok(authoringEngine.includes("sourceSignalDraftStats"), "sat_authoring_engine.js should compute source signal draft stats.");
  assert.ok(importEngine.includes("buildBankImportOptions"), "sat_import_engine.js should build bank import options.");
  assert.ok(importEngine.includes("buildVaultSummary"), "sat_import_engine.js should build vault summaries.");
  assert.ok(importEngine.includes("buildPdfInspectionModel"), "sat_import_engine.js should build PDF inspection models.");
  assert.ok(routerEngine.includes("buildViewState"), "sat_router_engine.js should build active view state.");
  assert.ok(routerEngine.includes("buildViewPreloadPlan"), "sat_router_engine.js should build preload plans.");
  assert.ok(dashboardEngine.includes("buildMetricsModel"), "sat_dashboard_engine.js should build dashboard metrics.");
  assert.ok(dashboardEngine.includes("buildRewardModel"), "sat_dashboard_engine.js should build dashboard rewards.");
  assert.ok(accountEngine.includes("currentAccount"), "sat_account_engine.js should resolve active accounts.");
  assert.ok(accountEngine.includes("ensureAccountProfile"), "sat_account_engine.js should normalize account profiles.");
  assert.ok(qualityIntakeEngine.includes("buildGenerationIntakeReport"), "sat_quality_intake_engine.js should build intake reports.");
  assert.ok(qualityIntakeEngine.includes("applyGenerationIntakePolicy"), "sat_quality_intake_engine.js should apply intake governance.");
  assert.ok(questionQueryEngine.includes("filterQuestions"), "sat_question_query_engine.js should expose reusable question filtering.");
  assert.ok(questionQueryEngine.includes("QUESTION_BANK_CONTRACT_VERSION"), "sat_question_query_engine.js should expose a question bank contract version.");
  assert.ok(questionQueryEngine.includes("queryQuestionBank"), "sat_question_query_engine.js should expose scoped question-bank retrieval.");
  assert.ok(questionQueryEngine.includes("buildQuestionBankManifest"), "sat_question_query_engine.js should expose versioned question-bank manifests.");
  assert.ok(contentAdminEngine.includes("buildContentAdminCommandModel"), "sat_content_admin_engine.js should build the content admin command center model.");
  assert.ok(contentAdminEngine.includes("buildItemAnalyticsSignals"), "sat_content_admin_engine.js should surface item analytics in Quality Lab.");
  assert.ok(itemAnalyticsEngine.includes("calibrationResponseCount"), "item analytics should separate independent calibration attempts from helped responses.");
  assert.ok(irtCalibrationEngine.includes("deferred_insufficient_data"), "IRT calibration should defer fitting until response thresholds are met.");
  assert.ok(irtCalibrationEngine.includes("fitIrt2PL"), "IRT calibration engine should expose a guarded 2PL fitting entry point.");
  assert.ok(contentAdminEngine.includes("POST_UPLOAD_CHECKS"), "sat_content_admin_engine.js should define post-upload verification checks.");
  assert.ok(releaseChecklist.includes("PRODUCTION_READINESS_CONTRACT"), "release_checklist.py should codify production readiness gates.");
  assert.ok(releaseChecklist.includes("P4 production readiness contract"), "release_checklist.py should block release when P4 gates fail.");
}

run();
console.log("static_audit_tests: pass");
