(function initSatSourceLedger(root, factory) {
  const sourceLedger = factory();
  if (typeof module === "object" && module.exports) {
    module.exports = sourceLedger;
  }
  if (root) {
    root.SatSourceLedger = sourceLedger;
  }
})(typeof window !== "undefined" ? window : globalThis, function createSatSourceLedger() {
  return {
    original: {
      name: "Original Draft",
      use: "Reusable after internal review",
      risk: "Low",
      note: "Questions authored inside this project. Keep reviewer name and revision history before public release.",
    },
    opensat: {
      name: "OpenSAT / PineSAT",
      use: "Database use allowed by OpenSAT license note",
      risk: "Medium",
      note: "Import as seed material only. Mark every item needs_review until checked for accuracy and originality.",
    },
    foundation: {
      name: "SAT Studio Foundation Bank",
      use: "Original items with free-source references",
      risk: "Low after review",
      note: "Original SAT Studio practice questions. Concept/source notes live in data/free-source-registry.json.",
    },
    private_vault: {
      name: "Private Family Vault",
      use: "Family/admin-child access only",
      risk: "High if copied into public release",
      note: "Use only for private family study. Do not expose to public accounts, exports, or public question lists.",
    },
    ai_generated: {
      name: "AI Generated Drafts",
      use: "Original draft after admin review",
      risk: "Medium until similarity/source review",
      note: "Generated from skill blueprints and source metadata. Must not copy official or third-party wording.",
    },
    antigravity: {
      name: "Antigravity Testbank",
      use: "Private generated drafts until SAT Studio review",
      risk: "Medium until schema, answer, and duplicate checks pass",
      note: "Generated by the Antigravity worker. SAT Studio imports these as private review candidates and keeps them out of public accounts until explicitly approved.",
    },
    sat_king: {
      name: "SAT King Supplemental",
      use: "Public-candidate original drills",
      risk: "Low after internal review",
      note: "Original SAT Studio items built to fill official-domain gaps, including harder R/W and Math grid-in practice.",
    },
    sat_1590: {
      name: "SAT 1590 Elite Bank",
      use: "High-score public-candidate drills",
      risk: "Low after internal review",
      note: "Original high-difficulty SAT Studio items for 1550-1590 practice. Built from official domain blueprints and high-score skill patterns, not copied source text.",
    },
    cracksat_reference: {
      name: "CrackSAT Reference",
      use: "Reference/link only unless permission is granted",
      risk: "High",
      note: "CrackSAT copyright page says material on the website cannot be reproduced in any format.",
    },
    official_log: {
      name: "Official Practice Log",
      use: "Progress metadata only",
      risk: "Low if no official text is stored",
      note: "Do not store official prompts, passages, answer choices, or explanations without written permission.",
    },
    college_board: {
      name: "College Board Official Content",
      use: "Link out or manual study only",
      risk: "High",
      note: "Official questions are not reusable in a public app unless explicit permission is granted.",
    },
  };
});
